homeassistant:
  customize:
    alarm_control_panel.home:
       friendly_name: 'Alarma'

recorder:
  include:
    entities:
      - alarm_control_panel.home

alarm_control_panel:
  - platform: manual
    name: home
    # Time in seconds to leave the building before triggering the alarm
    pending_time: 0
    # Time in seconds to disarm the alarm when coming back
    delay_time: 0
    # Time in seconds to keep the triggered status
    trigger_time: 120
    # Alarm will return to it's previous state after trigger time
    disarm_after_trigger: false
    disarmed:
      # Never triggers the alarm
      trigger_time: 0
    armed_home:
      # Don't wait to trigger the alarm
      delay_time: 0
    armed_night:
      # Don't wait to trigger the alarm
      delay_time: 0

script:
  zzz_slack_test:
    alias: 'zzSlack test'
    sequence:
      - service: notify.slack
        data_template:
          message: ''
          data:
            attachments:
              - color: 'danger'
                pretext: ':bell: *Alarma* :bell:'
                text: 'Movimiento detectado en Prueba'
                fallback: 'Alarma'
              - color: '#3AA3E3'
                title: 'Quieres'
                callback_id: 'alarma_test'
                attachment_type: 'default'
                actions: 
                  - name: 'desactivar_test'
                    text: 'Desactivar det. mov. test'
                    type: 'button'
                    value: 'homeassistant.turn_off#sensor.prueba'
                  - name: 'desarmar_alarma'
                    text: 'Desarmar alarma'
                    type: 'button'
                    value: 'script.turn_on#script.alarm_disarm_slack'

  alarm_arm_away:
    alias: 'Alarm arm away'
    sequence:
      # Turn on alarm related sensors
      - service: homeassistant.turn_on
        data:
          entity_id: group.seguridad
      # Arm alarm
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home

  alarm_arm_night:
    alias: 'Alarm arm night'
    sequence:
      # Turn on alarm related sensors
      - service: homeassistant.turn_on
        data:
          entity_id: group.seguridad
      # Alarm arm night
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home

  alarm_disarm_telegram:
    alias: 'Alarm disarm from telegram'
    sequence:
      # Alarm disarm
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
      # Send message
      - service: telegram_bot.send_message
        data_template:
          message: 'Alarma desarmada manualmente desde Telegram'
          target: 
            - !secret hokusphone_telegram_chat_id
            #- !secret geniphone_telegram_chat_id
          disable_notification: false
          inline_keyboard:
                 - 'Armar alarma:/script.turn_on#script.alarm_arm_away'

  alarm_disarm_slack:
    alias: 'Alarm disarm from slack'
    sequence:
      # Alarm disarm
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
      # Send message
      - service: notify.slack
        data_template:
          message: ''
          data:
            attachments:
              - color: 'danger'
                pretext: ':bell: *Alarma* :bell:'
                text: 'Alarma desarmada desde slack'
                fallback: 'Alarma'

  alarm_disarm_telegram_temporary:
    alias: 'Temporary alarm disarm from telegram'
    sequence:
      # Alarm disarm
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
      # Send message
      - service: telegram_bot.send_message
        data_template:
          message: 'Alarma desarmada durante {{data.minutes}} minutos desde Telegram'
          target: 
            - !secret hokusphone_telegram_chat_id
            #- !secret geniphone_telegram_chat_id
          disable_notification: false
          inline_keyboard:
                 - 'Armar alarma:/script.turn_on#script.alarm_arm_away'
      # Wait specified time before arming the alarm again
      - delay: "{{ data.minutes | multiply(60) | timestamp_custom('%H:%M:%S',False) }}"
      # Alarm arm away
      - service: script.turn_on
        data:
          entity_id: script.alarm_arm_away

  alarm_notify_camera:
    alias: 'Notifies camera motion detection with photo/video attached'
    sequence:
      # Notify to slack
      - service: notify.slack
        data_template:
          message: ''
          data:
            attachments:
              - color: 'danger'
                pretext: ':bell: *Alarma* :bell:'
                text: 'Movimiento detectado en {{data.camera_name}}'
                fallback: 'Alarma'
              - color: 'danger'
                title: '¿Qué quieres hacer?'
                callback_id: 'alarma_{{data.camera_name}}'
                attachment_type: 'default'
                actions: 
                  - name: 'desactivar_{{data.camera_name}}'
                    text: 'Desactivar det. mov. {{data.camera_name}}'
                    type: 'button'
                    value: 'homeassistant.turn_off#{{data.turn_off_entity_id}}'
                  - name: 'desarmar_alarma'
                    text: 'Desarmar alarma'
                    type: 'button'
                    value: 'script.turn_on#script.alarm_disarm_slack'

      # Send the video to slack
      - service: notify.slack
        data_template:
          message: ''
          data:
            file:
              path: '{{data.file}}'

      # Continue to notify in telegram only if jpg or mp4 video
      - condition: template
        value_template: '{{ "jpg" in data.file or "mp4" in data.file }}'

      # Notify to telegram
      - service_template: >-
          {%- if "jpg" in data.file -%}
            telegram_bot.send_photo
          {%- elif "mp4" in data.file -%}
            telegram_bot.send_video
          {%- endif -%}
  
        data_template:
          file: '{{data.file}}'
          caption: 'Movimiento detectado en {{data.camera_name}}'
          target: 
            - !secret hokusphone_telegram_chat_id
            #- !secret geniphone_telegram_chat_id
          disable_notification: false
          inline_keyboard:
            - 'Desactivar det. mov. {{data.camera_name}}:/homeassistant.turn_off#{{data.turn_off_entity_id}}'
            - 'Desarmar 30 mins:/30_mins, Desarmar 1 hora:/60_mins'
            - 'Desarmar 2 horas:/120_mins, Desarmar 3 horas:/180_mins'
            - 'Desarmar alarma:/script.turn_on#script.alarm_disarm_telegram'

  alarm_notify_sensor:
    alias: 'Notifies alarm'
    sequence:
      # Send the notification
      - service: telegram_bot.send_message
        data_template:
          message: '{{data.message}}'
          target: 
            - !secret hokusphone_telegram_chat_id
            #- !secret geniphone_telegram_chat_id
          disable_notification: false
          inline_keyboard:
            - 'Desactivar sensor:/homeassistant.turn_off#{{data.turn_off_entity_id}}'
            - 'Desarmar 30 mins:/30_mins, Desarmar 1 hora:/60_mins'
            - 'Desarmar 2 horas:/120_mins, Desarmar 3 horas:/180_mins'
            - 'Desarmar alarma:/script.turn_on#script.alarm_disarm_telegram'
  
      - service: notify.slack
        data_template:
          message: ''
          data:
            attachments:
              - color: 'danger'
                pretext: ':bell: *Alarma* :bell:'
                text: '{{data.message}}'
                fallback: 'Alarma'
