homeassistant:
  customize:
    sensor.ioniq_batt:
      friendly_name: 'Batería'
      device_class: 'battery'
    sensor.ioniq_soc_display:
      friendly_name: 'Batería mostrada'
      device_class: 'battery'
    sensor.ioniq_soc_bms:
      friendly_name: 'Batería BMS'
      device_class: 'battery'
    sensor.ioniq_odometer:
      friendly_name: 'Odómetro'
      icon: 'mdi:counter'
    sensor.ioniq_efficiency:
      friendly_name: 'Consumo'
      icon: 'mdi:car-electric'
    sensor.ioniq_battery_health:
      friendly_name: 'Salud batería'
      device_class: 'battery'
    sensor.ioniq_gps_accuracy:
      friendly_name: 'Precisión GPS'
      icon: 'mdi:map-marker-radius'
    sensor.ioniq_last_update:
      friendly_name: 'Última actualización'
      icon: 'mdi:clock'
    sensor.nissan_batt:
      friendly_name: 'Batería'
      device_class: 'battery'
    sensor.nissan_gps_accuracy:
      friendly_name: 'Precisión GPS'
      icon: 'mdi:map-marker-radius'
    sensor.nissan_last_update:
      friendly_name: 'Última actualización'
      icon: 'mdi:clock'

recorder:
  exclude:
    entities:
      - sensor.ioniq_previous_latitude
      - sensor.ioniq_previous_longitude
      - sensor.ioniq_last_update

      - sensor.nissan_last_update

group:
  Ioniq:
    entities:
      - device_tracker.ioniq
      - sensor.ioniq_soc_display
      - sensor.ioniq_soc_bms
      - sensor.ioniq_odometer
      - sensor.ioniq_efficiency
      - sensor.ioniq_battery_health
      - sensor.ioniq_gps_accuracy
      - sensor.ioniq_last_update
      - sensor.ioniq_distance_travelled_between_updates
      - binary_sensor.car_charging
      - switch.wemoinsight
      - sensor.insight_powerused
      - sensor.monthly_energy_insight_pico
      - sensor.monthly_energy_insight_valle
      - sensor.car_monthly_energy_cost
      - sensor.yearly_energy_insight_pico
      - sensor.yearly_energy_insight_valle
      - sensor.car_yearly_energy_cost
      - camera.ioniq

  Nissan:
    entities:
      - device_tracker.nissan
      - sensor.nissan_batt
      - sensor.nissan_gps_accuracy
      - sensor.nissan_last_update
      - camera.nissan

device_tracker:
  - platform: mqtt_json
    devices:
      # Ioniq tracker
      ioniq: car/ioniq/location
      # Nissan tracker
      nissan: car/nissan/location

sensor:
  - platform: mqtt
    state_topic: 'car/nissan/location'
    name: nissan_batt
    unit_of_measurement: '%'
    value_template: '{{ value_json.battery_level }}'
  
  - platform: mqtt
    state_topic: 'car/nissan/location'
    name: nissan_gps_accuracy
    unit_of_measurement: 'm'
    value_template: '{{ value_json.gps_accuracy }}'
  
  - platform: mqtt
    state_topic: 'car/nissan/location'
    name: nissan_last_update
    value_template: '{{ value_json.last_update|timestamp_custom("%d/%m/%Y %H:%M:%S") }}'
  
  - platform: mqtt
    state_topic: 'car/ioniq/location'
    name: ioniq_batt
    unit_of_measurement: '%'
    value_template: '{{ value_json.battery_level }}'
  
  - platform: mqtt
    state_topic: 'car/ioniq/location'
    name: ioniq_gps_accuracy
    unit_of_measurement: 'm'
    value_template: '{{ value_json.gps_accuracy }}'
  
  - platform: mqtt
    state_topic: 'car/ioniq/location'
    name: ioniq_last_update
    value_template: '{{ value_json.last_update|timestamp_custom("%d/%m/%Y %H:%M:%S") }}'
  
  - platform: mqtt
    state_topic: 'car/ioniq/location'
    name: ioniq_previous_latitude
    value_template: '{{ value_json.platitude }}'
  
  - platform: mqtt
    state_topic: 'car/ioniq/location'
    name: ioniq_previous_longitude
    value_template: '{{ value_json.plongitude }}'

  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: ioniq_soc_display
    value_template: '{{value_json.soc_display}}'
    unit_of_measurement: '%'
  
  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: ioniq_battery_health
    value_template: '{{value_json.soh}}'
    unit_of_measurement: '%'
  
  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: ioniq_soc_bms
    value_template: '{{value_json.soc_bms}}'
    unit_of_measurement: '%'
  
  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: ioniq_odometer
    value_template: '{{value_json.distance}}'
    unit_of_measurement: 'Km'
  
  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: ioniq_ced
    value_template: '{{value_json.ced}}'
    unit_of_measurement: 'kWh'
  
  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: ioniq_cec
    value_template: '{{value_json.cec}}'
    unit_of_measurement: 'kWh'

  - platform: template
    sensors:
      ioniq_efficiency:
        friendly_name: 'Consumo medio'
        value_template: '{{ ((states.sensor.ioniq_ced.state | float / states.sensor.ioniq_odometer.state | float) * 100) | round(1)}}'
        unit_of_measurement: 'kWh/100Km'
        entity_id:
          - sensor.ioniq_ced
          - sensor.ioniq_odometer

  - platform: template
    sensors:
      ioniq_distance_travelled_between_updates:
        unit_of_measurement: 'm'
        friendly_name: 'Dist. entre actualizaciones'
        value_template: '{% if states.device_tracker.ioniq.attributes.latitude %} {{ (distance(states("sensor.ioniq_previous_latitude"), states("sensor.ioniq_previous_longitude"), states.device_tracker.ioniq.attributes.latitude, states.device_tracker.ioniq.attributes.longitude) * 1000) | round (2) }} {% else %} -1 {% endif %}'
        icon_template: 'mdi:tape-measure'
        entity_id: device_tracker.ioniq, sensor.ioniq_previous_latitude, sensor.ioniq_previous_longitude

  # Google travel time to work
  - platform: google_travel_time
    name: 'a la oficina'
    api_key: !secret google_api_key
    origin: device_tracker.ioniq
    destination: zone.oficina
    options:
      language: es
      departure_time: now
      traffic_model: pessimistic
  
  # Google travel time to school
  - platform: google_travel_time
    name: 'al colegio'
    api_key: !secret google_api_key
    origin: device_tracker.ioniq
    destination: zone.colegio
    options:
      language: es
      departure_time: now
      traffic_model: pessimistic

camera:
  - platform: generic
    name: Ioniq
    still_image_url: !secret camera_ioniq_still_image_url
    limit_refetch_to_url_change: true
  
#  - platform: generic
#    name: Nissan
#    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.nissan.attributes.latitude }},{{ states.device_tracker.nissan.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:grey%7Clabel:N%7C{{ states.device_tracker.nissan.attributes.latitude }},{{ states.device_tracker.nissan.attributes.longitude }}
#    limit_refetch_to_url_change: true

automation:
#############################################################
# Alarm automations
#############################################################
  # Notify Ioniq movement if I'm not in the car
  - alias: 'Notify ioniq movement if I am not in the car'
    trigger:
      platform: numeric_state
      entity_id: sensor.ioniq_distance_travelled_between_updates
      above: 50
      for:
        seconds: 30
    condition:
      condition: template
      value_template: '{{ states.device_tracker.jordi_combined.state != "En ruta" }}'
    action:
      - service: notify.telegram
        data_template:
          message: 'Movimiento del ioniq de unos {{ sensor.ioniq_distance_travelled_between_updates.state }} metros detectado'
      - service: telegram_bot.send_location
        data_template:
          latitude: '{{ states.device_tracker.ioniq.attributes.latitude }}'
          longitude: '{{ states.device_tracker.ioniq.attributes.longitude }}'
          target: !secret hokusphone_telegram_chat_id
