homeassistant:
  customize:
    sensor.car_ioniq_location:
      friendly_name: 'Última actualización'
      #icon: 'mdi:clock'
      entity_picture: '/local/ioniq-icon.png'
    sensor.car_ioniq_charge_state:
      friendly_name: 'Estado carga'
      icon: 'mdi:flash-circle'
    sensor.car_al_colegio:
      friendly_name: 'Al colegio'
    sensor.car_a_la_oficina:
      friendly_name: 'A la oficina'
    binary_sensor.car_ioniq_state:
      friendly_name: 'Estado'
    camera.car_ioniq:
      friendly_name: 'Ioniq'

recorder:
  exclude:
    entities:
      - sensor.car_ioniq_location_previous_latitude
      - sensor.car_ioniq_location_previous_longitude
      - sensor.car_ioniq_location_last_update

device_tracker:
  - platform: mqtt_json
    devices:
      # Ioniq tracker
      car_ioniq: car/ioniq/location
      # Nissan tracker
      #nissan: car/nissan/location

binary_sensor:
  - platform: mqtt
    state_topic: 'car/ioniq/state'
    name: car_ioniq_state
    value_template: 'ON'
    json_attributes_topic: 'car/ioniq/state'
    device_class: 'moving'
    force_update: true
    off_delay: 180

sensor:
  - platform: mqtt
    state_topic: 'car/ioniq/location'
    name: car_ioniq_location
    value_template: '{{ value_json.last_update|timestamp_custom("%d/%m/%Y %H:%M:%S") }}'
    json_attributes_topic: 'car/ioniq/location'

  - platform: template
    sensors:
      # Ioniq State Of Charge display
      car_ioniq_state_soc_display:
        friendly_name: 'Batería mostrada'
        device_class: 'battery'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state", "soc_display")}}'
        unit_of_measurement: '%'
      # Ioniq State Of Health
      car_ioniq_state_battery_health:
        friendly_name: 'Salud batería'
        device_class: 'battery'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state", "soh")}}'
        unit_of_measurement: '%'
      # Ioniq State Of Charge BMS
      car_ioniq_state_soc_bms:
        friendly_name: 'Batería BMS'
        device_class: 'battery'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state", "soc_bms")}}'
        unit_of_measurement: '%'
      # Ioniq odometer
      car_ioniq_state_odometer:
        friendly_name: 'Odómetro'
        icon_template: 'mdi:counter'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state", "distance")}}'
        unit_of_measurement: 'Km'
      # Ioniq Cumulative Energy Discharged
      car_ioniq_state_ced:
        value_template: '{{state_attr("binary_sensor.car_ioniq_state", "ced")}}'
        unit_of_measurement: 'kWh'
      # Ioniq Cumulative Energy Charged
      car_ioniq_state_cec:
        value_template: '{{state_attr("binary_sensor.car_ioniq_state", "cec")}}'
        unit_of_measurement: 'kWh'
      # Ioniq Average energy consumption without taking into account regeneration
      car_ioniq_state_energy_consumption:
        friendly_name: 'Consumo medio'
        icon_template: 'mdi:car-electric'
        value_template: '{{ ((states.sensor.car_ioniq_state_ced.state | float / states.sensor.car_ioniq_state_odometer.state | float) * 100) | round(1)}}'
        unit_of_measurement: 'kWh/100Km'
        entity_id:
          - sensor.car_ioniq_state_ced
          - sensor.car_ioniq_state_odometer
      # Ioniq Previous latitude
      car_ioniq_location_previous_latitude:
        value_template: '{{state_attr("sensor.car_ioniq_location", "platitude")}}'
        entity_id: 
          - sensor.car_ioniq_location
      # Ioniq Previous longitude
      car_ioniq_location_previous_longitude:
        value_template: '{{state_attr("sensor.car_ioniq_location", "plongitude")}}'
        entity_id: 
          - sensor.car_ioniq_location
      # Ioniq Distance travelled between updates
      car_ioniq_location_distance_travelled_between_updates:
        unit_of_measurement: 'm'
        friendly_name: 'Dist. entre actualizaciones'
        value_template: '{% if states.device_tracker.car_ioniq.attributes.latitude %} {{ (distance(states("sensor.car_ioniq_location_previous_latitude"), states("sensor.car_ioniq_location_previous_longitude"), states.device_tracker.car_ioniq.attributes.latitude, states.device_tracker.car_ioniq.attributes.longitude) * 1000) | round (2) }} {% else %} -1 {% endif %}'
        icon_template: 'mdi:tape-measure'
        entity_id: 
          - device_tracker.car_ioniq
          - sensor.car_ioniq_location_previous_latitude
          - sensor.car_ioniq_location_previous_longitude
      # Ioniq GPS accuracy
      car_ioniq_location_gps_accuracy:
        unit_of_measurement: 'm'
        friendly_name: 'Precisión GPS'
        value_template: '{{state_attr("device_tracker.car_ioniq", "gps_accuracy")}}'
        icon_template: 'mdi:map-marker-radius'
        entity_id: 
          - device_tracker.car_ioniq
      car_ioniq_charge_state:
        value_template: >-
          {%- if states('sensor.energy_car_charger_powerused')|float > 1000.0 or is_state_attr('binary_sensor.car_ioniq_state', 'charging', 1) %}
             Cargando
          {%- elif is_state('switch.energy_car_charger', 'off') %}
            Apagado
          {% else %}
            Listo
          {%- endif %}
        entity_id: 
          - switch.energy_car_charger
          - binary_sensor.energy_car_charging
          - binary_sensor.car_ioniq_state

  # Google travel time to work
  - platform: google_travel_time
    name: 'car_a_la_oficina'
    api_key: !secret google_api_key
    origin: device_tracker.car_ioniq
    destination: zone.oficina
    options:
      language: es
      departure_time: now
      traffic_model: pessimistic
  
  # Google travel time to school
  - platform: google_travel_time
    name: 'car_al_colegio'
    api_key: !secret google_api_key
    origin: device_tracker.car_ioniq
    destination: zone.colegio
    options:
      language: es
      departure_time: now
      traffic_model: pessimistic

camera:
  - platform: generic
    name: car_ioniq
    still_image_url: !secret camera_ioniq_still_image_url
    limit_refetch_to_url_change: true