recorder:
  include:
    entities:
      - binary_sensor.car_ioniq_state
      - sensor.car_ioniq_charge_state
      - switch.car_ioniq_charger
      - sensor.car_ioniq_charger_current_power
      - sensor.car_ioniq_location_distance_travelled_between_updates
      - sensor.car_ioniq_state_odometer
      - sensor.car_ioniq_state_soc_display
      - sensor.car_ioniq_state_soc_bms
      - sensor.cargador_aragon
      - sensor.cargador_conquistador
      - sensor.cargador_palmanyola
      - sensor.cargador_sant_miquel

logbook:
  exclude:
    entities:
      - sensor.car_ioniq_charger_current_power
      - sensor.car_ioniq_location_distance_travelled_between_updates
      - sensor.car_ioniq_state_odometer
      - sensor.car_ioniq_state_soc_display
      - sensor.car_ioniq_state_soc_bms

device_tracker:
  - platform: mqtt_json
    devices:
      # Ioniq tracker
      car_ioniq: car/sensor/ioniq/location
      # Nissan tracker
      #nissan: car/nissan/location

binary_sensor:
  - platform: mqtt
    state_topic: 'car/sensor/ioniq/state'
    name: car_ioniq_state_sensor
    value_template: 'ON'
    json_attributes_topic: 'car/sensor/ioniq/state'
    force_update: true
    off_delay: 90

  - platform: mqtt
    state_topic: 'car/sensor/ioniq/location'
    name: car_ioniq_location_sensor
    value_template: 'ON'
    json_attributes_topic: 'car/sensor/ioniq/location'
    force_update: true
    off_delay: 45

  - platform: template
    sensors:
      car_ioniq_state:
        friendly_name: "Estado Ioniq"
        device_class: 'moving'
        value_template: "{{is_state('binary_sensor.car_ioniq_location_sensor', 'on') or is_state('binary_sensor.car_ioniq_state_sensor', 'on')}}"

sensor:
  - platform: integration 
    source: sensor.car_ioniq_charger_current_power
    name: car_ioniq_charger_spent
    unit_prefix: k
    round: 2

#  - platform: mqtt
#    state_topic: 'car/sensor/ioniq/location'
#    name: car_ioniq_location
#    value_template: '{{ value_json.last_update|timestamp_custom("%d/%m/%Y %H:%M:%S") }}'
#    json_attributes_topic: 'car/sensor/ioniq/location'

  - platform: mqtt
    state_topic: 'car/sensor/ioniq/state/daily'
    name: car_ioniq_state_daily
    value_template: '{{ value_json.timestamp|timestamp_custom("%d/%m/%Y %H:%M:%S") }}'
    json_attributes_topic: 'car/sensor/ioniq/state/daily'

  - platform: dweet
    name: 'Cargador Conquistador'
    device: ximelib_41
    value_template: >-
          {%- if value_json.status == 'OCCUPIED_PARTIAL' %}
            Parcialmente ocupado
          {% elif value_json.status == 'OCCUPIED' %}
            Ocupado
          {% elif value_json.status == 'UNAVAILABLE' %}
            Estado no disponible
          {% elif value_json.status == 'AVAILABLE' %}
            Libre
          {% elif value_json.status == 'OFFLINE' %}
            No gestionado
          {% else %}
            Desconocido
          {%- endif %}

  - platform: dweet
    name: 'Cargador Aragón'
    device: ximelib_38
    value_template: >-
          {%- if value_json.status == 'OCCUPIED_PARTIAL' %}
            Parcialmente ocupado
          {% elif value_json.status == 'OCCUPIED' %}
            Ocupado
          {% elif value_json.status == 'UNAVAILABLE' %}
            Estado no disponible
          {% elif value_json.status == 'AVAILABLE' %}
            Libre
          {% elif value_json.status == 'OFFLINE' %}
            No gestionado
          {% else %}
            Desconocido
          {%- endif %}

  - platform: dweet
    name: 'Cargador Sant Miquel'
    device: ximelib_32
    value_template: >-
          {%- if value_json.status == 'OCCUPIED_PARTIAL' %}
            Parcialmente ocupado
          {% elif value_json.status == 'OCCUPIED' %}
            Ocupado
          {% elif value_json.status == 'UNAVAILABLE' %}
            Estado no disponible
          {% elif value_json.status == 'AVAILABLE' %}
            Libre
          {% elif value_json.status == 'OFFLINE' %}
            No gestionado
          {% else %}
            Desconocido
          {%- endif %}

  - platform: dweet
    name: 'Cargador Palmanyola'
    device: ximelib_672
    value_template: >-
          {%- if value_json.status == 'OCCUPIED_PARTIAL' %}
            Parcialmente ocupado
          {% elif value_json.status == 'OCCUPIED' %}
            Ocupado
          {% elif value_json.status == 'UNAVAILABLE' %}
            Estado no disponible
          {% elif value_json.status == 'AVAILABLE' %}
            Libre
          {% elif value_json.status == 'OFFLINE' %}
            No gestionado
          {% else %}
            Desconocido
          {%- endif %}

  - platform: template
    sensors:
      # Charger today energy charged
      car_ioniq_state_today_energy_charged:
        value_template: >- 
          {% if state_attr('switch.car_ioniq_charger', 'today_energy_kwh') is not none %}
            {{state_attr('switch.car_ioniq_charger', 'today_energy_kwh')}}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: kWh
      # Current power used by Ioniq charger
      car_ioniq_charger_current_power:
        value_template: "{{state_attr('switch.car_ioniq_charger','current_power_w')|int}}"
        unit_of_measurement: W
      # Ioniq State last update
      car_ioniq_state_last_update:
        friendly_name: 'Última actualización'
        value_template: '{{((state_attr("binary_sensor.car_ioniq_state_sensor", "timestamp")|int)/1000)|round(0)|timestamp_custom("%d/%m/%Y %H:%M:%S")}}'
      # Ioniq State Of Charge display
      car_ioniq_state_soc_display:
        friendly_name: 'Batería mostrada'
        device_class: 'battery'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "soc_display")}}'
        unit_of_measurement: '%'
      # Ioniq State Of Health
      car_ioniq_state_battery_health:
        friendly_name: 'Salud batería'
        device_class: 'battery'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "soh")}}'
        unit_of_measurement: '%'
      # Ioniq State Of Charge BMS
      car_ioniq_state_soc_bms:
        friendly_name: 'Batería BMS'
        device_class: 'battery'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "soc_bms")}}'
        unit_of_measurement: '%'
      # Ioniq odometer
      car_ioniq_state_odometer:
        friendly_name: 'Odómetro'
        icon_template: 'mdi:counter'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "odometer")}}'
        unit_of_measurement: 'Km'
      # Ioniq distance traveled since codes cleared
      car_ioniq_state_distance_since_cc:
        friendly_name: 'Distancia cc'
        icon_template: 'mdi:counter'
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "distance_since_cc")}}'
        unit_of_measurement: 'Km'
      # Ioniq Cumulative Energy Discharged
      car_ioniq_state_ced:
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "ced")}}'
        unit_of_measurement: 'kWh'
      # Ioniq Cumulative Energy Charged
      car_ioniq_state_cec:
        value_template: '{{state_attr("binary_sensor.car_ioniq_state_sensor", "cec")}}'
        unit_of_measurement: 'kWh'
######################### Daily state data #########################
      # Ioniq daily State Of Charge display
      car_ioniq_state_daily_soc_display:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "soc_display")}}'
        unit_of_measurement: '%'
      # Ioniq daily State Of Health
      car_ioniq_state_daily_battery_health:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "soh")}}'
        unit_of_measurement: '%'
      # Ioniq daily State Of Charge BMS
      car_ioniq_state_daily_soc_bms:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "soc_bms")}}'
        unit_of_measurement: '%'
      # Ioniq daily odometer
      car_ioniq_state_daily_odometer:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "odometer")}}'
        unit_of_measurement: 'Km'
      # Ioniq daily distance traveled since codes cleared
      car_ioniq_state_daily_distance_since_cc:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "distance_since_cc")}}'
        unit_of_measurement: 'Km'
      # Ioniq daily Cumulative Energy Discharged
      car_ioniq_state_daily_ced:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "ced")}}'
        unit_of_measurement: 'kWh'
      # Ioniq daily Cumulative Energy Charged
      car_ioniq_state_daily_cec:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "cec")}}'
        unit_of_measurement: 'kWh'
      # Ioniq daily energy charged
      car_ioniq_state_daily_energy_charged:
        value_template: '{{state_attr("sensor.car_ioniq_state_daily", "charged_energy_kwh")}}'
        unit_of_measurement: 'kWh'
######################### Daily state data #########################
      # Ioniq Average energy consumption without taking into account regeneration
      car_ioniq_state_energy_consumption:
        friendly_name: 'Consumo medio'
        icon_template: 'mdi:car-electric'
        value_template: '{{ ((states.sensor.car_ioniq_state_ced.state | float / states.sensor.car_ioniq_state_odometer.state | float) * 100) | round(1)}}'
        unit_of_measurement: 'kWh/100Km'
        entity_id:
          - sensor.car_ioniq_state_ced
          - sensor.car_ioniq_state_odometer
      # Ioniq Previous latitude
      car_ioniq_location_previous_latitude:
        value_template: '{{state_attr("binary_sensor.car_ioniq_location_sensor", "platitude")}}'
        entity_id: 
          - binary_sensor.car_ioniq_location_sensor
      # Ioniq Previous longitude
      car_ioniq_location_previous_longitude:
        value_template: '{{state_attr("binary_sensor.car_ioniq_location_sensor", "plongitude")}}'
        entity_id: 
          - binary_sensor.car_ioniq_location_sensor
      # Ioniq Distance travelled between updates
      car_ioniq_location_distance_travelled_between_updates:
        unit_of_measurement: 'm'
        friendly_name: 'Dist. entre actualizaciones'
        value_template: '{% if states.device_tracker.car_ioniq.attributes.latitude %} {{ (distance(states("sensor.car_ioniq_location_previous_latitude"), states("sensor.car_ioniq_location_previous_longitude"), states.device_tracker.car_ioniq.attributes.latitude, states.device_tracker.car_ioniq.attributes.longitude) * 1000) | round (2) }} {% else %} -1 {% endif %}'
        icon_template: 'mdi:tape-measure'
        entity_id: 
          - device_tracker.car_ioniq
          - sensor.car_ioniq_location_previous_latitude
          - sensor.car_ioniq_location_previous_longitude
      # Ioniq Previous longitude
      car_ioniq_location_last_update:
        value_template: '{{state_attr("binary_sensor.car_ioniq_location_sensor", "last_update")|timestamp_custom("%d/%m/%Y %H:%M:%S")}}'
        entity_id: 
          - binary_sensor.car_ioniq_location_sensor
      # Ioniq GPS accuracy
      car_ioniq_location_gps_accuracy:
        unit_of_measurement: 'm'
        friendly_name: 'Precisión GPS'
        value_template: '{{state_attr("device_tracker.car_ioniq", "gps_accuracy")}}'
        icon_template: 'mdi:map-marker-radius'
        entity_id: 
          - device_tracker.car_ioniq
      car_ioniq_charge_state:
        value_template: >-
          {%- if states('sensor.car_ioniq_charger_current_power')|float > 1000.0 or is_state_attr('binary_sensor.car_ioniq_state_sensor', 'charging', 1) %}
             Cargando
          {%- elif is_state('switch.car_ioniq_charger', 'off') %}
            Apagado
          {% else %}
            Listo
          {%- endif %}
        entity_id: 
          - switch.car_ioniq_charger
          - binary_sensor.car_ioniq_charger_current_power
          - binary_sensor.car_ioniq_state_sensor

  # Google travel time to work
  - platform: google_travel_time
    name: 'car_a_la_oficina'
    api_key: !secret google_api_key
    origin: device_tracker.car_ioniq
    destination: zone.oficina
    options:
      language: es
      departure_time: now
      traffic_model: pessimistic
  
  # Google travel time to school
  - platform: google_travel_time
    name: 'car_al_colegio'
    api_key: !secret google_api_key
    origin: device_tracker.car_ioniq
    destination: zone.colegio
    options:
      language: es
      departure_time: now
      traffic_model: pessimistic

utility_meter:
  car_ioniq_charger_daily:
    source: sensor.car_ioniq_charger_spent
    cycle: daily
    tariffs:
      - Pico
      - Valle
#      - Super valle
  car_ioniq_charger_monthly:
    source: sensor.car_ioniq_charger_spent
    cycle: monthly
    tariffs:
      - Pico
      - Valle
#      - Super valle
  car_ioniq_charger_yearly:
    source: sensor.car_ioniq_charger_spent
    cycle: yearly
    tariffs:
      - Pico
      - Valle
#      - Super valle

camera:
  - platform: generic
    name: car_ioniq
    still_image_url: !secret camera_ioniq_still_image_url
    limit_refetch_to_url_change: true

zone:
  - name: Cargador Conquistador
    latitude: 39.56874
    longitude: 2.646939
    radius: 500
    icon: mdi:ev-station
  - name: Cargador Sant Miquel
    latitude: 39.576805
    longitude: 2.65234
    radius: 500
    icon: mdi:ev-station
  - name: Cargador Aragón
    latitude: 39.57309
    longitude: 2.657374
    radius: 500
    icon: mdi:ev-station
  - name: Cargador Palmanyola
    latitude: 39.6623
    longitude: 2.6723
    radius: 500
    icon: mdi:ev-station
