homeassistant:
  customize:
    sensor.efergy_2577:
      friendly_name: 'Consumo instantáneo'
      icon: 'mdi:speedometer'
    sensor.energy_ups_status:
      friendly_name: 'SAI'
      icon: 'mdi:power-socket-eu'
    sensor.nut_ups_manufacturer:
      friendly_name: 'Marca'
    sensor.nut_ups_model:
      friendly_name: 'Modelo'
    sensor.nut_ups_battery_charge:
      friendly_name: 'Carga'
    sensor.nut_ups_battery_runtime:
      friendly_name: 'Tiempo restante'
    sensor.energy_home_daily_pico:
      friendly_name: 'Consumo diario (pico)'
    sensor.energy_home_daily_valle:
      friendly_name: 'Consumo diario (valle)'
    sensor.energy_home_daily_super_valle:
      friendly_name: 'Consumo diario (super valle)'
    sensor.energy_home_monthly_pico:
      friendly_name: 'Consumo mensual (pico)'
    sensor.energy_home_monthly_valle:
      friendly_name: 'Consumo mensual (valle)'
    sensor.energy_home_monthly_super_valle:
      friendly_name: 'Consumo mensual (super valle)'
    ###################################
    # Binary Sensors
    ###################################
    binary_sensor.energy_ups_status_bs:
      friendly_name: 'Suministro eléctrico'
    ###################################
    # Switches
    ###################################
    switch.energy_ups_beeper:
      friendly_name: 'Pitido'
      icon: mdi:music-note

    utility_meter.energy_home_daily:
      friendly_name: 'Tarifa'

recorder:
  include:
    entities:
      - sensor.efergy_2577
      - sensor.energy_ups_status
      - binary_sensor.energy_ups_status_bs

#  exclude:
#    domains:
#      - utility_meter
#    entities:
#      - sensor.nut_ups_manufacturer
#      - sensor.nut_ups_model
#      - sensor.nut_ups_status_data
#      - sensor.nut_ups_beeper_status
#      - sensor.nut_ups_battery_runtime
#      - sensor.nut_ups_battery_charge
#      
#      - sensor.per_device_usage

sensor:
  - platform: efergy
    app_token: !secret efergy_app_token
    utc_offset: 2
    monitored_variables:
      - type: current_values

  - platform: integration 
    source: sensor.efergy_2577
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      energy_ups_status:
        value_template: >-
          {%- if is_state('sensor.nut_ups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.nut_ups_status_data', 'OL CHRG') %}
            Cargando
          {% elif is_state('sensor.nut_ups_status_data', 'OB DISCHRG') %}
            Batería
          {% elif is_state('sensor.nut_ups_status_data', 'LB DISCHRG') %}
            Batería baja
          {% elif is_state('sensor.nut_ups_status_data', 'RB') %}
            Reemplazar batería
          {% else %}
            Desconocido
          {%- endif %}
  
  - platform: nut
    resources:
      - ups.status
      - ups.status.display
      - battery.charge
      - battery.runtime
      - ups.beeper.status
      - ups.mfr
      - ups.model

binary_sensor:
  - platform: template
    sensors:
      energy_ups_status_bs:
        device_class: plug
        entity_id: sensor.nut_ups_status_data
        value_template: "{{ is_state('sensor.nut_ups_status_data', 'OL') or is_state('sensor.nut_ups_status_data', 'OL CHRG') }}"
        delay_off:
          seconds: 30

utility_meter:
  energy_home_daily:
    source: sensor.energy_spent
    cycle: daily 
    tariffs:
      - Pico
      - Valle
      - Super valle
  energy_home_monthly:
    source: sensor.energy_spent
    cycle: monthly
    tariffs:
      - Pico
      - Valle
      - Super valle
