homeassistant:
  customize:
    sensor.efergy_2577:
      friendly_name: 'Consumo instantáneo'
      icon: 'mdi:speedometer'
    sensor.energy_ups_status:
      friendly_name: 'SAI'
      icon: 'mdi:power-socket-eu'
    sensor.nut_ups_manufacturer:
      friendly_name: 'Marca'
    sensor.nut_ups_model:
      friendly_name: 'Modelo'
    sensor.nut_ups_battery_charge:
      friendly_name: 'Carga'
    sensor.nut_ups_battery_runtime:
      friendly_name: 'Tiempo restante'
    sensor.energy_home_daily_pico:
      friendly_name: 'Consumo diario (pico)'
    sensor.energy_home_daily_valle:
      friendly_name: 'Consumo diario (valle)'
    sensor.energy_home_daily_super_valle:
      friendly_name: 'Consumo diario (super valle)'
    sensor.energy_home_monthly_pico:
      friendly_name: 'Consumo mensual (pico)'
    sensor.energy_home_monthly_valle:
      friendly_name: 'Consumo mensual (valle)'
    sensor.energy_home_monthly_super_valle:
      friendly_name: 'Consumo mensual (super valle)'
    sensor.energy_car_charger_yearly_pico:
      friendly_name: 'Consumo anual (pico)'
      icon: 'mdi:trending-up'
    sensor.energy_car_charger_yearly_valle:
      friendly_name: 'Consumo anual (valle)'
      icon: 'mdi:trending-down'
      unit_of_measurement: kWh
    sensor.energy_car_charger_yearly_super_valle:
      friendly_name: 'Consumo anual (super valle)'
      icon: 'mdi:trending-down'
      unit_of_measurement: kWh
    sensor.energy_car_charger_monthly_pico:
      friendly_name: 'Consumo mensual (pico)'
      icon: 'mdi:trending-up'
    sensor.energy_car_charger_monthly_valle:
      friendly_name: 'Consumo mensual (valle)'
      icon: 'mdi:trending-down'
    sensor.energy_car_charger_monthly_super_valle:
      friendly_name: 'Consumo mensual (super valle)'
      icon: 'mdi:trending-down'
    sensor.energy_car_charger_daily_pico:
      friendly_name: 'Consumo diario (pico)'
      icon: 'mdi:trending-up'
    sensor.energy_car_charger_daily_valle:
      friendly_name: 'Consumo diario (valle)'
      icon: 'mdi:trending-down'
    sensor.energy_car_charger_daily_super_valle:
      friendly_name: 'Consumo diario (super valle)'
      icon: 'mdi:trending-down'
    sensor.energy_car_charger_powerused:
      friendly_name: 'Potencia carga'
      icon: 'mdi:speedometer'
    sensor.energy_car_charge_state:
      friendly_name: 'Estado carga'
      icon: 'mdi:flash-circle'

    ###################################
    # Binary Sensors
    ###################################
    binary_sensor.energy_ups_status_bs:
      friendly_name: 'Suministro eléctrico'
    ###################################
    # Switches
    ###################################
    switch.energy_ups_beeper:
      friendly_name: 'Pitido'
      icon: mdi:music-note
    switch.energy_car_charger:
      friendly_name: 'Cargador'

    utility_meter.energy_home_daily:
      friendly_name: 'Tarifa'

recorder:
  exclude:
    domains:
      - utility_meter
    entities:
      - sensor.nut_ups_manufacturer
      - sensor.nut_ups_model
      - sensor.nut_ups_status_data
      - sensor.nut_ups_beeper_status
      - sensor.nut_ups_battery_runtime
      - sensor.nut_ups_battery_charge
      - sensor.energy_car_charge_state

group:
  Energía:
    entities:
      - utility_meter.energy_home_daily
      - binary_sensor.energy_ups_status_bs
      - sensor.efergy_2577
      - sensor.energy_home_daily_pico
      - sensor.energy_home_daily_valle
      - sensor.energy_home_daily_super_valle
      - sensor.energy_home_monthly_pico
      - sensor.energy_home_monthly_valle
      - sensor.energy_home_monthly_super_valle
      - sensor.energy_ups_status
  SAI:
    entities:
      - sensor.energy_ups_status
      - sensor.nut_ups_battery_charge
      - sensor.nut_ups_battery_runtime
      - switch.energy_ups_beeper

sensor:
  - platform: efergy
    app_token: !secret efergy_app_token
    utc_offset: 2
    monitored_variables:
      - type: current_values

  - platform: integration 
    source: sensor.efergy_2577
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: integration 
    source: sensor.energy_car_charger_powerused
    name: energy_spent_insight
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      energy_car_charger_powerused:
        value_template: "{{state_attr('switch.energy_car_charger','current_power_w')|int}}"
        unit_of_measurement: W
      energy_car_charge_state:
        value_template: >-
          {%- if is_state('switch.energy_car_charger', 'off') %}
            Apagado
          {% elif is_state('binary_sensor.energy_car_charging', 'off') %}
            Listo
          {% else %}
            Cargando
          {%- endif %}
      energy_ups_status:
        value_template: >-
          {%- if is_state('sensor.nut_ups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.nut_ups_status_data', 'OL CHRG') %}
            Cargando
          {% elif is_state('sensor.nut_ups_status_data', 'OB DISCHRG') %}
            Batería
          {% elif is_state('sensor.nut_ups_status_data', 'LB DISCHRG') %}
            Batería baja
          {% elif is_state('sensor.nut_ups_status_data', 'RB') %}
            Reemplazar batería
          {% else %}
            Desconocido
          {%- endif %}
  
  - platform: nut
    resources:
      - ups.status
      - ups.status.display
      - battery.charge
      - battery.runtime
      - ups.beeper.status
      - ups.mfr
      - ups.model

binary_sensor:
  - platform: template
    sensors:
      energy_ups_status_bs:
        device_class: plug
        entity_id: sensor.nut_ups_status_data
        value_template: "{{ is_state('sensor.nut_ups_status_data', 'OL') or is_state('sensor.nut_ups_status_data', 'OL CHRG') }}"
        delay_off:
          seconds: 30
      energy_car_charging:
        friendly_name: "Cargando"
        device_class: plug
        value_template: "{{ states('sensor.energy_car_charger_powerused')|float > 1000.0 }}"
switch:
  - platform: template
    switches:
      energy_ups_beeper:
        value_template: "{{ is_state('sensor.nut_ups_beeper_status', 'enabled') }}"
        turn_on:
          service: shell_command.nut_ups_enable_beeper
        turn_off:
          service: shell_command.nut_ups_disable_beeper

utility_meter:
  energy_home_daily:
    source: sensor.energy_spent
    cycle: daily 
    tariffs:
      - Pico
      - Valle
      - Super valle
  energy_home_monthly:
    source: sensor.energy_spent
    cycle: monthly
    tariffs:
      - Pico
      - Valle
      - Super valle
  energy_car_charger_daily:
    source: sensor.energy_spent_insight
    cycle: daily
    tariffs:
      - Pico
      - Valle
      - Super valle
  energy_car_charger_monthly:
    source: sensor.energy_spent_insight
    cycle: monthly
    tariffs:
      - Pico
      - Valle
      - Super valle
  energy_car_charger_yearly:
    source: sensor.energy_spent_insight
    cycle: yearly
    tariffs:
      - Pico
      - Valle
      - Super valle

automation:
  #############################################################
  # Power automations
  #############################################################
  
  # Notify when a power cut longer than 1 minute detected
  - alias: '[Energy] Notify power cut'
    trigger:
      platform: state
      entity_id: binary_sensor.energy_ups_status_bs
      to: 'off'
      for:
        minutes: 1
    action:
      - service: notify.telegram
        data:
          message: 'Corte en el suministro eléctrico detectado'
  
  # Restart UPS driver controller when a power cut is detected.
  # I've added this automation because from time to time the controller stops working until it's restarted.
  - alias: '[Energy] Restart UPS Driver Controller'
    trigger:
      platform: state
      entity_id: binary_sensor.energy_ups_status_bs
      to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.ha_runtime_in_minutes
        above: 2
    action:
      - service: notify.telegram
        data:
          message: 'Controlador SAI reiniciado'
      - service: shell_command.restart_ups_driver_controller
  
  # Notify when the power is back normal
  - alias: '[Energy] Notify power ok'
    trigger:
      platform: state
      entity_id: binary_sensor.energy_ups_status_bs
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.ha_runtime_in_minutes
        above: 2
    action:
      service: notify.telegram
      data:
        message: 'Suministro eléctrico reestablecido'
  
  # Notify when the UPS battery has to be replaced
  - alias: '[Energy] Notify ups battery replacement'
    trigger:
      platform: state
      entity_id: sensor.energy_ups_status
      to: 'Reemplazar batería'
    action:
      service: notify.telegram
      data:
        message: 'Batería del SAI agotándose, reemplazar'
  
  - alias: '[Energy] Set correct energy tariff on start'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: utility_meter.select_tariff
        data_template:
          entity_id: utility_meter.energy_home_daily 
          tariff: >-
            {%- if as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=1).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=7).replace(minute=0).replace(second=0)) %}
              Super valle
            {%- elif as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=13).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=23).replace(minute=0).replace(second=0))%}
              Pico
            {%- else %}
              Valle
            {%- endif %}
      - service: utility_meter.select_tariff
        data_template:
          entity_id: utility_meter.energy_home_monthly
          tariff: >-
            {%- if as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=1).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=7).replace(minute=0).replace(second=0)) %}
              Super valle
            {%- elif as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=13).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=23).replace(minute=0).replace(second=0))%}
              Pico
            {%- else %}
              Valle
            {%- endif %}
      - service: utility_meter.select_tariff
        data_template:
          entity_id: utility_meter.energy_car_charger_daily
          tariff: >-
            {%- if as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=1).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=7).replace(minute=0).replace(second=0)) %}
              Super valle
            {%- elif as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=13).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=23).replace(minute=0).replace(second=0))%}
              Pico
            {%- else %}
              Valle
            {%- endif %}
      - service: utility_meter.select_tariff
        data_template:
          entity_id: utility_meter.energy_car_charger_monthly
          tariff: >-
            {%- if as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=1).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=7).replace(minute=0).replace(second=0)) %}
              Super valle
            {%- elif as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=13).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=23).replace(minute=0).replace(second=0))%}
              Pico
            {%- else %}
              Valle
            {%- endif %}
      - service: utility_meter.select_tariff
        data_template:
          entity_id: utility_meter.energy_car_charger_yearly
          tariff: >-
            {%- if as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=1).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=7).replace(minute=0).replace(second=0)) %}
              Super valle
            {%- elif as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) >= as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=13).replace(minute=0).replace(second=0)) and as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M")) < as_timestamp(strptime(states.sensor.date_time.state, "%Y-%m-%d, %H:%M").replace(hour=23).replace(minute=0).replace(second=0))%}
              Pico
            {%- else %}
              Valle
            {%- endif %}

  - alias: '[Energy] Energy Pico time'
    trigger:
      platform: time
      at: '13:00:00'
    action:
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_home_daily 
          tariff: 'Pico'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_home_monthly
          tariff: 'Pico'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_daily
          tariff: 'Pico'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_monthly
          tariff: 'Pico'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_yearly
          tariff: 'Pico'

  - alias: '[Energy] Energy Valle time'
    trigger:
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '07:00:00'
    action:
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_home_daily 
          tariff: 'Valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_home_monthly
          tariff: 'Valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_daily
          tariff: 'Valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_monthly
          tariff: 'Valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_yearly
          tariff: 'Valle'

  - alias: '[Energy] Energy Super valle time'
    trigger:
      platform: time
      at: '01:00:00'
    action:
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_home_daily 
          tariff: 'Super valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_home_monthly
          tariff: 'Super valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_daily
          tariff: 'Super valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_monthly
          tariff: 'Super valle'
      - service: utility_meter.select_tariff
        data:
          entity_id: utility_meter.energy_car_charger_yearly
          tariff: 'Super valle'

#   - alias: 'Turn on WeMo Insight in Valle time'
#     trigger:
#       platform: state
#       entity_id: utility_meter.energy_car_charger_yearly
#       from: 'Pico'
#       to: 'Valle'
#     action:
#       - service: switch.turn_on
#         entity_id: switch.energy_car_charger

  - alias: '[Energy] Turn off WeMo Insight 5 mins after Super valle time finishes'
    trigger:
      platform: state
      entity_id: utility_meter.energy_car_charger_yearly
      from: 'Super valle'
    action:
      - delay:
          minutes: 5
      - service: switch.turn_off
        entity_id: switch.energy_car_charger
