recorder:
  include:
    entities:
      - sensor.efergy_2577
      - sensor.energy_ups_status
      - binary_sensor.energy_ups_status_bs

logbook:
  exclude:
    entities:
      - sensor.efergy_2577

sensor:
  - platform: efergy
    app_token: !secret efergy_app_token
    utc_offset: 2
    monitored_variables:
      - type: current_values

  - platform: integration 
    source: sensor.efergy_2577
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      energy_ups_status:
        value_template: >-
          {%- if is_state('sensor.nut_ups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.nut_ups_status_data', 'OL LB') %}
            Normal Batería baja
          {% elif is_state('sensor.nut_ups_status_data', 'OL CHRG') %}
            Cargando
          {% elif is_state('sensor.nut_ups_status_data', 'OB DISCHRG') %}
            Batería
          {% elif is_state('sensor.nut_ups_status_data', 'LB DISCHRG') %}
            Batería baja
          {% elif is_state('sensor.nut_ups_status_data', 'RB') %}
            Reemplazar batería
          {% else %}
            Desconocido
          {%- endif %}

#  - platform: nut
#    host: a0d7b954-nut
#    resources:
#      - ups.status
#      - ups.status.display
#      - battery.charge
#      - battery.runtime
#      - ups.beeper.status
#      - ups.mfr
#      - ups.model

  - platform: mqtt
    state_topic: 'home/sensor/energy/tariff'
    name: energy_tariff

binary_sensor:
  - platform: template
    sensors:
      energy_ups_status_bs:
        device_class: plug
        entity_id: sensor.nut_ups_status_data
        value_template: "{{ is_state('sensor.nut_ups_status_data', 'OL') or is_state('sensor.nut_ups_status_data', 'OL CHRG') or is_state('sensor.nut_ups_status_data', 'OL LB')}}"
        delay_off:
          seconds: 30

utility_meter:
  energy_home_daily:
    source: sensor.energy_spent
    cycle: daily 
    tariffs:
      - Pico
      - Valle
#      - Super valle
  energy_home_monthly:
    source: sensor.energy_spent
    cycle: monthly
    tariffs:
      - Pico
      - Valle
#      - Super valle
