homeassistant:
  customize:
    sensor.outside_fence:
      friendly_name: 'Estado barrera'

recorder:
  include:
    entities:
      - sensor.outside_fence
#  exclude:
#    entities:
#      - sensor.outside_fence_sensor_state
#      - switch.barrera

sensor:
  - platform: template
    sensors:
      # Wemo Maker sensor state (off: fence opened, on: fence closed)
      outside_fence_sensor_state:
        value_template: '{{state_attr("switch.barrera", "sensor_state")}}'

  - platform: mqtt
    name: 'outside_fence'
    state_topic: 'home/sensor/fence/state'
    icon: mdi:garage

cover:
  - platform: template
    covers:
      outside_fence:
        friendly_name: "Barrera"
        value_template: "{{ is_state_attr('switch.barrera', 'sensor_state', 'off') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.barrera
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.barrera
        icon_template: >-
          {%- if is_state("sensor.outside_fence", "Abierta") %}
            mdi:garage-open
          {%- elif is_state("sensor.outside_fence", "En movimiento") %}
            mdi:garage-alert
          {% else %}
            mdi:garage
          {% endif %}

cloud:
  google_actions:
    entity_config:
      cover.outside_fence:
        name: Puerta de entrada
        aliases:
          - Barrera
          - Puerta de entrada
        room: Jardín delantero
