homeassistant:
  customize:
    sensor.outside_fence_switch:
      friendly_name: 'Estado barrera'
      icon: 'mdi:gate'
    switch.barrera:
      friendly_name: 'Barrera'
      icon: mdi:gate

#recorder:
#  exclude:
#    entities:

group:
  Barrera:
    entities:
      - switch.barrera
      - sensor.outside_fence_switch

sensor:
  - platform: template
    sensors:
      # Know if the Wemo Maker sensor has been triggered (off: garage door opened, on: garage door closed)
      outside_fence_switch:
        friendly_name: 'Estado'
        value_template: >-
            {%- if is_state_attr("switch.barrera", "sensor_state", "off") %}
                Abierta
            {% else %}
                Cerrada
            {%- endif %}

switch:
  - platform: template
    switches:
      outside_fence:
        value_template: '{{ is_state_attr("switch.barrera", "sensor_state", "off") }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.barrera
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.barrera

google_assistant:
  entity_config:
    switch.outside_fence:
      name: Barrera
      expose: true
      room: Exterior

automation:
  - alias: 'When fence open notify every 10 minutes'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.outside_fence_switch
          state: 'Abierta'
        - condition: template
          value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.sensor.outside_fence_switch.last_changed))//60)%10 == 0 }}'
        - condition: template
          value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.sensor.outside_fence_switch.last_changed))//60) != 0 }}'
    action:
      - service: script.turn_on
        data:
          entity_id: script.speech_set_tts_volume_level
      - service: tts.google_say
        entity_id: media_player.homeassistant
        data_template:
          message: 'Barrera {{ states.sensor.outside_fence_switch.state }} durante más de {{ (as_timestamp(now()) - as_timestamp(states.sensor.outside_fence_switch.last_changed))|int//60 }} minutos'
          cache: false
      - service: telegram_bot.send_message
        data_template:
          message: 'Barrera {{ states.sensor.outside_fence_switch.state }} durante más de {{ (as_timestamp(now()) - as_timestamp(states.sensor.outside_fence_switch.last_changed))|int//60 }} minutos'
          target: 
            - !secret hokusphone_telegram_chat_id
            - !secret geniphone_telegram_chat_id
          inline_keyboard: 
            - 'Cerrar:/script.turn_on#script.fence_close'


script:
  fence_close:
    alias: 'Close fence if open'
    sequence:
      - service_template: >
          {%- if is_state("sensor.outside_fence_switch", "Abierta") -%}
            homeassistant.turn_on
          {%- endif -%}
  
        data:
          entity_id: switch.barrera
  
  fence_open_ga:
    alias: 'Open fence if closed'
    sequence:
      - service_template: >
          {%- if is_state("sensor.outside_fence_switch", "Cerrada") -%}
            homeassistant.turn_on
          {%- endif -%}
  
        data:
          entity_id: switch.barrera
      - service: telegram_bot.send_message
        data_template:
          message: 'Google Assistant ha abierto la barrera'
          target: !secret hokusphone_telegram_chat_id
          inline_keyboard: 
            - 'Cerrar:/script.turn_on#script.fence_close'
