homeassistant:
  customize:
    switch.outside_fence:
      friendly_name: 'Barrera'
      icon: mdi:gate
    sensor.outside_fence:
      friendly_name: 'Estado barrera'

recorder:
  exclude:
    entities:
      - sensor.outside_fence_sensor_state

group:
  Barrera:
    entities:
      - switch.outside_fence
      - sensor.outside_fence

sensor:
  - platform: template
    sensors:
      # Wemo Maker sensor state (off: fence opened, on: fence closed)
      outside_fence_sensor_state:
        value_template: '{{state_attr("switch.barrera", "sensor_state")}}'

  - platform: mqtt
    name: 'outside_fence'
    state_topic: 'home/fence/state'
    icon: mdi:gate

switch:
  - platform: template
    switches:
      outside_fence:
        value_template: '{{ is_state_attr("switch.barrera", "sensor_state", "off") }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.barrera
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.barrera

cloud:
  google_actions:
    filter:
      include_entities:
        - switch.outside_fence
    entity_config:
      switch.outside_fence:
        name: Puerta de entrada
        aliases:
          - Barrera
          - Puerta de entrada
        room: Jardín delantero

#google_assistant:
#  entity_config:
#    switch.outside_fence:
#      name: Barrera
#      expose: true
#      room: Exterior

automation:
    # Fence state. Can be moving (En movimiento), open (Abierta) or closed (Cerrada).
    # Fence needs around 20 seconds to fully open/close
  - alias: 'Publish to mqtt fence status'
    trigger:
      platform: state
      entity_id: switch.barrera
      to: 'off'
    action:
      - service: mqtt.publish
        data:
          topic: home/fence/state
          payload_template: >-
            {%- if is_state("sensor.outside_fence_sensor_state", "off") and not is_state("sensor.outside_fence", "En movimiento") %}
              En movimiento
            {%- else %}
              {%- if is_state("sensor.outside_fence_sensor_state", "off") %}
                Abierta
              {% else %}
                Cerrada
              {%- endif %}
            {%- endif %}
          qos: 0
          retain: true
      - delay:
          seconds: 20
      - service: mqtt.publish
        data:
          topic: home/fence/state
          payload_template: >-
            {%- if is_state("sensor.outside_fence_sensor_state", "off") %}
              Abierta
            {% else %}
              Cerrada
            {%- endif %}

  - alias: 'Publish to mqtt fence closed (Cerrada) status'
    trigger:
      platform: state
      entity_id: sensor.outside_fence_sensor_state
      to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: home/fence/state
          payload: Cerrada
          qos: 0
          retain: true

  - alias: 'When fence open notify every 10 minutes'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.outside_fence
          state: 'Abierta'
        - condition: template
          value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.sensor.outside_fence.last_changed))//60)%10 == 0 }}'
        - condition: template
          value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.sensor.outside_fence.last_changed))//60) != 0 }}'
    action:
      - service: tts.google_say
        entity_id: media_player.recibidor
        data_template:
          message: 'Barrera {{ states.sensor.outside_fence.state }} durante más de {{ (as_timestamp(now()) - as_timestamp(states.sensor.outside_fence.last_changed))|int//60 }} minutos'
          cache: false
      - service: telegram_bot.send_message
        data_template:
          message: 'Barrera {{ states.sensor.outside_fence.state }} durante más de {{ (as_timestamp(now()) - as_timestamp(states.sensor.outside_fence.last_changed))|int//60 }} minutos'
          target: 
            - !secret hokusphone_telegram_chat_id
            - !secret geniphone_telegram_chat_id
          inline_keyboard: 
            - 'Cerrar:/switch.turn_on#switch.outside_fence'