homeassistant:
  customize:
    sensor.escalera_switch_energy:
      icon: 'mdi:speedometer'
      friendly_name: 'Consumo luz escalera'
    sensor.escalera_switch_power:
      icon: 'mdi:power-plug'
      friendly_name: 'Potencia luz escalera'
    sensor.suite_switch_energy:
      icon: 'mdi:speedometer'
      friendly_name: 'Consumo luz suite'
    sensor.suite_switch_power:
      icon: 'mdi:power-plug'
      friendly_name: 'Potencia luz suite'
    light.escalera_light:
      friendly_name: 'Escalera'
      icon: mdi:ceiling-light
    light.suite_light:
      friendly_name: 'Suite'
      icon: mdi:ceiling-light
    light.salon_light:
      friendly_name: 'Salón'
      icon: mdi:ceiling-light
    light.comedor_light:
      friendly_name: 'Comedor'
      icon: mdi:ceiling-light
    light.entrance_hall_lamp_light:
      friendly_name: 'Lámpara recibidor'
      icon: mdi:lamp
#    input_number.outside_ligths_brightness:
#      icon: mdi:brightness-6
    script.turn_off_lights_exterior:
      hidden: true

recorder:
  include:
    domains:
      - light
#  exclude:
#    entities:
#      - sensor.suite_switch_exporting
#      - sensor.escalera_switch_alarm_level
#      - sensor.escalera_switch_alarm_type
#      - sensor.escalera_switch_exporting
#      - sensor.escalera_switch_heat
#      - sensor.escalera_switch_power_management
#      - sensor.escalera_switch_sourcenodeid
#      - switch.entrance_hall_lamp_switch
#      - switch.escalera_switch
#      - switch.suite_switch

light:
  - platform: group
    name: Luces exteriores
    entities:
      - light.barrera_derecha
      - light.barrera_izquierda
      - light.puerta_coladuria

  - platform: switch
    name: salon_light
    entity_id: switch.salon_switch

  - platform: switch
    name: comedor_light
    entity_id: switch.comedor_switch

  - platform: switch
    name: suite_light
    entity_id: switch.suite_switch

  - platform: switch
    name: escalera_light
    entity_id: switch.escalera_switch

  - platform: switch
    name: entrance_hall_lamp_light
    entity_id: switch.entrance_hall_lamp_switch

  - platform: group
    name: Luces interiores
    entities:
      - light.suite_light
      - light.escalera_light
      - light.entrance_hall_lamp_light
      - light.comedor_light
      - light.salon_light
