homeassistant:
  customize:
    sensor.escalera_switch_energy:
      icon: 'mdi:speedometer'
      friendly_name: 'Consumo luz escalera'
    sensor.escalera_switch_power:
      icon: 'mdi:power-plug'
      friendly_name: 'Potencia luz escalera'
    sensor.suite_switch_energy:
      icon: 'mdi:speedometer'
      friendly_name: 'Consumo luz suite'
    sensor.suite_switch_power:
      icon: 'mdi:power-plug'
      friendly_name: 'Potencia luz suite'
    light.escalera_light:
      friendly_name: 'Escalera'
      icon: mdi:ceiling-light
    light.suite_light:
      friendly_name: 'Suite'
      icon: mdi:ceiling-light
    light.entrance_hall_lamp_light:
      friendly_name: 'Lámpara recibidor'
      icon: mdi:lamp
#    input_number.outside_ligths_brightness:
#      icon: mdi:brightness-6
    script.turn_off_lights_exterior:
      hidden: true

recorder:
  exclude:
    entities:
      - sensor.suite_switch_exporting
      - sensor.escalera_switch_alarm_level
      - sensor.escalera_switch_alarm_type
      - sensor.escalera_switch_exporting
      - sensor.escalera_switch_heat
      - sensor.escalera_switch_power_management
      - sensor.escalera_switch_sourcenodeid

light:
  - platform: group
    name: Luces exteriores
    entities:
      - light.barrera_derecha
      - light.barrera_izquierda
      - light.puerta_coladuria

  - platform: switch
    name: suite_light
    entity_id: switch.suite_switch

  - platform: switch
    name: escalera_light
    entity_id: switch.escalera_switch

  - platform: switch
    name: entrance_hall_lamp_light
    entity_id: switch.entrance_hall_lamp_switch

  - platform: group
    name: Luces interiores
    entities:
      - light.suite
      - light.escalera
      - light.lampara_recibidor

#input_number:
#  outside_ligths_brightness:
#    name: Brillo
#    initial: 75
#    min: 5
#    max: 100
#    step: 5

#automation:
#  - alias: '[Lights - Outside] When turn on outside lights, adjust brightness to 75%'
#    trigger:
#      platform: state
#      entity_id: light.luces_exteriores
#      to: 'on'
#    action:
#      - service: light.turn_on
#        data_template:
#          entity_id: light.luces_exteriores
#          brightness: '{{ (75 * 255) // 100 }}'
#  
#  # Adjust luces exteriores brightness
##  - alias: '[Lights] Luces exteriores - Adjust Brightness'
##    trigger:
##      platform: state
##      entity_id: input_number.outside_ligths_brightness
##    condition:
##      condition: state
##      entity_id: light.luces_exteriores
##      state: 'on'
##    action:
##      - service: light.turn_on
##        data_template:
##          entity_id: light.luces_exteriores
##          brightness: '{{ ((trigger.to_state.state | int) * 255) // 100 }}'
#  
#  # Turn on outside lights at sunset (+15 minutes)
#  - alias: '[Lights - Outside] Turn on outside lights at sunset (+15 minutes)'
#    trigger:
#      platform: sun
#      event: 'sunset'
#      offset: '00:15:00'
#    action:
#      - service: light.turn_on
#        data_template:
#          entity_id: light.luces_exteriores
#          brightness: '{{ (75 * 255) // 100 }}'
#      - service: logbook.log
#        data:
#          name: 'Luces exteriores'
#          message: 'encendidas por la puesta de sol'
#          entity_id: light.luces_exteriores
#          domain: light
#  
#  - alias: '[Lights - Outside] Turn off outside lights at night (at 00:15)'
#    trigger:
#      platform: time
#      at: '00:15'
#    condition:
#      condition: state
#      entity_id: light.luces_exteriores
#      state: 'on'
#    action:
#      - service: light.turn_off
#        entity_id: light.luces_exteriores
#      - service: logbook.log
#        data:
#          name: 'Luces exteriores'
#          message: 'apagadas a las 00:15'
#          entity_id: light.luces_exteriores
#          domain: light
#  
#  - alias: '[Lights - Outside] When the outside lights have been turned on at late night (later than 00:15) and before sunrise, turn them off after 5 minutes'
#    trigger:
#      platform: state
#      entity_id: light.luces_exteriores
#      to: 'on'
#    condition:
#      - condition: time
#        after: '00:15'
#      - condition: sun
#        before: sunrise
#    action:
#      - delay:
#          minutes: 5
#      - service: light.turn_off
#        data:
#          entity_id: light.luces_exteriores
#      - service: logbook.log
#        data:
#          name: 'Luces exteriores'
#          message: 'apagadas más tarde de las 00:15'
#          entity_id: light.luces_exteriores
#          domain: light
#  
#  - alias: '[Lights - Outside] Turn off outside lights after 10 seconds when the sun is not set'
#    trigger:
#      platform: state
#      entity_id: light.luces_exteriores
#      to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: sun
#        before: sunset
#      - condition: sun
#        after: sunrise
#    action:
#      - delay:
#          seconds: 10
#      - service: light.turn_off
#        data:
#          entity_id: light.luces_exteriores
#      - service: logbook.log
#        data:
#          name: 'Luces exteriores'
#          message: 'apagadas porque es de dia'
#          entity_id: light.luces_exteriores
#          domain: light
#  
#  - alias: '[Lights - Outside] Turn on outside lights when fence is opened and the sun is set'
#    trigger:
#      platform: state
#      entity_id: sensor.outside_fence
#      from: 'Cerrada'
#      to: 'En movimiento'
#    condition:
#      condition: or
#      conditions:
#      - condition: sun
#        after: sunset
#      - condition: sun
#        before: sunrise
#    action:
#      - service: light.turn_on
#        data_template:
#          entity_id: light.luces_exteriores
#          brightness: '{{ (75 * 255) // 100 }}'
#      - service: logbook.log
#        data:
#          name: 'Luces exteriores'
#          message: 'encendidas porque se ha abierto la barrera y es de noche'
#          entity_id: light.luces_exteriores
#          domain: light
#  
#  - alias: '[Lights - Hall lamp] Turn on hall lamp when the sun is set and someone at home'
#    trigger:
#      platform: sun
#      event: sunset
#    condition:
#      condition: state
#      entity_id: group.unidad_familiar
#      state: 'home'
#    action:
#      - service: switch.turn_on
#        data:
#          entity_id: switch.entrance_hall_lamp_switch