homeassistant:
  customize:
    sensor.next_holiday_mode_start:
      icon: mdi:airplane-takeoff
    sensor.next_holiday_mode_end:
      icon: mdi:airplane-landing
    sensor.next_shift_event:
      icon: mdi:message
    sensor.next_shift_date:
      icon: mdi:calendar
    switch.holiday:
      friendly_name: 'Vacaciones'
      icon: mdi:airplane
    input_number.empty_home_activation_delay_minutes:
      icon: mdi:clock-end
    device_tracker.geniphone_wifi:
      source_type: router
    device_tracker.hokusphone_wifi:
      source_type: router
    device_tracker.guest:
      source_type: router
    person.jordi:
      entity_picture: 'https://s.gravatar.com/avatar/f5d192b4f4ffab4d9625f9b9e11d16b7?s=192'
    person.geni:
      entity_picture: '/local/person.geni.jpg'
    person.guest:
      entity_picture: '/local/person.guest.png'

recorder:
  include:
    domains:
      - person
    entities:
      - group.unidad_familiar

#  exclude:
#    entities:
#      - sensor.next_shift_event
#      - sensor.next_shift_date
#      - sensor.next_holiday_mode_start
#      - sensor.next_holiday_mode_end
#      - sensor.check_switch_holiday
#
#      - input_number.guest_mode_minutes

group:
  Unidad Familiar:
    entities:
      - person.jordi
      - person.geni
      - person.guest

input_boolean:
  guest_mode:
    name: Modo invitado
  #  initial: off
    icon: 'mdi:clock'

input_number:
  # Number of minutes to keep the guest mode on
  guest_mode_minutes:
    name: Minutos invitado
    initial: 180
    min: 0
    max: 240
    step: 5

device_tracker:
  - platform: mqtt
    devices:
      # Updated when hokusphone is connected to a WiFi
      hokusphone_wifi: phone/sensor/hokus/wifi
      # Updated when geniphone is connected to a WiFi
      geniphone_wifi: phone/sensor/geni/wifi

sensor:
  - platform: template
    sensors:
      next_holiday_mode_start:
        friendly_name: 'Inicio vacaciones'
        value_template: >-
             {%- if states.calendar.holiday_mode.attributes.start_time is not none %}
                 {{ as_timestamp(states.calendar.holiday_mode.attributes.start_time)|timestamp_custom("%d/%m/%Y %H:%M:%S") }}
             {% else %}
                 No previstas
             {%- endif %}
      next_holiday_mode_end:
        friendly_name: 'Fin vacaciones'
        value_template: >-
             {%- if states.calendar.holiday_mode.attributes.end_time is not none %}
                 {{ as_timestamp(states.calendar.holiday_mode.attributes.end_time)|timestamp_custom("%d/%m/%Y %H:%M:%S") }}
             {% else %}
                 No previstas
             {%- endif %}
      next_shift_event:
        friendly_name: 'Próx. turno'
        value_template: '{{ states.calendar.turnos_geni_everything.attributes.message }}'
      next_shift_date:
        friendly_name: 'Próx. turno'
        value_template: >-
            {%- if as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 0 %}
                Domingo, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 1 %}
                Lunes, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 2 %}
                Martes, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 3 %}
                Miércoles, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 4 %}
                Jueves, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 5 %}
                Viernes, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 6 %}
                Sábado, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {%- endif %}

switch:
  - platform: mqtt
    name: 'holiday'
    state_topic: 'home/switch/holiday/status'
    command_topic: 'home/switch/holiday/status'
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 0
    retain: true

cloud:
  google_actions:
    entity_config:
      script.presence_guest_mode_on:
        name: Persona autorizada
        aliases:
          - Persona autorizada
          - Modo invitado
        room: General
      script.presence_leave_home:
        name: Me voy
        aliases:
          - Me voy
        room: General

script:
  presence_empty_home:
    alias: 'Empty home'
    sequence:
      # Alarm arm away
      - service: script.turn_on
        data:
          entity_id: script.alarm_arm_away
      # Turn off hall lamp
      - service: switch.turn_off
        data:
          entity_id: switch.entrance_hall_lamp_switch
      # Turn off stair lights
      - service: switch.turn_off
        data:
          entity_id: switch.escalera_switch
      # Turn off suite light
      - service: switch.turn_off
        data:
          entity_id: switch.suite_switch
      # Continue script only if heating is on and not in holiday mode
      - condition: template
        value_template: "{{not is_state('climate.netatmo_general', 'off')}}"
      - condition: state
        entity_id: switch.holiday
        state: 'off'
      # Set thermostat away mode 
      - service: climate.set_preset_mode
        entity_id: climate.netatmo_general
        data_template:
          preset_mode: 'away'

  presence_someone_home:
    alias: 'Someone at home'
    sequence:
      # Disarm alarm
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home
      # Continue script only if heating is on and not in holiday mode
      - condition: template
        value_template: "{{not is_state('climate.netatmo_general', 'off')}}"
      - condition: state
        entity_id: switch.holiday
        state: 'off'
      # Set thermostat Schedule mode 
      - service: climate.set_preset_mode
        entity_id: climate.netatmo_general
        data_template:
          preset_mode: 'Schedule'

  presence_guest_mode_on:
    alias: 'Activate guest mode for 180 minutes'
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.guest_mode_minutes
          value: 180.0
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.guest_mode_minutes
  
  presence_leave_home:
    alias: 'Leave home'
    sequence:
      - delay:
          seconds: 5
      - service: tts.google_translate_say
        entity_id: media_player.recibidor
        data_template:
          message: >
            {% set incidence = false %}
            {%- if is_state("binary_sensor.porche_sensor_puerta", "on") %}{% set incidence = true %}Puerta de la cocina abierta. {% endif %}
            {%- if is_state("binary_sensor.porche_sensor_persiana", "on") %}{% set incidence = true %}Persiana de la cocina abierta. {% endif %}
            {%- if is_state("binary_sensor.coladuria_sensor_puerta", "on") %}{% set incidence = true %}Puerta de la coladuria abierta. {% endif %}
            {%- if is_state("switch.entrance_hall_lamp_switch", "on") %}{% set incidence = true %}Lámpara del recibidor encendida. {% endif %}
            {%- if is_state("switch.escalera_switch", "on") %}{% set incidence = true %}Luz de la escalera encendida. {% endif %}
            {%- if is_state("switch.suite_switch", "on") %}{% set incidence = true %}Luz de la suite encendida. {% endif %}
            {%- if is_state("sensor.outside_fence", "Abierta") %}{% set incidence = true %}Barrera abierta.{% endif -%}
            {%- if not incidence %}Todo correcto.{% endif %}
  
  presence_guest_mode_ga:
    alias: 'Activates the guest mode the specified number of minutes'
    sequence:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.guest_mode_minutes
          value: '{{data.minutes}}'
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.guest_mode
      - service: telegram_bot.send_message
        data_template:
          message: 'Google Assistant a autorizado presencia en casa durante {{data.minutes}} minutos'
          target: !secret hokusphone_telegram_chat_id
  
#  presence_jordi_at_home:
#    alias: 'Jordi at home'
#    sequence:
#      - service: device_tracker.see
#        data:
#          dev_id: 'jordi_combined'
#          location_name: 'home'

  presence_hokusphone_connected_home_wifi:
    alias: 'HokusPhone connected to home Wi-Fi'
    sequence:
      - service: mqtt.publish
        data:
          payload: 'home'
          retain: true
          topic: 'phone/sensor/hokus/wifi'

  presence_hokusphone_not_connected_home_wifi:
    alias: 'HokusPhone disconnected from home Wi-Fi'
    sequence:
      - service: mqtt.publish
        data:
          payload: 'not_home'
          retain: true
          topic: 'phone/sensor/hokus/wifi'

  presence_geniphone_connected_home_wifi:
    alias: 'GeniPhone connected to home Wi-Fi'
    sequence:
      - service: mqtt.publish
        data:
          payload: 'home'
          retain: true
          topic: 'phone/sensor/geni/wifi'

  presence_geniphone_not_connected_home_wifi:
    alias: 'GeniPhone disconnected from home Wi-Fi'
    sequence:
      - service: mqtt.publish
        data:
          payload: 'not_home'
          retain: true
          topic: 'phone/sensor/geni/wifi'

zone:
  - name: Oficina
    latitude: !secret office_latitude
    longitude: !secret office_longitude
    radius: 200
    icon: mdi:briefcase
  
  - name: Colegio
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 175
    icon: mdi:school
  
  - name: Hospital
    latitude: !secret office2_latitude
    longitude: !secret office2_longitude
    radius: 250
    icon: mdi:hospital-building
