homeassistant:
  customize:
    sensor.next_holiday_mode_start:
      icon: mdi:airplane-takeoff
    sensor.next_holiday_mode_end:
      icon: mdi:airplane-landing
    sensor.next_shift_event:
      icon: mdi:message
    sensor.next_shift_date:
      icon: mdi:calendar
    switch.holiday:
      friendly_name: 'Vacaciones'
      icon: mdi:airplane
    input_number.empty_home_activation_delay_minutes:
      icon: mdi:clock-end
    device_tracker.geniphone_wifi:
      source_type: router
    device_tracker.hokusphone_wifi:
      source_type: router
    device_tracker.guest:
      source_type: router
    person.jordi:
      entity_picture: 'https://s.gravatar.com/avatar/f5d192b4f4ffab4d9625f9b9e11d16b7?s=192'
    person.geni:
      entity_picture: '/local/person.geni.jpg'
    person.guest:
      entity_picture: '/local/person.guest.png'

recorder:
  include:
    domains:
      - person
    entities:
      - group.unidad_familiar

group:
  Unidad Familiar:
    entities:
      - person.jordi
      - person.geni
      - person.guest

input_boolean:
  guest_mode:
    name: Modo invitado
  #  initial: off
    icon: 'mdi:clock'

input_number:
  # Number of minutes to keep the guest mode on
  guest_mode_minutes:
    name: Minutos invitado
    initial: 180
    min: 0
    max: 240
    step: 5

device_tracker:
  - platform: mqtt
    devices:
      # Updated when hokusphone is connected to a WiFi
      hokusphone_wifi: phone/sensor/hokus/wifi
      # Updated when geniphone is connected to a WiFi
      geniphone_wifi: phone/sensor/geni/wifi

sensor:
  - platform: template
    sensors:
      next_holiday_mode_start:
        friendly_name: 'Inicio vacaciones'
        value_template: >-
             {%- if states.calendar.holiday_mode.attributes.start_time is not none %}
                 {{ as_timestamp(states.calendar.holiday_mode.attributes.start_time)|timestamp_custom("%d/%m/%Y %H:%M:%S") }}
             {% else %}
                 No previstas
             {%- endif %}
      next_holiday_mode_end:
        friendly_name: 'Fin vacaciones'
        value_template: >-
             {%- if states.calendar.holiday_mode.attributes.end_time is not none %}
                 {{ as_timestamp(states.calendar.holiday_mode.attributes.end_time)|timestamp_custom("%d/%m/%Y %H:%M:%S") }}
             {% else %}
                 No previstas
             {%- endif %}
      next_shift_event:
        friendly_name: 'Próx. turno'
        value_template: '{{ states.calendar.turnos_geni_everything.attributes.message }}'
      next_shift_date:
        friendly_name: 'Próx. turno'
        value_template: >-
            {%- if as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 0 %}
                Domingo, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 1 %}
                Lunes, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 2 %}
                Martes, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 3 %}
                Miércoles, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 4 %}
                Jueves, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 5 %}
                Viernes, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {% elif as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%w")|int == 6 %}
                Sábado, {{ as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time)|timestamp_custom("%d/%m/%Y") }}
            {%- endif %}

switch:
  - platform: mqtt
    name: 'holiday'
    state_topic: 'home/switch/holiday/status'
    command_topic: 'home/switch/holiday/status'
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 0
    retain: true

zone:
  - name: Oficina
    latitude: !secret office_latitude
    longitude: !secret office_longitude
    radius: 200
    icon: mdi:briefcase
  
  - name: Colegio
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 175
    icon: mdi:school
  
  - name: Hospital
    latitude: !secret office2_latitude
    longitude: !secret office2_longitude
    radius: 250
    icon: mdi:hospital-building
