# Hall camera
- platform: foscam
  ip: !secret cam_hall_host
  name: recibidor
  port: !secret cam_hall_port
  username: !secret cam_hall_username
  password: !secret cam_hall_password

 # Swiming pool camera
- platform: foscam
  ip: !secret cam_swimmingpool_host
  name: piscina
  port: !secret cam_swimmingpool_port
  username: !secret cam_swimmingpool_username
  password: !secret cam_swimmingpool_password

# Backyard stand camera
# For Linksys WVC54GCA http://<cam-host>:<cam_port>/img/snapshot.cgi
- platform: generic
  still_image_url: !secret cam_caseta_still_image_url
  name: caseta
  username: !secret cam_caseta_username
  password: !secret cam_caseta_password
  authentication: basic