# Hall camera
- platform: foscam
  ip: !secret cam_recibidor_host
  name: recibidor
  port: !secret cam_recibidor_port
  username: !secret cam_recibidor_username
  password: !secret cam_recibidor_password

 # Swiming pool camera
- platform: foscam
  ip: !secret cam_piscina_host
  name: piscina
  port: !secret cam_piscina_port
  username: !secret cam_piscina_username
  password: !secret cam_piscina_password

 # Bbq camera
- platform: foscam
  ip: !secret cam_barbacoa_host
  name: barbacoa
  port: !secret cam_barbacoa_port
  username: !secret cam_barbacoa_username
  password: !secret cam_barbacoa_password

# Backyard stand camera
# For Linksys WVC54GCA http://<cam-host>:<cam_port>/img/snapshot.cgi
- platform: generic
  still_image_url: !secret cam_caseta_still_image_url
  name: caseta
  username: !secret cam_caseta_username
  password: !secret cam_caseta_password
  authentication: basic

- platform: generic
  name: Toyota
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.toyota.attributes.latitude }},{{ states.device_tracker.toyota.attributes.longitude }}&zoom=15&size=1280x1024&maptype=roadmap&markers=icon:https%3A%2F%2Fhome.hokusnet.com%2Flocal%2Ftoyota-small-t.png%7C{{ states.device_tracker.toyota.attributes.latitude }},{{ states.device_tracker.toyota.attributes.longitude }}
  limit_refetch_to_url_change: true

- platform: generic
  name: Nissan
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.nissan.attributes.latitude }},{{ states.device_tracker.nissan.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:grey%7Clabel:N%7C{{ states.device_tracker.nissan.attributes.latitude }},{{ states.device_tracker.nissan.attributes.longitude }}
  limit_refetch_to_url_change: true

#- platform: onvif
#  name: pH Piscina
#  host: !secret cam_ph_piscina_host