# Hall camera
- platform: foscam
  ip: !secret cam_recibidor_host
  name: recibidor
  port: !secret cam_recibidor_port
  username: !secret cam_recibidor_username
  password: !secret cam_recibidor_password

 # Swiming pool camera
- platform: foscam
  ip: !secret cam_piscina_host
  name: piscina
  port: !secret cam_piscina_port
  username: !secret cam_piscina_username
  password: !secret cam_piscina_password

# Backyard stand camera
# For Linksys WVC54GCA http://<cam-host>:<cam_port>/img/snapshot.cgi
- platform: generic
  still_image_url: !secret cam_caseta_still_image_url
  name: caseta
  username: !secret cam_caseta_username
  password: !secret cam_caseta_password
  authentication: basic