homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 119
  unit_system: metric
  customize: !include customize.yaml

http:
  api_password: !secret ha_api_password
  trusted_networks:
    - 127.0.0.1
#  ssl_certificate: !secret ha_ssl_certificate
#  ssl_key: !secret ha_ssl_key
  #server_port: 8123
  #development: 1

  # Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
discovery:

#############################################
# Temporary until discovery service is fixed.
#media_player:
#  - platform: squeezebox
#    host: 192.168.1.2
#    port: 9001
#  - platform: cast

#wemo:
#  static:
#    - 192.168.1.110
##    - 192.168.1.111
#    - 192.168.1.112
#    - 192.168.1.113
# END Temporary until discovery service is fixed.
#################################################

# Checks for available updates
updater:

# Enables support for tracking state changes over time.
history:

config:

recorder:
  purge_days: 14
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - script
      - zone
      - group
      - calendar
    entities:
      - sensor.since_last_boot
      - sensor.last_boot
      - sensor.next_shift_event
      - sensor.next_shift_date
      - sensor.next_holiday_mode_start
      - sensor.next_holiday_mode_end
      - sensor.nut_ups_manufacturer
      - sensor.nut_ups_model
      - sun.sun

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

logger:
  default: warn
#  logs:
#    homeassistant.components.apiai: debug
#    homeassistant.helpers.script: debug
#    homeassistant.components.device_tracker: info
#    libopenzwave: warn
#    openzwave: debug
#    homeassistant.core: debug
#    homeassistant.components.sensor.speedtest: debug
#    homeassistant.components.switch.command_line: critical

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

  - name: HTML5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

#  - platform: pushbullet
#    name: pushbullet
#    api_key: !secret pushbullet_api_key

ifttt:
  key: !secret ifttt_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

#foursquare:
#  access_token: !secret foursquare_access_token
#  push_secret: !secret foursquare_push_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'es'

shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automation.yaml
script: !include scripts.yaml
input_slider: !include input_sliders.yaml
input_boolean: !include input_booleans.yaml
panel_iframe: !include panel_iframes.yaml
#scene: !include scenes.yaml
apiai: !include apiai.yaml