homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 119
  unit_system: metric
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/camera

http:
  api_password: !secret ha_api_password
  trusted_networks:
    - 127.0.0.1
  base_url: !secret ha_base_url
#  ssl_certificate: !secret ha_ssl_certificate
#  ssl_key: !secret ha_ssl_key
  #server_port: 8123
  #development: 1

  # Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
#conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
discovery:

#############################################
# Temporary until discovery service is fixed.
#media_player:
#  - platform: squeezebox
#    host: 192.168.1.2
#    port: 9001
#  - platform: cast

#wemo:
#  static:
#    - 192.168.1.110
##    - 192.168.1.111
#    - 192.168.1.112
#    - 192.168.1.113
# END Temporary until discovery service is fixed.
#################################################

# Checks for available updates
updater:
  include_used_components: true

# Enables support for tracking state changes over time.
history:

config:

recorder:
  purge_days: 14
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - script
      - zone
      - group
      - calendar
      - zwave
    entities:
      - sensor.since_last_boot
      - sensor.last_boot
      - sensor.next_shift_event
      - sensor.next_shift_date
      - sensor.next_holiday_mode_start
      - sensor.next_holiday_mode_end
      - sensor.nut_ups_manufacturer
      - sensor.nut_ups_model
      - sun.sun
      - sensor.sunrise
      - sensor.sunset
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_access_control
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_alarm_level
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_alarm_type
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_burglar
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_general
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_sourcenodeid
      - binary_sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_sensor
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_access_control
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_alarm_level
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_alarm_type
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_burglar
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_general
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_sourcenodeid
      - binary_sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_sensor
      - binary_sensor.fibaro_fgms001_motion_sensor_salon_sensor
      - sensor.fibaro_fgms001_motion_sensor_salon_alarm_level
      - sensor.fibaro_fgms001_motion_sensor_salon_alarm_type
      - sensor.fibaro_fgms001_motion_sensor_salon_burglar
      - sensor.fibaro_fgms001_motion_sensor_salon_general
      - sensor.fibaro_fgms001_motion_sensor_salon_luminance
      - sensor.fibaro_fgms001_motion_sensor_salon_seismic_intensity
      - sensor.fibaro_fgms001_motion_sensor_salon_sourcenodeid
      - sensor.fibaro_fgms001_motion_sensor_salon_temperature
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_alarm_level
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_alarm_type
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy_2
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_exporting
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_exporting_2
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_heat
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_interval
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_2
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_management
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_previous_reading
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_sourcenodeid
      - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
      - sensor.recibidor_termometro_temperatura
      - sensor.exterior_termometro_temperatura
      - sensor.exterior_termometro_humedad
      - sensor.exterior_termometro_max_temp
      - sensor.exterior_termometro_min_temp
      - sensor.salon_termometro_co2
      - sensor.salon_termometro_temperatura
      - sensor.salon_termometro_humedad
      - sensor.salon_termometro_max_temp
      - sensor.salon_termometro_min_temp
      - sensor.salon_termometro_ruido
      - sensor.salon_termometro_presion
      - sensor.suite_termometro_co2
      - sensor.suite_termometro_temperatura
      - sensor.suite_termometro_humedad
      - sensor.suite_termometro_max_temp
      - sensor.suite_termometro_min_temp
      - sensor.exterior_pluviometro_lluvia
      - sensor.exterior_pluviometro_lluvia_1
      - sensor.exterior_pluviometro_lluvia_24
      - sensor.exterior_anemometro_velocidad_viento
      - sensor.on_off_switch_termostato
      - sensor.on_off_switch_termostato_modo_ausente
      - sensor.on_off_switch_piscina
      - sensor.on_off_group_luces_exteriores
      - sensor.on_off_group_luces_interiores
      - sensor.on_off_switch_swiid_swiidinter_lampara_recibidor_switch
      - sensor.on_off_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - sensor.on_off_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
      - sensor.on_off_switch_caseta_camara_deteccion_movimiento
      - sensor.on_off_switch_piscina_camara_deteccion_movimiento
      - sensor.on_off_switch_recibidor_camara_deteccion_movimiento
      - sensor.on_off_input_boolean_salon_detector_movimiento
      - sensor.on_off_input_boolean_cocina_sensor_puerta
      - sensor.on_off_input_boolean_cocina_sensor_persiana
      - sensor.on_off_switch_holiday
      - sensor.on_off_switch_ups_beeper
      - sensor.on_off_group_seguridad
      - sensor.on_off_switch_barrera
      - sensor.check_switch_termostato
      - sensor.check_switch_termostato_modo_ausente
      - sensor.check_switch_piscina
      - sensor.check_group_luces_exteriores
      - sensor.check_group_luces_interiores
      - sensor.check_switch_swiid_swiidinter_lampara_recibidor_switch
      - sensor.check_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - sensor.check_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
      - sensor.check_switch_caseta_camara_deteccion_movimiento
      - sensor.check_switch_piscina_camara_deteccion_movimiento
      - sensor.check_switch_recibidor_camara_deteccion_movimiento
      - sensor.check_input_boolean_salon_detector_movimiento
      - sensor.check_input_boolean_cocina_sensor_puerta
      - sensor.check_input_boolean_cocina_sensor_persiana
      - sensor.check_switch_holiday
      - sensor.check_switch_ups_beeper
      - sensor.check_group_seguridad
      - sensor.check_switch_barrera
      - sensor.check_sensor_cocina_sensor_persiana
      - sensor.check_sensor_cocina_sensor_puerta
      - device_tracker.ac63be0b8591
      - device_tracker.48e9f1ef7911
      - device_tracker.d013fd1259af
      - device_tracker.d47bb0af2168
      - device_tracker.dc415fda59c2
      - device_tracker.f81654845f30
      - device_tracker.flex_2
      - device_tracker.hokusphone_mqtt
      - device_tracker.geni_nmap
      - device_tracker.toyota
      - group.toyota
      - camera.toyota

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

logger:
  default: warn
#  logs:
#    homeassistant.components.apiai: debug
#    homeassistant.helpers.intent: debug
#    homeassistant.components.intent_script: debug
#    homeassistant.helpers.script: debug
#    homeassistant.components.device_tracker: info
#    libopenzwave: warn
#    openzwave: debug
#    homeassistant.core: debug
#    homeassistant.components.sensor.speedtest: debug
#    homeassistant.components.switch.command_line: critical

telegram_bot:
  platform: broadcast
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

  - name: HTML5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

#  - platform: pushbullet
#    name: pushbullet
#    api_key: !secret pushbullet_api_key

ifttt:
  key: !secret ifttt_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

#foursquare:
#  access_token: !secret foursquare_access_token
#  push_secret: !secret foursquare_push_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'es'

apiai:

shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_slider: !include input_sliders.yaml
input_boolean: !include input_booleans.yaml
panel_iframe: !include panel_iframes.yaml
intent_script: !include intent_scripts.yaml
#scene: !include scenes.yaml

