homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 119
  unit_system: metric
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/camera

http:
  api_password: !secret ha_api_password
#  trusted_networks:
#    - 127.0.0.1
  base_url: !secret ha_base_url
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5
#  ssl_certificate: !secret ha_ssl_certificate
#  ssl_key: !secret ha_ssl_key
  #server_port: 8123
  #development: 1

map:

  # Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
#conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
discovery:

# Checks for available updates
updater:
  include_used_components: true

# Enables support for tracking state changes over time.
history:

config:

wemo:
  static:
    # Maker
    - 10.155.106.110
    # Switch
#    - 10.155.106.111
    # Link
    - 10.155.106.112

media_player:
    # TV
  - platform: cast
    host: 10.155.106.114
    # Home-Assistant
  - platform: cast
    host: 10.155.106.143

recorder:
  purge_interval: 1
  purge_keep_days: 30
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - script
      - zone
      - group
      - calendar
      - zwave
      - updater
      - camera
      - media_player
    entities:
      - sensor.since_last_boot
      - sensor.last_boot

      - sensor.next_shift_event
      - sensor.next_shift_date
      - sensor.next_holiday_mode_start
      - sensor.next_holiday_mode_end
      - sensor.next_holiday_mode_end
      - sensor.next_holiday_mode_start
      - sensor.next_shift_date
      - sensor.next_shift_event
      - sensor.check_switch_holiday

      - sensor.nut_ups_manufacturer
      - sensor.nut_ups_model
      - sensor.nut_ups_status_data
      - sensor.nut_ups_beeper_status
      - sensor.nut_ups_battery_runtime
      - sensor.nut_ups_battery_charge

      - sun.sun
      - sensor.season
      - sensor.estacion
      - sensor.date
      - sensor.time
      - sensor.date__time
      - sensor.sunrise
      - sensor.sunset

      - sensor.pws_weather
      - sensor.pws_weather_1d_metric
      - sensor.pws_alerts

      - sensor.hokusnasserver_uptime
      - sensor.hokusnasserver_uptime_timeticks

      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_access_control
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_alarm_level
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_alarm_type
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_burglar
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_general
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_sourcenodeid
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_system
      - sensor.fibaro_fgk10x_door_opening_sensor_piscina_heat
      - binary_sensor.fibaro_fgk10x_door_opening_sensor_piscina

      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_access_control
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_alarm_level
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_alarm_type
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_burglar
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_general
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_sourcenodeid
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_system
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche_heat
      - binary_sensor.fibaro_fgk10x_door_opening_sensor_puerta_porche

      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_access_control
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_alarm_level
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_alarm_type
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_burglar
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_general
      - sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche_sourcenodeid
      - binary_sensor.fibaro_fgk10x_door_opening_sensor_persiana_porche

      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria_access_control
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria_alarm_level
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria_alarm_type
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria_burglar
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria_general
      - sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria_sourcenodeid
      - binary_sensor.fibaro_fgk10x_door_opening_sensor_puerta_coladuria

      - binary_sensor.fibaro_fgms001_motion_sensor_salon
      - sensor.fibaro_fgms001_motion_sensor_salon_alarm_level
      - sensor.fibaro_fgms001_motion_sensor_salon_alarm_type
      - sensor.fibaro_fgms001_motion_sensor_salon_burglar
      - sensor.fibaro_fgms001_motion_sensor_salon_general
      - sensor.fibaro_fgms001_motion_sensor_salon_seismic_intensity
      - sensor.fibaro_fgms001_motion_sensor_salon_sourcenodeid

      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_alarm_level
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_alarm_type
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_exporting
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_exporting_2
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_heat
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_interval
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_management
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_previous_reading
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_sourcenodeid
      - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2

      - sensor.recibidor_termometro_temperatura
      - sensor.exterior_termometro_temperatura
      - sensor.exterior_termometro_humedad
      - sensor.exterior_termometro_max_temp
      - sensor.exterior_termometro_min_temp
      - sensor.netatmo_exterior_radio
      - sensor.netatmo_exterior_battery

      - sensor.salon_termometro_co2
      - sensor.salon_termometro_temperatura
      - sensor.salon_termometro_humedad
      - sensor.salon_termometro_max_temp
      - sensor.salon_termometro_min_temp
      - sensor.salon_termometro_ruido
      - sensor.salon_termometro_presion

      - sensor.suite_termometro_co2
      - sensor.suite_termometro_temperatura
      - sensor.suite_termometro_humedad
      - sensor.suite_termometro_max_temp
      - sensor.suite_termometro_min_temp
      - sensor.netatmo_suite_radio
      - sensor.netatmo_suite_battery

      - sensor.habitacion_termometro_co2
      - sensor.habitacion_termometro_temperatura
      - sensor.habitacion_termometro_humedad
      - sensor.habitacion_termometro_max_temp
      - sensor.habitacion_termometro_min_temp
      - sensor.netatmo_habitacion_radio
      - sensor.netatmo_habitacion_battery

      - sensor.exterior_pluviometro_lluvia
      - sensor.exterior_pluviometro_lluvia_1
      - sensor.exterior_pluviometro_lluvia_24
      - sensor.netatmo_pluviometro_radio
      - sensor.netatmo_pluviometro_battery

      - sensor.exterior_anemometro_velocidad_viento
      - sensor.netatmo_anemometro_gust_angle
      - sensor.netatmo_anemometro_angle
      - sensor.netatmo_anemometro_radio
      - sensor.netatmo_anemometro_battery

      - sensor.on_off_switch_termostato
      - sensor.on_off_switch_termostato_modo_ausente
      - sensor.on_off_switch_piscina
      - sensor.on_off_group_luces_exteriores
      - sensor.on_off_group_luces_interiores
      - sensor.on_off_switch_swiid_swiidinter_lampara_recibidor_switch
      - sensor.on_off_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - sensor.on_off_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
      - sensor.on_off_switch_caseta_camara_det_mov
      - sensor.on_off_switch_piscina_camara_det_mov
      - sensor.on_off_switch_recibidor_camara_det_mov
      - sensor.on_off_input_boolean_salon_detector_movimiento
      - sensor.on_off_input_boolean_cocina_sensor_puerta
      - sensor.on_off_input_boolean_cocina_sensor_persiana
      - sensor.on_off_switch_holiday
      - sensor.on_off_switch_ups_beeper
      - sensor.on_off_group_seguridad
      - sensor.on_off_switch_barrera
      - sensor.check_switch_termostato
      - sensor.check_switch_termostato_modo_ausente
      - sensor.check_switch_piscina
      - sensor.check_group_luces_exteriores
      - sensor.check_group_luces_interiores
      - sensor.check_switch_swiid_swiidinter_lampara_recibidor_switch
      - sensor.check_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - sensor.check_switch_fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
      - sensor.check_switch_caseta_camara_det_mov
      - sensor.check_switch_piscina_camara_det_mov
      - sensor.check_switch_recibidor_camara_det_mov
      - sensor.check_input_boolean_salon_detector_movimiento
      - sensor.check_input_boolean_cocina_sensor_puerta
      - sensor.check_input_boolean_cocina_sensor_persiana
      - sensor.check_switch_holiday
      - sensor.check_switch_ups_beeper
      - sensor.check_group_seguridad
      - sensor.check_switch_barrera
      - sensor.check_sensor_cocina_sensor_persiana
      - sensor.check_sensor_cocina_sensor_puerta

      - sensor.toyota_previous_latitude
      - sensor.toyota_previous_longitude
      - sensor.toyota_last_update
      
      - sensor.nissan_last_update

      - device_tracker.ac63be0b8591
      - device_tracker.48e9f1ef7911
      - device_tracker.d013fd1259af
      - device_tracker.d47bb0af2168
      - device_tracker.dc415fda59c2
      - device_tracker.f81654845f30
      - device_tracker.e0b52dc9f7e4
      - device_tracker.ac83f303a892
      - device_tracker.54724f769044
      - device_tracker.70ee502aa1ac
      - device_tracker.748d08da83b9
      - device_tracker.64b5c60cdc86
      - device_tracker.flex_2
      - device_tracker.toyota
      - device_tracker.hp_photosmart_5520
#      - device_tracker.jordi_combined
#      - device_tracker.hokusphone_nmap
#      - device_tracker.hokusphone_wifi
#      - device_tracker.hokusphone_ibeacon
#      - device_tracker.geni_combined
#      - device_tracker.geniphone_nmap
#      - device_tracker.geniphone_wifi
#      - device_tracker.geniphone_ibeacon
      - device_tracker.virtual_device

      - binary_sensor.exterior_termometro_temperatura_descendiendo
      - binary_sensor.exterior_termometro_temperatura_aumentando
      - sensor.exterior_termometro_temperatura_tendencia

      - binary_sensor.salon_termometro_temperatura_descendiendo
      - binary_sensor.salon_termometro_temperatura_aumentando
      - sensor.salon_termometro_temperatura_tendencia

      - binary_sensor.recibidor_termometro_temperatura_descendiendo
      - binary_sensor.recibidor_termometro_temperatura_aumentando
      - sensor.recibidor_termometro_temperatura_tendencia

      - binary_sensor.suite_termometro_temperatura_descendiendo
      - binary_sensor.suite_termometro_temperatura_aumentando
      - sensor.suite_termometro_temperatura_tendencia

      - binary_sensor.habitacion_termometro_temperatura_descendiendo
      - binary_sensor.habitacion_termometro_temperatura_aumentando
      - sensor.habitacion_termometro_temperatura_tendencia

      - binary_sensor.primera_planta_temperatura_aumentando
      - binary_sensor.primera_planta_temperatura_descendiendo
      - sensor.primera_planta_temperatura_tendencia

      - binary_sensor.salon_termometro_co2_descendiendo
      - binary_sensor.salon_termometro_co2_aumentando
      - sensor.salon_termometro_co2_tendencia
      
      - binary_sensor.suite_termometro_co2_descendiendo
      - binary_sensor.suite_termometro_co2_aumentando
      - sensor.suite_termometro_co2_tendencia

      - binary_sensor.habitacion_termometro_co2_descendiendo
      - binary_sensor.habitacion_termometro_co2_aumentando
      - sensor.habitacion_termometro_co2_tendencia

      - binary_sensor.planta_baja_temperatura_aumentando
      - binary_sensor.planta_baja_temperatura_descendiendo
      - sensor.planta_baja_temperatura_tendencia

      - sensor.piscina_k_factor
      - sensor.piscina_pump_efficiency
      - sensor.piscina_off_time
      - sensor.piscina_on_time

      - binary_sensor.workday_sensor
      - input_number.empty_home_activation_delay_minutes
      - image_processing.sevensegement_ocr_ph_piscina

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

logger:
  default: warn
  logs:
    openzwave: warn
    libopenzwave: warn
    homeassistant.components.zwave: warn
    homeassistant.components.zwave.util: warn
    homeassistant.components.websocket_api: warn
    homeassistant.components.switch.command_line: warn
    homeassistant.components.sensor.command_line: warn
#    homeassistant.components.dialogflow: debug
#    homeassistant.components.telegram_bot: debug
#    homeassistant.components.dialogflow: debug
#    homeassistant.helpers.intent: debug
#    homeassistant.components.intent_script: debug
#    homeassistant.helpers.script: debug
#    homeassistant.components.device_tracker: info
#    homeassistant.core: debug
#    homeassistant.components.sensor.speedtest: debug
#    homeassistant.core: debug

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret hokusphone_telegram_chat_id
    - !secret hokuscar_telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret hokusphone_telegram_chat_id

#  - name: HTML5
#    platform: html5
#    gcm_api_key: !secret gcm_api_key
#    gcm_sender_id: !secret gcm_sender_id

#  - platform: pushbullet
#    name: pushbullet
#    api_key: !secret pushbullet_api_key

ifttt:
  key: !secret ifttt_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: true

#foursquare:
#  access_token: !secret foursquare_access_token
#  push_secret: !secret foursquare_push_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_api_key
  expose_by_default: true
  entity_config:
    switch.recibidor_camara_det_mov:
      name: Detección movimento recibidor
      aliases:
        - detección de movimiento del recibidor
        - deteccion de movimiento del recibidor
        - detección movimiento recibidor
        - deteccion movimiento recibidor
        - detector de movimiento del recibidor
        - detector movimiento recibidor
        - detector de movimiento recibidor
        - detector movimiento del recibidor
        - detección de movimento recibidor
        - deteccion de movimiento recibidor
        - detección movimiento del recibidor
        - deteccion movimiento del recibidor
      room: Recibidor

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'es'

dialogflow:

freedns:
  access_token: !secret freedns_token

folder_watcher:
  - folder: /home/camera
    patterns:
      - '*.jpg'

#climate:
#  - platform: netatmo

shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_number: !include input_sliders.yaml
input_boolean: !include input_booleans.yaml
panel_iframe: !include panel_iframes.yaml
#panel_custom: !include panel_custom.yaml
intent_script: !include intent_scripts.yaml
#image_processing: !include image_processing.yaml
history_graph: !include history_graph.yaml
#scene: !include scenes.yaml

