- platform: seven_segments
  x_position: 480
  y_position: 250
  height: 480
  width: 240
  threshold: 50
  extra_arguments: -D -i 4 remove_isolated closing 3
  source:
    - entity_id: camera.ph_piscina

