- platform: seven_segments
  x_position: 250
  y_position: 100
  height: 52
  width: 120
  threshold: 50
  extra_arguments: -C rotate 358 dilation 1 erosion 2
  source:
    - entity_id: camera.ph_piscina

