- alias: '[Fence - State] Publish to mqtt fence status'
  trigger:
    platform: state
    entity_id: switch.barrera
    to: 'off'
  action:
    - service: mqtt.publish
      data:
        topic: home/sensor/fence
        payload_template: >-
          {%- if is_state("sensor.outside_fence_sensor_state", "off") %}
            En movimiento
          {%- else %}
            Cerrada
          {%- endif %}
        qos: 0
        retain: true
    - delay:
        seconds: 18
    - service: mqtt.publish
      data:
        topic: home/sensor/fence
        payload_template: >-
          {%- if is_state("sensor.outside_fence_sensor_state", "off") %}
            Abierta
          {% else %}
            Cerrada
          {%- endif %}
        qos: 0
        retain: true

- alias: '[Fence - State] Publish to mqtt fence moving (En movimiento) status'
  trigger:
    platform: state
    entity_id: switch.barrera
    to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: home/sensor/fence
        payload: "En movimiento"
        qos: 0
        retain: true

- alias: '[Fence - State] Publish to mqtt fence closed (Cerrada) status'
  trigger:
    platform: state
    entity_id: sensor.outside_fence_sensor_state
    to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: home/sensor/fence
        payload: Cerrada
        qos: 0
        retain: true
