# Turn on outside lights at sunset
- alias: '[Lights - Outside] Turn on outside lights'
  trigger:
    platform: sun
    event: 'sunset'
  action:
    - service: script.turn_on_outside_lights_75pct
      data_template:
        data:
          logbook_message: 'encendidas por la puesta de sol'

# Turn off outside lights at night (at 00:15)
- alias: '[Lights - Outside] Turn off outside lights'
  trigger:
    platform: time
    at: '00:15'
  condition:
    condition: state
    entity_id: light.luces_exteriores
    state: 'on'
  action:
    - service: script.turn_off_outside_lights
      data_template:
        data:
          logbook_message: 'apagadas a las 00:15'

# When the outside lights have been turned on at late night (later than 00:15) and before sunrise, turn them off after 5 minutes
- alias: '[Lights - Outside] Turn off outside lights at night'
  trigger:
    platform: state
    entity_id: light.luces_exteriores
    to: 'on'
  condition:
    - condition: time
      after: '00:15'
    - condition: sun
      before: sunrise
  action:
    - delay:
        minutes: 5
    - service: script.turn_off_outside_lights
      data_template:
        data:
          logbook_message: 'apagadas más tarde de las 00:15'
     
# Turn off outside lights after 10 seconds when the sun is not set
- alias: '[Lights - Outside] Turn off outside lights during day'
  trigger:
    platform: state
    entity_id: light.luces_exteriores
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunset
    - condition: sun
      after: sunrise
  action:
    - delay:
        seconds: 10
    - service: script.turn_off_outside_lights
      data_template:
        data:
          logbook_message: 'apagadas porque es de dia'

# Turn on outside lights when fence is opened and the sun is set
- alias: '[Lights - Outside] Turn on outside lights when fence is opened'
  trigger:
    platform: state
    entity_id: sensor.outside_fence
    from: 'Cerrada'
    to: 'En movimiento'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
    - service: script.turn_on_outside_lights_75pct
      data_template:
        data:
          logbook_message: 'encendidas porque se ha abierto la barrera y es de noche'
