- alias: '[Lights - Outside] When turn on outside lights, adjust brightness to 75%'
  trigger:
    platform: state
    entity_id: light.luces_exteriores
    to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.luces_exteriores
        brightness: '{{ (75 * 255) // 100 }}'

# Turn on outside lights at sunset (+15 minutes)
- alias: '[Lights - Outside] Turn on outside lights at sunset (+15 minutes)'
  trigger:
    platform: sun
    event: 'sunset'
    offset: '00:15:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.luces_exteriores
        brightness: '{{ (75 * 255) // 100 }}'
    - service: logbook.log
      data:
        name: 'Luces exteriores'
        message: 'encendidas por la puesta de sol'
        entity_id: light.luces_exteriores
        domain: light

- alias: '[Lights - Outside] Turn off outside lights at night (at 00:15)'
  trigger:
    platform: time
    at: '00:15'
  condition:
    condition: state
    entity_id: light.luces_exteriores
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.luces_exteriores
    - service: logbook.log
      data:
        name: 'Luces exteriores'
        message: 'apagadas a las 00:15'
        entity_id: light.luces_exteriores
        domain: light

- alias: '[Lights - Outside] When the outside lights have been turned on at late night (later than 00:15) and before sunrise, turn them off after 5 minutes'
  trigger:
    platform: state
    entity_id: light.luces_exteriores
    to: 'on'
  condition:
    - condition: time
      after: '00:15'
    - condition: sun
      before: sunrise
  action:
    - delay:
        minutes: 5
    - service: light.turn_off
      data:
        entity_id: light.luces_exteriores
    - service: logbook.log
      data:
        name: 'Luces exteriores'
        message: 'apagadas más tarde de las 00:15'
        entity_id: light.luces_exteriores
        domain: light

- alias: '[Lights - Outside] Turn off outside lights after 10 seconds when the sun is not set'
  trigger:
    platform: state
    entity_id: light.luces_exteriores
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunset
    - condition: sun
      after: sunrise
  action:
    - delay:
        seconds: 10
    - service: light.turn_off
      data:
        entity_id: light.luces_exteriores
    - service: logbook.log
      data:
        name: 'Luces exteriores'
        message: 'apagadas porque es de dia'
        entity_id: light.luces_exteriores
        domain: light

- alias: '[Lights - Outside] Turn on outside lights when fence is opened and the sun is set'
  trigger:
    platform: state
    entity_id: sensor.outside_fence
    from: 'Cerrada'
    to: 'En movimiento'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.luces_exteriores
        brightness: '{{ (75 * 255) // 100 }}'
    - service: logbook.log
      data:
        name: 'Luces exteriores'
        message: 'encendidas porque se ha abierto la barrera y es de noche'
        entity_id: light.luces_exteriores
        domain: light
