# Notify presence detection in any activated sensor when sensor active and alarm triggered
- alias: 'Alarm - Notification - Presence detection'
  trigger: 
    - platform: state
      entity_id: binary_sensor.porche_sensor_puerta
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.porche_sensor_persiana
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.coladuria_sensor_puerta
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.despacho_sensor_movimiento
      to: 'on'
  condition:
    - condition: template
      value_template: >- 
        {%- set inputBooleanMap ={"binary_sensor.porche_sensor_puerta": "input_boolean.porche_sensor_puerta",
                         "binary_sensor.porche_sensor_persiana": "input_boolean.porche_sensor_persiana",
                         "binary_sensor.coladuria_sensor_puerta": "input_boolean.coladuria_sensor_puerta",
                         "binary_sensor.despacho_sensor_movimiento": "input_boolean.despacho_sensor_movimiento"}
         -%}
         {{is_state(inputBooleanMap[trigger.entity_id],'on')}}
  action:
    # Delay before evaluating alarm state. This is needed to avoid skipping notifications
    - delay:
        seconds: 1
    # Only continue execution if alarm has been triggered
    - condition: state
      entity_id: alarm_control_panel.home
      state: 'triggered'
    - service: script.alarm_notify_sensor
      data_template:
        data:
          message: >-
            {%- set messageMap ={"binary_sensor.porche_sensor_puerta": "Puerta de la cocina abierta",
                             "binary_sensor.porche_sensor_persiana": "Persiana de la cocina abierta",
                             "binary_sensor.coladuria_sensor_puerta": "Puerta de la coladuría abierta",
                             "binary_sensor.despacho_sensor_movimiento": "Movimiento detectado en el despacho"}
             -%}
            {{messageMap[trigger.entity_id]}}
          turn_off_entity_id: >-
            {%- set turnOffEntityId ={"binary_sensor.porche_sensor_puerta": "input_boolean.porche_sensor_puerta",
                             "binary_sensor.porche_sensor_persiana": "input_boolean.porche_sensor_persiana",
                             "binary_sensor.coladuria_sensor_puerta": "input_boolean.coladuria_sensor_puerta",
                             "binary_sensor.despacho_sensor_movimiento": "input_boolean.despacho_sensor_movimiento"}
             -%}
            {{turnOffEntityId[trigger.entity_id]}}