- alias: 'Car - Zone - Ioniq enters Cargador Sant Miquel'
  trigger:
     - platform: zone
       entity_id: device_tracker.car_ioniq
       zone: zone.cargador_sant_miquel
       event: enter
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.car_ioniq_state
        state: 'on'
      - condition: template
        value_template: "{{ (state_attr('device_tracker.car_ioniq', 'gps_accuracy')|int) < 100}}"
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          El cargador de Sant Miquel está {{ states.sensor.cargador_sant_miquel.state }}
        retain: false
        topic: 'phone/sensor/hokus/cmnd/say'
    - service: notify.telegram
      data_template:
        message: 'El cargador de Sant Miquel está {{ states.sensor.cargador_sant_miquel.state }}'