- alias: 'Car - Zone - Ioniq enters Cargador Conquistador'
  trigger:
     - platform: zone
       entity_id: device_tracker.car_ioniq
       zone: zone.cargador_conquistador
       event: enter
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          El cargador de Conquistador está {{ states.sensor.cargador_conquistador.state }}
        retain: false
        topic: 'phone/sensor/hokus/cmnd/say'
    - service: notify.telegram
      data_template:
        message: 'El cargador de Conquistador está {{ states.sensor.cargador_conquistador.state }}'