- alias: 'Car - Notification - Ioniq charge finishes'
  trigger:
    platform: state
    entity_id: sensor.car_ioniq_charge_state
    from: 'Cargando'
  action:
    - service: notify.telegram
      data_template:
        message: >-
          Carga del Ioniq finalizada. {{state_attr('switch.car_ioniq_charger', 'today_energy_kwh')}} kWh cargados.