- alias: 'Car - Zone - Ioniq enters Cargador Sant Miquel'
  trigger:
     - platform: zone
       entity_id: device_tracker.car_ioniq
       zone: zone.cargador_sant_miquel
       event: enter
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          El cargador de Sant Miquel está {{ states.sensor.cargador_sant_miquel.state }}
        retain: false
        topic: 'phone/sensor/hokus/cmnd/say'
    - service: notify.telegram
      data_template:
        message: 'El cargador de Sant Miquel está {{ states.sensor.cargador_sant_miquel.state }}'