- alias: 'Energy - Tariff - Change'
  trigger:
    platform: mqtt
    topic: 'home/sensor/energy/tariff'
  action:
    - service: utility_meter.select_tariff
      data_template:
        entity_id: utility_meter.energy_home_daily 
        tariff: '{{trigger.payload}}'
    - service: utility_meter.select_tariff
      data_template:
        entity_id: utility_meter.energy_home_monthly
        tariff: '{{trigger.payload}}'
