- alias: 'NodOn Remote - Button 3 pressed'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 30
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 3 apretado'