- alias: 'NodOn Remote - Button 4 double click'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 43
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 4 doble pulsación'
