- alias: 'Presence - Notification - Geni not at home'
  trigger:
    - platform: state
      entity_id: person.geni
      from: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Geni no está en casa'