- alias: 'Presence - Notification - Nobody at home'
  trigger:
    - platform: state
      entity_id: group.unidad_familiar
      from: 'home'
  action:
    - delay:
        seconds: 2
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'No hay nadie en casa'