- alias: 'Swimming Pool - Notification - Pump on more than expected'
  trigger: 
    platform: template
    value_template: '{{states.sensor.piscina_on_history.state|float > (states.sensor.piscina_filtering_time.state|float + 0.15)}}'
  condition:
    condition: state
    entity_id: switch.motor_piscina
    state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: 'Motor piscina encendido hoy durante {{states.sensor.piscina_on_history.state}} horas. Tiempo programado {{states.sensor.piscina_filtering_time.state}} horas.'
        inline_keyboard: 
          - 'Apagar:/homeassistant.turn_off#switch.motor_piscina'
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'warning'
              pretext: ':swimmer: *Piscina* :swimmer:'
              text: 'Motor piscina encendido hoy durante {{states.sensor.piscina_on_history.state}} horas. Tiempo programado {{states.sensor.piscina_filtering_time.state}} horas.'
              fallback: 'Piscina'
