- alias: 'System - At 3 AM'
  trigger:
    platform: time
    at: '3:00:00'
  action:
  - service: hassio.snapshot_full
    data_template:
      name: '{{ now().strftime("%Y%m%d") }} - Auto'
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'danger'
            pretext: ':floppy_disk: *Copia seguridad* :floppy_disk:'
            text: 'Copia de seguridad [{{ now().strftime("%Y%m%d") }} - Auto] creada'
            fallback: 'Copia seguridad'