alias: '[Comfort] Sleep mode event received'
trigger:
  platform: event
  event_type: sleep_mode
action:
  - service: logbook.log
    data:
      name: 'Modo nocturno'
      message: 'es hora de irse a dormir'
  - service: script.turn_on
    data:
      entity_id: script.goto_sleep
