- alias: '[Car - Charge] Turn off Ioniq car charger 5 mins after Valle tariff finishes'
  trigger:
    platform: state
    entity_id: utility_meter.energy_home_daily
    from: 'Valle'
  action:
    - delay:
        minutes: 5
    - service: switch.turn_off
      entity_id: switch.car_ioniq_charger
