- alias: '[Car - Notification] Notify when Ioniq charge finishes'
  trigger:
    platform: state
    entity_id: sensor.car_ioniq_charge_state
    from: 'Cargando'
  action:
    - service: notify.telegram
      data_template:
        message: >-
          Carga del Ioniq finalizada. {{state_attr('switch.car_ioniq_charger', 'today_energy_kwh')}} kWh cargados.

- alias: '[Car - Notification] Notify when Ioniq battery health is below 100%'
  trigger:
    platform: numeric_state
    entity_id: sensor.car_ioniq_state_battery_health
    below: 100
  action:
    - service: notify.telegram
      data_template:
        message: 'La salud de la batería del Ioniq es del: {{states.sensor.car_ioniq_state_battery_health.state}}{{states.sensor.car_ioniq_state_battery_health.attributes.unit_of_measurement}}'
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'warning'
              pretext: ':oncoming_automobile: *Coche* :oncoming_automobile:'
              text: 'La salud de la batería del Ioniq es del: {{states.sensor.car_ioniq_state_battery_health.state}}{{states.sensor.car_ioniq_state_battery_health.attributes.unit_of_measurement}}'
              fallback: 'Coche'
