- alias: '[Car - State] Publish Ioniq daily state'
  trigger:
    platform: time
    at: '23:59:00'
  action:
    - service: mqtt.publish
      data:
        topic: 'car/sensor/ioniq/state/daily'
        retain: true
        qos: 0
        payload_template: "{{{\"charged_energy_kwh\": states('sensor.car_ioniq_state_today_energy_charged'),\"odometer\": states('sensor.car_ioniq_state_odometer'),\"ced\": states('sensor.car_ioniq_state_ced'),\"cec\": states('sensor.car_ioniq_state_cec'),\"soh\": states('sensor.car_ioniq_state_battery_health'),\"soc_display\":states('sensor.car_ioniq_state_soc_display'),\"soc_bms\":states('sensor.car_ioniq_state_soc_bms'),\"distance_since_cc\": states('sensor.car_ioniq_state_distance_since_cc'),\"timestamp\": as_timestamp(now())|round,} | tojson}}"
