#############################################################
# Nodon Octan automations
#############################################################
- alias: '[System - NodOn Remote] Button 1 pressed'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 10
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 1 apretado'

- alias: '[System - NodOn Remote] Button 1 long press release'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 11
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 1 soltado después de una pulsación larga'

- alias: '[System - NodOn Remote] Button 1 long press'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 12
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 1 pulsación larga'

- alias: '[System - NodOn Remote] Button 1 double click'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 13
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 1 doble pulsación'

- alias: '[System - NodOn Remote] Button 2 pressed'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 20
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 2 apretado'

- alias: '[System - NodOn Remote] Button 2 long press release'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 21
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 2 soltado después de una pulsación larga'

- alias: '[System - NodOn Remote] Button 2 long press'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 22
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 2 pulsación larga'

- alias: '[System - NodOn Remote] Button 2 double click'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 23
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 2 doble pulsación'

- alias: '[System - NodOn Remote] Button 3 pressed'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 30
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 3 apretado'

- alias: '[System - NodOn Remote] Button 3 long press release'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 31
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 3 soltado después de una pulsación larga'

- alias: '[System - NodOn Remote] Button 3 long press'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 32
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 3 pulsación larga'

- alias: '[System - NodOn Remote] Button 3 double click'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 33
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 3 doble pulsación'

- alias: '[System - NodOn Remote] Button 4 pressed'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 40
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 4 apretado'

- alias: '[System - NodOn Remote] Button 1 long press release'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 41
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 4 soltado después de una pulsación larga'

- alias: '[System - NodOn Remote] Button 4 long press'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 42
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 4 pulsación larga'

- alias: '[System - NodOn Remote] Button 4 double click'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.recibidor_remote
      scene_id: 43
  action:
    - service: logbook.log
      data:
        name: 'NodOn'
        message: 'Botón 4 doble pulsación'
