- alias: '[System - Noification] Update Notification'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.telegram
      data_template:
        message: 'Nueva versión {{ states.updater.updater.state }} de Home Assistant disponible.'
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: '#439FE0'
              pretext: ':house_with_garden: *Home-Assistant* :house_with_garden:'
              text: 'Nueva versión {{ states.updater.updater.state }} de Home Assistant disponible.'
              fallback: 'Home-Assistant'
