- alias: '[System] Daily Backup at 3 AM'
  trigger:
    platform: time
    at: '3:00:00'
  action:
  - service: hassio.snapshot_full
    data_template:
      name: '{{ now().strftime("%Y%m%d") }} - Auto'
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'danger'
            pretext: ':floppy_disk: *Copia seguridad* :floppy_disk:'
            text: 'Copia de seguridad \"{{ now().strftime("%Y%m%d") }} - Auto\" creada'
            fallback: 'Copia seguridad'

- alias: '[System] Convert MKV to MP4 to be able to send them through telegram'
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ "mkv" in trigger.event.data.file }}'
      - condition: template
        value_template: '{{ not(is_state("alarm_control_panel.home", "disarmed")) }}'
  action:
    # Delay execution to let the file to be fully loaded in the ftp
    - delay:
        seconds: 15
    - service: shell_command.mp4_convert
      data_template:
        file: '{{ trigger.event.data.path }}'
