presence_geniphone_connected_home_wifi:
  alias: 'Presence - GeniPhone connected home WiFi'
  sequence:
    - service: mqtt.publish
      data:
        payload: 'home'
        retain: true
        topic: 'phone/sensor/geni/wifi'

presence_geniphone_not_connected_home_wifi:
  alias: 'Presence - GeniPhone not connected home WiFi'
  sequence:
    - service: mqtt.publish
      data:
        payload: 'not_home'
        retain: true
        topic: 'phone/sensor/geni/wifi'
