presence_notify_state_change_slack:
  alias: '[Presence - Notification] Notify presence state changes to slack'
  sequence:
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'good'
              pretext: ':bust_in_silhouette: *Presencia* :bust_in_silhouette:'
              text: '{{message}}'
              fallback: 'Presencia'
