- platform: workday
  country: ES
  province: IBA

#- platform: template
#  sensors:
#    piscina_pump:
#      friendly_name: Motor piscina
#      value_template: "{{(as_timestamp(now())|round - as_timestamp(states.sensor.piscina_on_time.state)|round) >= 0 and (as_timestamp(now())|round - as_timestamp(states.sensor.piscina_off_time.state)|round) <= 0}}"
#      device_class: plug

- platform: bayesian
  # Indicates the probability that this is true in a day – let’s say I’m home half the time, or 0.5
  prior: 0.5
  name: 'Jordi Presence'
  # How sure should it be to guess that I’m home? By setting the bar high at 90%, we are requiring more than one platform to be ‘home’ before it will flip to on.
  probability_threshold: 0.95
  observations:
    - entity_id: 'device_tracker.hokusphone_nmap'
      # If I’m home, how likely is this state true? In other words, how reliable is that platform at marking me home?
      prob_given_true: 0.75
      # How likely is this platform to be wrong – for it to be ‘home’ when I’m not home?
      prob_given_false: 0.25
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.hokusphone_wifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.hokusphone_ibeacon'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
