homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 119
  unit_system: metric
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /share/camera
  packages: !include_dir_named packages

http:
# Needed for Torque!
#  api_password: !secret ha_api_password
  base_url: !secret ha_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 3

map:

stream:

person:

system_health:

  # Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Allows you to issue voice commands from the frontend
#conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
discovery:

wemo:
  discovery: true
  static:
    - 10.155.106.21 # Laptop - Wemo switch
    - 10.155.106.31 # Fence - Wemo Maker
    - 10.155.106.70 # Lights - Wemo Link
    - 10.155.106.71 # Car charger - Wemo Insight

# Checks for available updates
updater:
  include_used_components: true

# Enables support for tracking state changes over time.
history:

config:

recorder:
  purge_interval: 1
  purge_keep_days: 30
  db_url: !secret recorder_db_url

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

logger:
  default: warn
  logs:
    openzwave: warn
    libopenzwave: warn
    homeassistant.components.zwave: warn
    homeassistant.components.zwave.util: warn
    homeassistant.components.websocket_api: warn
    homeassistant.components.switch.command_line: warn
    homeassistant.components.sensor.command_line: warn
    homeassistant.components.netatmo.sensor: error
#    homeassistant.components.sensor: debug
#    homeassistant.components.sensor.torque: debug
#    homeassistant.components.camera: debug
#    homeassistant.components.shell_command: debug
#    homeassistant.components.dialogflow: debug
#    homeassistant.components.telegram_bot: debug
#    homeassistant.helpers.intent: debug
#    homeassistant.components.intent_script: debug
#    homeassistant.helpers.script: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.device_tracker.luci: debug
#    homeassistant.core: debug
#    homeassistant.components.sensor.speedtest: debug
#    homeassistant.core: debug
#    homeassistant.components.wemo: debug
#    pywemo: debug

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  parse_mode: html
  allowed_chat_ids:
    - !secret hokusphone_telegram_chat_id
    - !secret hokuscar_telegram_chat_id
    - !secret geniphone_telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret hokusphone_telegram_chat_id

  - name: slack
    platform: slack
    api_key: !secret slack_token
    default_channel: '#general'
#    icon: ':house_with_garden:'

ifttt:
  key: !secret ifttt_api_key

hacs:
  token: !secret hacs_token

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: true
  webhooks: true

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

cloud:
  google_actions:
    entity_config:
      script.goto_sleep:
        name: Me voy a la cama
        aliases:
          - Me voy a la cama
          - A dormir
          - Me voy a dormir
        room: General
      script.chores:
        name: Basura
        aliases:
          - Basura
        room: General
      script.speech_parte_meteorologico_corto:
        name: Parte meteorológico corto
        aliases:
          - Parte meteorológico corto
        room: General
      script.speech_parte_meteorologico:
        name: Parte meteorológico
        aliases:
          - Parte meteorológico
        room: General
      script.geni_shift:
        name: Turno Geni
        aliases:
          - Turno Geni
        room: General
      script.google_home_good_morning:
        name: Buenos días
        aliases:
          - Buenos días
        room: General

#google_assistant:
#  project_id: !secret google_assistant_project_id
#  api_key: !secret google_api_key
#  expose_by_default: false
#  entity_config:
#    script.goto_sleep:
#      name: Me voy a la cama
#      expose: true
#      room: General

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

zwave:
  usb_path: /dev/ttyACM0
  device_config_glob:
    "*_burglar*":
      ignored: true
      polling_intensity: 0
    "*_alarm_type":
      ignored: true
      polling_intensity: 0
    "*_alarm_level":
      ignored: true
      polling_intensity: 0
    "*_sourcenodeid":
      ignored: true
    "sensor.*_exporting*":
      ignored: true
    "sensor.*_heat":
      ignored: true
    "sensor.*_power_management":
      ignored: true
    "sensor.*_general":
      ignored: true
tts:
  - platform: google_translate
#    cache: true
#    cache_dir: /tmp/tts
#    time_memory: 300
    language: 'es'

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
#automation: !include automations.yaml
#automation: !include_dir_list automations
automation: !include_dir_merge_list automations
script: !include scripts.yaml
panel_iframe: !include panel_iframes.yaml
