homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 119
  unit_system: metric
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/camera
  packages: !include_dir_named packages

http:
  api_password: !secret ha_api_password
#  trusted_networks:
#    - 127.0.0.1
  base_url: !secret ha_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 3
#  ssl_certificate: !secret ha_ssl_certificate
#  ssl_key: !secret ha_ssl_key
  #server_port: 8123
  #development: 1

map:

  # Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
#conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - belkin_wemo

# Checks for available updates
updater:
  include_used_components: true

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - camera

config:

wemo:
  static:
    # Maker
    - 10.155.106.110
    # Switch
#    - 10.155.106.111
    # Link
    - 10.155.106.112

media_player:
    # TV
  - platform: cast
    host: 10.155.106.114
    # Home-Assistant
  - platform: cast
    host: 10.155.106.143

recorder:
  purge_interval: 1
  purge_keep_days: 30
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - script
      - zone
      - group
      - calendar
      - zwave
      - updater
      - media_player
    entities:
      - sensor.since_last_boot
      - sensor.last_boot

      - sensor.nut_ups_manufacturer
      - sensor.nut_ups_model
      - sensor.nut_ups_status_data
      - sensor.nut_ups_beeper_status
      - sensor.nut_ups_battery_runtime
      - sensor.nut_ups_battery_charge

      - sun.sun
      - sensor.date
      - sensor.time
      - sensor.date__time
      - sensor.sunrise
      - sensor.sunset

      - sensor.ha_runtime_in_minutes

      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_alarm_level
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_alarm_type
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_exporting
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_exporting_2
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_heat
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_interval
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_management
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_previous_reading
      - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_sourcenodeid
      - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
      - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2

      - binary_sensor.workday_sensor
      - image_processing.sevensegement_ocr_ph_piscina

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

logger:
  default: warn
  logs:
    openzwave: warn
    libopenzwave: warn
    homeassistant.components.zwave: warn
    homeassistant.components.zwave.util: warn
    homeassistant.components.websocket_api: warn
    homeassistant.components.switch.command_line: warn
    homeassistant.components.sensor.command_line: warn
#    homeassistant.components.shell_command: debug
#    homeassistant.components.dialogflow: debug
#    homeassistant.components.telegram_bot: debug
#    homeassistant.components.dialogflow: debug
#    homeassistant.helpers.intent: debug
#    homeassistant.components.intent_script: debug
#    homeassistant.helpers.script: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.device_tracker: info
#    homeassistant.core: debug
#    homeassistant.components.sensor.speedtest: debug
#    homeassistant.core: debug

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret hokusphone_telegram_chat_id
    - !secret hokuscar_telegram_chat_id
    - !secret geniphone_telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret hokusphone_telegram_chat_id

#  - name: HTML5
#    platform: html5
#    gcm_api_key: !secret gcm_api_key
#    gcm_sender_id: !secret gcm_sender_id

#  - platform: pushbullet
#    name: pushbullet
#    api_key: !secret pushbullet_api_key

ifttt:
  key: !secret ifttt_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: true

#foursquare:
#  access_token: !secret foursquare_access_token
#  push_secret: !secret foursquare_push_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_api_key
  expose_by_default: true
  entity_config:
    switch.recibidor_camara_det_mov:
      name: Detección movimento recibidor
      aliases:
        - detección de movimiento del recibidor
        - deteccion de movimiento del recibidor
        - detección movimiento recibidor
        - deteccion movimiento recibidor
        - detector de movimiento del recibidor
        - detector movimiento recibidor
        - detector de movimiento recibidor
        - detector movimiento del recibidor
        - detección de movimento recibidor
        - deteccion de movimiento recibidor
        - detección movimiento del recibidor
        - deteccion movimiento del recibidor
      room: Recibidor

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'es'

freedns:
  access_token: !secret freedns_token

#climate:
#  - platform: netatmo

shell_command: !include shell_command.yaml
zone: !include zones.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
#automation: !include_dir_merge_list automation
script: !include scripts.yaml
input_number: !include input_sliders.yaml
panel_iframe: !include panel_iframes.yaml
#panel_custom: !include panel_custom.yaml
#image_processing: !include image_processing.yaml
#scene: !include scenes.yaml
