###################################
# Sensors
###################################
sensor.speedtest_ping:
  friendly_name: 'Ping'
  icon: mdi:lan-connect
sensor.speedtest_download:
  friendly_name: 'Descarga'
  icon: mdi:cloud-download
sensor.speedtest_upload:
  friendly_name: 'Subida'
  icon: mdi:cloud-upload
#sensor.energy_usage:
#  friendly_name: 'Consumo'
#  icon: 'mdi:speedometer'
sensor.efergy_2577:
  friendly_name: 'Consumo'
  icon: 'mdi:speedometer'
sensor.exchange_rate_1_btc:
  friendly_name: 'Bitcoin'
  icon: 'mdi:currency-btc'
sensor.exchange_rate_1_eth:
  friendly_name: 'Ethereum'
  icon: 'mdi:currency-eth'
#sensor.hokusphone_batt:
#  friendly_name: 'Batería teléfono'
#  icon: 'mdi:battery'
sensor.switch_barrera:
  friendly_name: 'Estado barrera'
  icon: 'mdi:gate'
sensor.ups_status:
  friendly_name: 'SAI'
  icon: 'mdi:power-socket-eu'
sensor.sunset:
  icon: mdi:weather-sunset-down
sensor.sunrise:
  icon: mdi:weather-sunset-up
sensor.ink_level_magenta:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_magenta.png
sensor.ink_level_cyan:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_cyan.png
sensor.ink_level_yellow:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_yellow.png
sensor.ink_level_black:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_black.png
sensor.hp_photosmart_5520:
  entity_picture: /local/printer_icon.png
sensor.processor_use:
  friendly_name: 'Uso CPU'
sensor.memory_free:
  friendly_name: 'RAM libre'
  icon: mdi:chip
sensor.disk_free_:
  friendly_name: 'Espacio libre'
sensor.last_boot:
  friendly_name: 'Último reinicio'
sensor.since_last_boot:
  friendly_name: 'Uptime'
sensor.nut_ups_manufacturer:
  friendly_name: 'Marca'
sensor.nut_ups_model:
  friendly_name: 'Modelo'
sensor.nut_ups_battery_charge:
  friendly_name: 'Carga'
sensor.nut_ups_battery_runtime:
  friendly_name: 'Tiempo restante'
sensor.recibidor_boton_bateria:
  device_class: 'battery'
  friendly_name: 'Nodon'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy:
  icon: 'mdi:speedometer'
  friendly_name: 'Consumo luz escalera'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power:
  icon: 'mdi:power-plug'
  friendly_name: 'Potencia luz escalera'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy_2:
  icon: 'mdi:speedometer'
  friendly_name: 'Consumo luz suite'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_2:
  icon: 'mdi:power-plug'
  friendly_name: 'Potencia luz suite'
sensor.caducidad_certificado_ssl:
  unit_of_measurement: días
sensor.connected_clients:
  friendly_name: 'Clientes conectados'
  unit_of_measurement: 'cliente(s)'
  icon: 'mdi:account'
sensor.ha_runtime_in_minutes:
  friendly_name: 'Tiempo ejecución HA'
  unit_of_measurement: 'mins'
###################################
# Binary Sensors
###################################
binary_sensor.ups_status_bs:
  friendly_name: 'Suministro eléctrico'

###################################
# Switches
###################################
switch.barrera:
  friendly_name: 'Barrera'
  icon: mdi:gate
switch.ups_beeper:
  friendly_name: 'Pitido'
  icon: mdi:music-note
switch.swiid_swiidinter_lampara_recibidor_switch:
  friendly_name: 'Lámpara recibidor'
  icon: mdi:lamp
switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch:
  friendly_name: 'Luz escalera'
  icon: mdi:ceiling-light
switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2:
  friendly_name: 'Luz suite'
  icon: mdi:ceiling-light

###################################
# Input sliders
###################################
input_number.entrada_luz_brillo:
  icon: mdi:brightness-6
###################################
# Scripts
###################################
script.turn_off_lights_exterior:
  hidden: true
script.restart_ha:
  icon: mdi:autorenew
script.reboot_pi:
  icon: mdi:power
###################################
# Scenes
###################################
#scene.empty_home:
#  hidden: true
#scene.someone_home:
#  hidden: true
###################################
# Groups
###################################
group.external_lights_group:
  hidden: true
###################################
# Other
###################################
sun.sun:
  friendly_name: 'Sol'
media_player.hokussqueezebox:
  friendly_name: 'Squeezebox suite'
media_player.salon:
  friendly_name: 'Chromecast Salón'
