###################################
# Sensors
###################################
sensor.speedtest_ping:
  friendly_name: 'Ping'
  icon: mdi:lan-connect
sensor.speedtest_download:
  friendly_name: 'Descarga'
  icon: mdi:cloud-download
sensor.speedtest_upload:
  friendly_name: 'Subida'
  icon: mdi:cloud-upload
#sensor.energy_usage:
#  friendly_name: 'Consumo'
#  icon: 'mdi:speedometer'
sensor.exchange_rate_1_btc:
  friendly_name: 'Bitcoin'
  icon: 'mdi:currency-btc'
sensor.exchange_rate_1_eth:
  friendly_name: 'Ethereum'
  icon: 'mdi:currency-eth'
#sensor.hokusphone_batt:
#  friendly_name: 'Batería teléfono'
#  icon: 'mdi:battery'
sensor.sunset:
  icon: mdi:weather-sunset-down
sensor.sunrise:
  icon: mdi:weather-sunset-up
sensor.ink_level_magenta:
  friendly_name: 'Magenta'
  entity_picture: /local/printer_ink_magenta.png
sensor.ink_level_cyan:
  friendly_name: 'Cyan'
  entity_picture: /local/printer_ink_cyan.png
sensor.ink_level_yellow:
  friendly_name: 'Amarillo'
  entity_picture: /local/printer_ink_yellow.png
sensor.ink_level_black:
  friendly_name: 'Negro'
  entity_picture: /local/printer_ink_black.png
sensor.hp_photosmart_5520:
  entity_picture: /local/printer_icon.png
sensor.processor_use:
  friendly_name: 'Uso CPU'
sensor.memory_free:
  friendly_name: 'RAM libre'
  icon: mdi:chip
sensor.disk_free:
  friendly_name: 'Espacio libre'
sensor.last_boot:
  friendly_name: 'Último reinicio'
sensor.since_last_boot:
  friendly_name: 'Uptime'
sensor.recibidor_boton_bateria:
  device_class: 'battery'
  friendly_name: 'Nodon'
sensor.caducidad_certificado_ssl:
  unit_of_measurement: días
sensor.dominio_principal:
  unit_of_measurement: días
sensor.dominio_nena:
  unit_of_measurement: días
sensor.connected_clients:
  friendly_name: 'Clientes conectados'
  unit_of_measurement: 'cliente(s)'
  icon: 'mdi:account'
sensor.ha_runtime_in_minutes:
  friendly_name: 'Tiempo ejecución HA'
  unit_of_measurement: 'mins'
sensor.google_wifi_current_version:
  friendly_name: 'Versión Google WiFi'
sensor.google_wifi_last_restart:
  friendly_name: 'Reinicio Google WiFi'
sensor.google_wifi_new_version:
  friendly_name: 'Nueva versión Google WiFi'
sensor.google_wifi_status:
  friendly_name: 'Estado Google WiFi'
sensor.google_wifi_uptime:
  friendly_name: 'Uptime Google WiFi'
  unit_of_measurement: 'días'
sensor.db_size:
  friendly_name: 'Tamaño BD'
  icon: mdi:database
###################################
# Scripts
###################################
script.restart_ha:
  icon: mdi:autorenew
script.reboot_pi:
  icon: mdi:power
###################################
# Scenes
###################################
#scene.empty_home:
#  hidden: true
#scene.someone_home:
#  hidden: true
###################################
# Other
###################################
sun.sun:
  friendly_name: 'Sol'
media_player.hokussqueezebox:
  friendly_name: 'Squeezebox suite'
media_player.salon:
  friendly_name: 'Chromecast Salón'
