###################################
# Sensors
###################################
sensor.netatmo_exterior_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_exterior_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_exterior_min_temp:
  friendly_name: 'Mínima de hoy'
sensor.netatmo_exterior_max_temp:
  friendly_name: 'Máxima de hoy'
sensor.netatmo_exterior_battery:
  friendly_name: 'Netatmo exterior'
  device_class: 'battery'
sensor.netatmo_exterior_radio:
  friendly_name: 'Señal exterior'
sensor.netatmo_pluviometro_rain:
  friendly_name: 'Previsión lluvia'
sensor.netatmo_pluviometro_sum_rain_1:
  friendly_name: 'Lluvia última hora'
sensor.netatmo_pluviometro_sum_rain_24:
  friendly_name: 'Lluvia 24 horas'
sensor.netatmo_pluviometro_battery:
  friendly_name: 'Netatmo pluviómetro'
  device_class: 'battery'
sensor.netatmo_pluviometro_radio:
  friendly_name: 'Señal pluviómetro'
sensor.netatmo_salon_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_salon_min_temp:
  friendly_name: 'Mínima de hoy'
sensor.netatmo_salon_max_temp:
  friendly_name: 'Máxima de hoy'
sensor.netatmo_salon_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_salon_noise:
  friendly_name: 'Nivel de ruido'
sensor.netatmo_salon_pressure:
  friendly_name: 'Presión atmosférica'
sensor.netatmo_salon_co2:
  friendly_name: 'Nivel CO2'
sensor.netatmo_salon_wifi:
  friendly_name: 'Señal Wifi Netatmo'
sensor.netatmo_anemometro_angle:
  friendly_name: 'Dirección viento'
sensor.netatmo_anemometro_battery:
  friendly_name: 'Netatmo anemómetro'
  device_class: 'battery'
sensor.netatmo_anemometro_gust_angle:
  friendly_name: 'Dirección rachas'
sensor.netatmo_anemometro_gust_strength:
  friendly_name: 'Velocidad rachas'
sensor.netatmo_anemometro_radio:
  friendly_name: 'Señal anemómetro'
sensor.netatmo_anemometro_strength:
  friendly_name: 'Velocidad viento'
sensor.netatmo_suite_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_suite_min_temp:
  friendly_name: 'Mínima de hoy'
sensor.netatmo_suite_max_temp:
  friendly_name: 'Máxima de hoy'
sensor.netatmo_suite_co2:
  friendly_name: 'Nivel CO2'
sensor.netatmo_suite_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_suite_battery:
  friendly_name: 'Netatmo suite'
  device_class: 'battery'
sensor.netatmo_suite_radio:
  friendly_name: 'Señal suite'
sensor.netatmo_habitacion_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_habitacion_min_temp:
  friendly_name: 'Mínima de hoy'
sensor.netatmo_habitacion_max_temp:
  friendly_name: 'Máxima de hoy'
sensor.netatmo_habitacion_co2:
  friendly_name: 'Nivel CO2'
sensor.netatmo_habitacion_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_habitacion_battery:
  friendly_name: 'Netatmo hab. niños'
  device_class: 'battery'
sensor.netatmo_habitacion_radio:
  friendly_name: 'Señal hab.niños'
sensor.speedtest_ping:
  friendly_name: 'Ping'
  icon: mdi:lan-connect
sensor.speedtest_download:
  friendly_name: 'Descarga'
  icon: mdi:cloud-download
sensor.speedtest_upload:
  friendly_name: 'Subida'
  icon: mdi:cloud-upload
#sensor.energy_usage:
#  friendly_name: 'Consumo'
#  icon: 'mdi:speedometer'
sensor.efergy_2577:
  friendly_name: 'Consumo'
  icon: 'mdi:speedometer'
sensor.exchange_rate_1_btc:
  friendly_name: 'Bitcoin'
  icon: 'mdi:currency-btc'
sensor.exchange_rate_1_eth:
  friendly_name: 'Ethereum'
  icon: 'mdi:currency-eth'
#sensor.hokusphone_batt:
#  friendly_name: 'Batería teléfono'
#  icon: 'mdi:battery'
sensor.switch_barrera:
  friendly_name: 'Estado barrera'
  icon: 'mdi:gate'
sensor.season:
  friendly_name: 'Estación'
sensor.ups_status:
  friendly_name: 'SAI'
  icon: 'mdi:power-socket-eu'
sensor.toyota_batt:
  friendly_name: 'Batería'
  device_class: 'battery'
sensor.toyota_gps_accuracy:
  friendly_name: 'Precisión GPS'
  icon: 'mdi:map-marker-radius'
sensor.toyota_last_update:
  friendly_name: 'Última actualización'
  icon: 'mdi:clock'
sensor.nissan_batt:
  friendly_name: 'Batería'
  device_class: 'battery'
sensor.nissan_gps_accuracy:
  friendly_name: 'Precisión GPS'
  icon: 'mdi:map-marker-radius'
sensor.nissan_last_update:
  friendly_name: 'Última actualización'
  icon: 'mdi:clock'
sensor.sunset:
  icon: mdi:weather-sunset-down
sensor.sunrise:
  icon: mdi:weather-sunset-up
sensor.ink_level_magenta:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_magenta.png
sensor.ink_level_cyan:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_cyan.png
sensor.ink_level_yellow:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_yellow.png
sensor.ink_level_black:
  friendly_name: 'Nivel tinta'
  entity_picture: /local/printer_ink_black.png
sensor.hp_photosmart_5520:
  entity_picture: /local/printer_icon.png

sensor.cpu_use:
  friendly_name: 'Uso CPU'
sensor.ram_free:
  friendly_name: 'RAM libre'
  icon: mdi:chip
sensor.disk_free_:
  friendly_name: 'Espacio libre'
sensor.last_boot:
  friendly_name: 'Último reinicio'
sensor.since_last_boot:
  friendly_name: 'Uptime'
sensor.cocina_sensor_puerta:
#  icon: 'mdi:glassdoor'
  friendly_name: 'Estado puerta porche'
sensor.cocina_sensor_puerta_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor puerta cocina'
sensor.cocina_sensor_persiana:
#  icon: 'mdi:glassdoor'
  friendly_name: 'Estado persiana porche'
sensor.cocina_sensor_persiana_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor persiana cocina'
sensor.coladuria_sensor_puerta:
#  icon: 'mdi:glassdoor'
  friendly_name: 'Estado puerta coladuria'
sensor.coladuria_sensor_puerta_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor puerta coladuria'
sensor.piscina_sensor_piscina_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor temp. piscina'
sensor.nut_ups_manufacturer:
  friendly_name: 'Marca'
sensor.nut_ups_model:
  friendly_name: 'Modelo'
sensor.nut_ups_battery_charge:
  friendly_name: 'Carga'
sensor.nut_ups_battery_runtime:
  friendly_name: 'Tiempo restante'
sensor.salon_sensor_movimiento_luminance:
  icon: 'mdi:weather-sunny'
  friendly_name: 'Luminosidad'
sensor.salon_sensor_movimiento_bateria:
  device_class: 'battery'
  friendly_name: 'Detector movimiento salón'
sensor.recibidor_boton_bateria:
  device_class: 'battery'
  friendly_name: 'Nodon'
sensor.salon_sensor_movimiento_temperature:
  friendly_name: 'Temperatura'
sensor.recibidor_termometro_temperatura:
  friendly_name: 'Temperatura'
  unit_of_measurement: '°C'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy:
  icon: 'mdi:speedometer'
  friendly_name: 'Consumo luz escalera'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power:
  icon: 'mdi:power-plug'
  friendly_name: 'Potencia luz escalera'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy_2:
  icon: 'mdi:speedometer'
  friendly_name: 'Consumo luz suite'
sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_2:
  icon: 'mdi:power-plug'
  friendly_name: 'Potencia luz suite'
sensor.next_holiday_mode_start:
  icon: mdi:airplane-takeoff
sensor.next_holiday_mode_end:
  icon: mdi:airplane-landing
sensor.next_shift_event:
  icon: mdi:message
sensor.next_shift_date:
  icon: mdi:calendar
sensor.piscina_on_history:
  friendly_name: 'Uso bomba hoy'
sensor.switch_piscina_current_power_w:
  icon: mdi:speedometer
sensor.switch_piscina_today_energy_kwh:
  icon: mdi:calendar-today
sensor.caducidad_certificado_ssl:
  unit_of_measurement: días
sensor.connected_clients:
  friendly_name: 'Clientes conectados'
  unit_of_measurement: 'cliente(s)'
  icon: 'mdi:account'
sensor.temperature_ground_floor:
  friendly_name: 'Temp media planta baja'
  icon: 'mdi:thermometer'
  unit_of_measurement: '°C'
sensor.temperature_first_floor:
  friendly_name: 'Temp media 1ª planta'
  icon: 'mdi:thermometer'
  unit_of_measurement: '°C'
sensor.fibaro_fgk10x_door_opening_sensor_piscina_temperature:
  friendly_name: 'Temp. agua'
sensor.piscina_temperature_mean:
  friendly_name: 'Temp. media agua'
sensor.ha_runtime_in_minutes:
  friendly_name: 'Tiempo ejecución HA'
  unit_of_measurement: 'mins'
###################################
# Binary Sensors
###################################
binary_sensor.recibidor_camara_infrarrojo:
  friendly_name: 'Infrarrojos recibidor'
  icon: 'mdi:led-on'
binary_sensor.piscina_camara_infrarrojo:
  friendly_name: 'Infrarrojos piscina'
  icon: 'mdi:led-on'
binary_sensor.barbacoa_camara_infrarrojo:
  friendly_name: 'Infrarrojos barbacoa'
  icon: 'mdi:led-on'
binary_sensor.caseta_camara_infrarrojo:
  friendly_name: 'Infrarrojos caseta'
  icon: 'mdi:led-on'
binary_sensor.ups_status_bs:
  friendly_name: 'Suministro eléctrico'
binary_sensor.piscina_camara_det_mov:
  friendly_name: 'Movimiento piscina'
binary_sensor.recibidor_camara_det_mov:
  friendly_name: 'Movimiento recibidor'
binary_sensor.barbacoa_camara_det_mov:
  friendly_name: 'Movimiento barbacoa'
binary_sensor.caseta_camara_det_mov:
  friendly_name: 'Movimiento caseta'
binary_sensor.salon_sensor_movimiento:
  friendly_name: 'Movimiento salón'
  device_class: 'motion'
binary_sensor.salon_sensor_movimiento_sabotaje:
  friendly_name: 'Manipulación sensor'
binary_sensor.entrada_principal_outdoor_motion:
  friendly_name: 'Movimiento desconocido'
binary_sensor.entrada_principal_outdoor_human:
  friendly_name: 'Persona detectada'
binary_sensor.entrada_principal_outdoor_animal:
  friendly_name: 'Animal detectado'
  icon: 'mdi:paw'
binary_sensor.entrada_principal_outdoor_vehicle:
  friendly_name: 'Vehiculo detectado'
  icon: 'mdi:car'
binary_sensor.porche_sensor_puerta:
  device_class: 'door'
  friendly_name: 'Puerta porche'
binary_sensor.porche_sensor_persiana:
  device_class: 'door'
  friendly_name: 'Persiana porche'
binary_sensor.coladuria_sensor_puerta:
  device_class: 'door'
  friendly_name: 'Puerta coladuría'

###################################
# Cameras
###################################
camera.recibidor:
  friendly_name: 'Recibidor'
camera.piscina:
  friendly_name: 'Piscina'
camera.barbacoa:
  friendly_name: 'Barbacoa'
camera.caseta:
  friendly_name: 'Caseta'
###################################
# Switches
###################################
switch.recibidor_camara_det_mov:
  friendly_name: 'Det. mov. recibidor'
  icon: 'mdi:transit-transfer'
switch.piscina_camara_det_mov:
  friendly_name: 'Det. mov. piscina'
  icon: 'mdi:transit-transfer'
switch.barbacoa_camara_det_mov:
  friendly_name: 'Det. mov. barbacoa'
  icon: 'mdi:transit-transfer'
switch.caseta_camara_det_mov:
  friendly_name: 'Det. mov. caseta'
  icon: 'mdi:transit-transfer'
switch.motor_piscina:
  friendly_name: 'Depuradora'
  icon: mdi:pool
switch.barrera:
  friendly_name: 'Barrera'
  icon: mdi:gate
switch.holiday:
  friendly_name: 'Vacaciones'
  icon: mdi:airplane
switch.termostato:
  friendly_name: 'Calefacción'
  icon: mdi:radiator
switch.termostato_modo_ausente:
  friendly_name: 'Modo ausente'
  icon: mdi:home-outline
switch.ups_beeper:
  friendly_name: 'Pitido'
  icon: mdi:music-note
switch.swiid_swiidinter_lampara_recibidor_switch:
  friendly_name: 'Lámpara recibidor'
  icon: mdi:lamp
switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch:
  friendly_name: 'Luz escalera'
  icon: mdi:ceiling-light
switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2:
  friendly_name: 'Luz suite'
  icon: mdi:ceiling-light
sensor.porche_sensor_puerta_temperature:
  friendly_name: 'Temperatura'
  icon: mdi:thermometer

###################################
# Input sliders
###################################
input_number.empty_home_activation_delay_minutes:
  icon: mdi:clock-end
input_number.entrada_luz_brillo:
  icon: mdi:brightness-6
###################################
# Scripts
###################################
script.turn_off_lights_exterior:
  hidden: true
script.turn_on_swimmingpool_1_hour:
  hidden: true
script.turn_on_swimmingpool_2_hours:
  hidden: true
script.turn_on_swimmingpool_3_hours:
  hidden: true
script.check_caseta_motion_detection:
  hidden: true
script.restart_ha:
  icon: mdi:autorenew
script.reboot_pi:
  icon: mdi:power
###################################
# Scenes
###################################
#scene.empty_home:
#  hidden: true
#scene.someone_home:
#  hidden: true
###################################
# Groups
###################################
group.external_lights_group:
  hidden: true
###################################
# Other
###################################
sun.sun:
  friendly_name: 'Sol'
media_player.hokussqueezebox:
  friendly_name: 'Squeezebox suite'
media_player.salon:
  friendly_name: 'Chromecast Salón'
