sensor.speedtest_ping:
  friendly_name: Ping
  icon: mdi:lan-connect
sensor.speedtest_download:
  friendly_name: Descarga
  icon: mdi:cloud-download
sensor.speedtest_upload:
  friendly_name: Subida
  icon: mdi:cloud-upload
sensor.exchange_rate_1_btc:
  friendly_name: Bitcoin
  icon: mdi:bitcoin
sensor.exchange_rate_1_eth:
  friendly_name: Ethereum
  icon: mdi:ethereum
sensor.sunset:
  icon: mdi:weather-sunset-down
sensor.sunrise:
  icon: mdi:weather-sunset-up
sensor.ink_level_magenta:
  friendly_name: Magenta
  entity_picture: /local/printer_ink_magenta.png
sensor.ink_level_cyan:
  friendly_name: Cyan
  entity_picture: /local/printer_ink_cyan.png
sensor.ink_level_yellow:
  friendly_name: Amarillo
  entity_picture: /local/printer_ink_yellow.png
sensor.ink_level_black:
  friendly_name: Negro
  entity_picture: /local/printer_ink_black.png
sensor.hp_photosmart_5520:
  entity_picture: /local/printer_icon.png
sensor.processor_use:
  friendly_name: Uso CPU
sensor.memory_free:
  friendly_name: RAM libre
  icon: mdi:chip
sensor.disk_free:
  friendly_name: Espacio libre
sensor.last_boot:
  friendly_name: Último reinicio
sensor.since_last_boot:
  friendly_name: Uptime
sensor.recibidor_boton_bateria:
  device_class: battery
  friendly_name: Nodon
sensor.caducidad_certificado_ssl:
  unit_of_measurement: días
sensor.dominio_principal:
  unit_of_measurement: días
sensor.dominio_nena:
  unit_of_measurement: días
sensor.connected_clients:
  friendly_name: Clientes conectados
  unit_of_measurement: cliente(s)
  icon: mdi:account
sensor.ha_runtime_in_minutes:
  friendly_name: Tiempo ejecución HA
  unit_of_measurement: mins
sensor.google_wifi_current_version:
  friendly_name: Versión Google WiFi
sensor.google_wifi_last_restart:
  friendly_name: Reinicio Google WiFi
sensor.google_wifi_new_version:
  friendly_name: Nueva versión Google WiFi
sensor.google_wifi_status:
  friendly_name: Estado Google WiFi
sensor.google_wifi_uptime:
  friendly_name: Uptime Google WiFi
  unit_of_measurement: días
sensor.db_size:
  friendly_name: Tamaño BD
  icon: mdi:database
script.restart_ha:
  icon: mdi:autorenew
script.reboot_pi:
  icon: mdi:power
sun.sun:
  friendly_name: Sol
media_player.hokussqueezebox:
  friendly_name: Squeezebox suite
media_player.salon:
  friendly_name: Chromecast Salón
sensor.ground_floor_temperature:
  device_class: temperature
  friendly_name: Temp media planta baja
  icon: mdi:thermometer
sensor.next_holiday_mode_start:
  icon: mdi:airplane-takeoff
sensor.next_holiday_mode_end:
  icon: mdi:airplane-landing
sensor.next_shift_event:
  icon: mdi:message
sensor.next_shift_date:
  icon: mdi:calendar
switch.holiday:
  friendly_name: 'Vacaciones'
  icon: mdi:airplane
input_number.empty_home_activation_delay_minutes:
  icon: mdi:clock-end
device_tracker.geniphone_wifi:
  source_type: router
device_tracker.hokusphone_wifi:
  source_type: router
device_tracker.guest:
  source_type: router
person.jordi:
  entity_picture: 'https://s.gravatar.com/avatar/f5d192b4f4ffab4d9625f9b9e11d16b7?s=192'
person.geni:
  entity_picture: '/local/person.geni.jpg'
person.guest:
  entity_picture: '/local/person.guest.png'
sensor.escalera_switch_energy:
  icon: 'mdi:speedometer'
  friendly_name: 'Consumo luz escalera'
sensor.escalera_switch_power:
  icon: 'mdi:power-plug'
  friendly_name: 'Potencia luz escalera'
sensor.suite_switch_energy:
  icon: 'mdi:speedometer'
  friendly_name: 'Consumo luz suite'
sensor.suite_switch_power:
  icon: 'mdi:power-plug'
  friendly_name: 'Potencia luz suite'
light.escalera_light:
  friendly_name: 'Escalera'
  icon: mdi:ceiling-light
light.suite_light:
  friendly_name: 'Suite'
  icon: mdi:ceiling-light
light.salon_light:
  friendly_name: 'Salón'
  icon: mdi:ceiling-light
light.comedor_light:
  friendly_name: 'Comedor'
  icon: mdi:ceiling-light
light.entrance_hall_lamp_light:
  friendly_name: 'Lámpara recibidor'
  icon: mdi:lamp
script.turn_off_lights_exterior:
  hidden: true
sensor.outside_fence:
  friendly_name: 'Estado barrera'
sensor.efergy_2577:
  friendly_name: 'Consumo instantáneo'
  icon: 'mdi:speedometer'
sensor.energy_ups_status:
  friendly_name: 'SAI'
  icon: 'mdi:power-socket-eu'
sensor.nut_ups_manufacturer:
  friendly_name: 'Marca'
sensor.nut_ups_model:
  friendly_name: 'Modelo'
sensor.nut_ups_battery_charge:
  friendly_name: 'Carga'
sensor.nut_ups_battery_runtime:
  friendly_name: 'Tiempo restante'
sensor.energy_home_daily_pico:
  friendly_name: 'Consumo diario (pico)'
sensor.energy_home_daily_valle:
  friendly_name: 'Consumo diario (valle)'
sensor.energy_home_daily_super_valle:
  friendly_name: 'Consumo diario (super valle)'
sensor.energy_home_monthly_pico:
  friendly_name: 'Consumo mensual (pico)'
sensor.energy_home_monthly_valle:
  friendly_name: 'Consumo mensual (valle)'
sensor.energy_home_monthly_super_valle:
  friendly_name: 'Consumo mensual (super valle)'
binary_sensor.energy_ups_status_bs:
  friendly_name: 'Suministro eléctrico'
switch.energy_ups_beeper:
  friendly_name: 'Pitido'
  icon: mdi:music-note
utility_meter.energy_home_daily:
  friendly_name: 'Tarifa'
sensor.car_ioniq_location:
  friendly_name: 'Última actualización'
  #icon: 'mdi:clock'
  entity_picture: '/local/ioniq-icon.png'
sensor.car_ioniq_charge_state:
  friendly_name: 'Estado carga'
  icon: 'mdi:flash-circle'
sensor.car_ioniq_state_today_energy_charged:
  friendly_name: 'Energía cargada hoy'
  icon: 'mdi:battery-charging-70'
sensor.car_al_colegio:
  friendly_name: 'Al colegio'
sensor.car_a_la_oficina:
  friendly_name: 'A la oficina'
sensor.car_ioniq_charger_current_power:
  friendly_name: 'Potencia carga'
  icon: 'mdi:speedometer'
sensor.car_ioniq_charger_yearly_pico:
  friendly_name: 'Consumo anual (pico)'
  icon: 'mdi:trending-up'
sensor.car_ioniq_charger_yearly_valle:
  friendly_name: 'Consumo anual (valle)'
  icon: 'mdi:trending-down'
  unit_of_measurement: kWh
sensor.car_ioniq_charger_yearly_super_valle:
  friendly_name: 'Consumo anual (super valle)'
  icon: 'mdi:trending-down'
  unit_of_measurement: kWh
sensor.car_ioniq_charger_monthly_pico:
  friendly_name: 'Consumo mensual (pico)'
  icon: 'mdi:trending-up'
sensor.car_ioniq_charger_monthly_valle:
  friendly_name: 'Consumo mensual (valle)'
  icon: 'mdi:trending-down'
sensor.car_ioniq_charger_monthly_super_valle:
  friendly_name: 'Consumo mensual (super valle)'
  icon: 'mdi:trending-down'
sensor.car_ioniq_charger_daily_pico:
  friendly_name: 'Consumo diario (pico)'
  icon: 'mdi:trending-up'
sensor.car_ioniq_charger_daily_valle:
  friendly_name: 'Consumo diario (valle)'
  icon: 'mdi:trending-down'
sensor.car_ioniq_charger_daily_super_valle:
  friendly_name: 'Consumo diario (super valle)'
  icon: 'mdi:trending-down'
binary_sensor.car_ioniq_state:
  friendly_name: 'Estado'
camera.car_ioniq:
  friendly_name: 'Ioniq'
switch.car_ioniq_charger:
  friendly_name: 'Cargador'
  icon: 'mdi:ev-station'
device_tracker.car_ioniq:
  entity_picture: /local/ioniq-icon.png
alarm_control_panel.home:
   friendly_name: 'Alarma'
sensor.piscina_on_history:
  friendly_name: 'Uso bomba hoy'
sensor.piscina_water_temperature:
  friendly_name: 'Temperatura agua'
  icon: 'mdi:oil-temperature'
sensor.piscina_temperature:
  friendly_name: 'Temp. media agua'
sensor.piscina_filtered_realistic_water_temperature:
  friendly_name: 'Temp. realista agua'
switch.motor_piscina:
  friendly_name: 'Depuradora'
switch.luz_piscina:
  friendly_name: 'Luz'
light.piscina_light:
  friendly_name: 'Luz piscina'
###################################
# Hall camera customization
###################################
camera.recibidor:
  friendly_name: 'Recibidor'
binary_sensor.recibidor_camara_infrarrojo:
  friendly_name: 'Infrarrojos recibidor'
  icon: 'mdi:led-on'
binary_sensor.recibidor_camara_det_mov:
  friendly_name: 'Movimiento recibidor'
switch.recibidor_camara_det_mov:
  friendly_name: 'Det. mov. recibidor'
  icon: 'mdi:transit-transfer'

###################################
# Living room camera customization
###################################
camera.salon:
  friendly_name: 'Salón'
binary_sensor.salon_camara_infrarrojo:
  friendly_name: 'Infrarrojos salón'
  icon: 'mdi:led-on'
binary_sensor.salon_camara_det_mov:
  friendly_name: 'Movimiento salón'
switch.salon_camara_det_mov:
  friendly_name: 'Det. mov. salón'
  icon: 'mdi:transit-transfer'

###################################
# Swimming pool camera customization
###################################
camera.piscina:
  friendly_name: 'Piscina'
binary_sensor.piscina_camara_infrarrojo:
  friendly_name: 'Infrarrojos piscina'
  icon: 'mdi:led-on'
binary_sensor.piscina_camara_det_mov:
  friendly_name: 'Movimiento piscina'
switch.piscina_camara_det_mov:
  friendly_name: 'Det. mov. piscina'
  icon: 'mdi:transit-transfer'

###################################
# BBQ camera customization
###################################
camera.barbacoa:
  friendly_name: 'Barbacoa'
binary_sensor.barbacoa_camara_infrarrojo:
  friendly_name: 'Infrarrojos barbacoa'
  icon: 'mdi:led-on'
binary_sensor.barbacoa_camara_det_mov:
  friendly_name: 'Movimiento barbacoa'
switch.barbacoa_camara_det_mov:
  friendly_name: 'Det. mov. barbacoa'
  icon: 'mdi:transit-transfer'

###################################
# Shed camera customization
###################################
camera.caseta:
  friendly_name: 'Caseta'
binary_sensor.caseta_camara_det_mov:
  friendly_name: 'Movimiento caseta'
switch.caseta_camara_det_mov:
  friendly_name: 'Det. mov. caseta'
  icon: 'mdi:transit-transfer'

###################################
# Main entrance camera customization
###################################
binary_sensor.entrada_outdoor_motion:
  friendly_name: 'Movimiento desconocido'
binary_sensor.entrada_outdoor_human:
  friendly_name: 'Persona detectada'
binary_sensor.entrada_outdoor_animal:
  friendly_name: 'Animal detectado'
  icon: 'mdi:paw'
binary_sensor.entrada_outdoor_vehicle:
  friendly_name: 'Vehiculo detectado'
  icon: 'mdi:car'

###################################
# Office motion sensor customization
###################################
binary_sensor.despacho_sensor_movimiento:
  friendly_name: 'Movimiento despacho'
  device_class: 'motion'
binary_sensor.despacho_sensor_movimiento_sabotaje:
  friendly_name: 'Manipulación sensor'
sensor.despacho_sensor_movimiento_luminance:
  icon: 'mdi:weather-sunny'
  friendly_name: 'Luminosidad'
sensor.despacho_sensor_movimiento_bateria:
  device_class: 'battery'
  friendly_name: 'Detector movimiento despacho'
sensor.despacho_sensor_movimiento_temperature:
  friendly_name: 'Temperatura'

###################################
# Porch door sensor customization
###################################
binary_sensor.porche_sensor_puerta:
  device_class: 'door'
  friendly_name: 'Puerta porche'
sensor.porche_sensor_puerta:
#  icon: 'mdi:glassdoor'
  friendly_name: 'Estado puerta porche'
sensor.porche_sensor_puerta_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor puerta cocina'
sensor.porche_sensor_puerta_temperature:
  friendly_name: 'Temperatura'
  icon: mdi:thermometer

###################################
# Porch blind door sensor customization
###################################
binary_sensor.porche_sensor_persiana:
  device_class: 'door'
  friendly_name: 'Persiana porche'
sensor.porche_sensor_persiana:
#  icon: 'mdi:glassdoor'
  friendly_name: 'Estado persiana porche'
sensor.porche_sensor_persiana_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor persiana cocina'

###################################
# Laundry door sensor customization
###################################
binary_sensor.coladuria_sensor_puerta:
  device_class: 'door'
  friendly_name: 'Puerta coladuría'
sensor.coladuria_sensor_puerta:
#  icon: 'mdi:glassdoor'
  friendly_name: 'Estado puerta coladuria'
sensor.coladuria_sensor_puerta_bateria:
  device_class: 'battery'
  friendly_name: 'Sensor puerta coladuria'
climate.netatmo_general:
  friendly_name: 'Calefacción'
sensor.netatmo_exterior_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_exterior_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_exterior_min_temp:
  friendly_name: 'Mínima de hoy'
  icon: 'mdi:thermometer-minus'
sensor.netatmo_exterior_max_temp:
  friendly_name: 'Máxima de hoy'
  icon: 'mdi:thermometer-plus'
sensor.netatmo_exterior_battery:
  friendly_name: 'Netatmo exterior'
  device_class: 'battery'
sensor.netatmo_exterior_radio:
  friendly_name: 'Señal exterior'
sensor.netatmo_pluviometro_rain:
  friendly_name: 'Previsión lluvia'
sensor.netatmo_pluviometro_sum_rain_1:
  friendly_name: 'Lluvia última hora'
sensor.netatmo_pluviometro_sum_rain_24:
  friendly_name: 'Lluvia 24 horas'
sensor.netatmo_pluviometro_battery:
  friendly_name: 'Netatmo pluviómetro'
  device_class: 'battery'
sensor.netatmo_pluviometro_radio:
  friendly_name: 'Señal pluviómetro'
sensor.netatmo_salon_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_salon_min_temp:
  friendly_name: 'Mínima de hoy'
  icon: 'mdi:thermometer-minus'
sensor.netatmo_salon_max_temp:
  friendly_name: 'Máxima de hoy'
  icon: 'mdi:thermometer-plus'
sensor.netatmo_salon_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_salon_noise:
  friendly_name: 'Nivel de ruido'
sensor.netatmo_salon_pressure:
  friendly_name: 'Presión atmosférica'
sensor.netatmo_salon_co2:
  friendly_name: 'Nivel CO2'
sensor.netatmo_salon_wifi:
  friendly_name: 'Señal Wifi Netatmo'
sensor.netatmo_anemometro_angle:
  friendly_name: 'Dirección viento'
sensor.netatmo_anemometro_battery:
  friendly_name: 'Netatmo anemómetro'
  device_class: 'battery'
sensor.netatmo_anemometro_gust_angle:
  friendly_name: 'Dirección rachas'
sensor.netatmo_anemometro_gust_strength:
  friendly_name: 'Velocidad rachas'
sensor.netatmo_anemometro_radio:
  friendly_name: 'Señal anemómetro'
sensor.netatmo_anemometro_strength:
  friendly_name: 'Velocidad viento'
sensor.netatmo_suite_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_suite_min_temp:
  friendly_name: 'Mínima de hoy'
  icon: 'mdi:thermometer-minus'
sensor.netatmo_suite_max_temp:
  friendly_name: 'Máxima de hoy'
  icon: 'mdi:thermometer-plus'
sensor.netatmo_suite_co2:
  friendly_name: 'Nivel CO2'
sensor.netatmo_suite_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_suite_battery:
  friendly_name: 'Netatmo suite'
  device_class: 'battery'
sensor.netatmo_suite_radio:
  friendly_name: 'Señal suite'
sensor.netatmo_habitacion_temperature:
  friendly_name: 'Temperatura'
sensor.netatmo_habitacion_min_temp:
  friendly_name: 'Mínima de hoy'
  icon: 'mdi:thermometer-minus'
sensor.netatmo_habitacion_max_temp:
  friendly_name: 'Máxima de hoy'
  icon: 'mdi:thermometer-plus'
sensor.netatmo_habitacion_co2:
  friendly_name: 'Nivel CO2'
sensor.netatmo_habitacion_humidity:
  friendly_name: 'Humedad'
sensor.netatmo_habitacion_battery:
  friendly_name: 'Netatmo hab. niños'
  device_class: 'battery'
sensor.netatmo_habitacion_radio:
  friendly_name: 'Señal hab.niños'
sensor.first_floor_temperature:
  friendly_name: 'Temp media 1ª planta'
  icon: 'mdi:thermometer'
  unit_of_measurement: '°C'
switch.thermostat_away_mode:
  friendly_name: 'Modo ausente'
  icon: mdi:home-outline
sensor.season:
  friendly_name: 'Estación'
sensor.home_temperature_mean:
  friendly_name: 'Temp. media 24h'
  icon: 'mdi:thermometer'
  unit_of_measurement: '°C'
sensor.home_temperature:
  friendly_name: 'Temp. media'
sensor.entrance_hall_thermostat_temperature:
  friendly_name: 'Temperatura'
  unit_of_measurement: '°C'
sensor.dark_sky_summary_0d:
  friendly_name: 'Previsión'
binary_sensor.summer_time:
  friendly_name: 'Horario de verano'
