#- platform: nmap_tracker
#  hosts: 192.168.1.0/24
#  # The number of minutes nmap will not scan this devices, assuming it is home, in order to preserve the device battery.
#  home_interval: 3
#  # If new discovered devices are tracked by default (default: yes)
#  track_new_devices: no
#  # Seconds between each scan for new devices (default: 12)
#  interval_seconds: 60
#  # Seconds to wait till marking someone as not home after not being seen
#  # (default: 180)
#  consider_home: 180
#  exclude:
#    - 192.168.1.100

#- platform: owntracks
#  max_gps_accuracy: 200
#  waypoints: yes

- platform: linksys_smart
  host: !secret wrt1900acs_host
#  username: !secret wrt1900acs_username 
#  password: !secret wrt1900acs_password

- platform: mqtt_json
  devices:
    # Toyota tracker
    toyota: location/car/toyota
    # Nissan tracker
    nissan: location/car/nissan

- platform: mqtt
  devices:
    # Updated when hokusphone is connected to a WiFi
    hokusphone_wifi: location/hokusphone/wifi
    # Updated when iBeacon is detected from hokusphone
    hokusphone_ibeacon: location/hokusphone/ibeacon
    # Updated when geniphone is connected to a WiFi
    geniphone_wifi: location/geniphone/wifi
    # Updated when iBeacon is detected from geniphone
    geniphone_ibeacon: location/geniphone/ibeacon

#- platform: bluetooth_le_tracker

#- platform: google_maps
#  username: !secret google_device_tracker_username
#  password: !secret google_device_tracker_password