################################################
# Views
################################################
default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.alarma
    - group.barrera
    - group.familia
    - group.energia
    - group.calefaccion
#    - group.seguridad
    - group.luces_interiores
    - sensor.a_la_oficina
    - sensor.al_colegio
    - updater.updater

Vista Seguridad:
  view: yes
  icon: mdi:security-home
  entities:
    - group.alarma
    - group.familia
    - group.seguridad
    - group.camara_recibidor
    - group.camara_entrada_principal
    - group.camara_piscina
    - group.camara_barbacoa
    - group.camara_caseta
    - group.acciones_presencia
    - group.puerta_porche_cocina
    - group.persiana_porche_cocina
    - group.puerta_coladuria_cocina
    - group.sensor_salon

Interior:
  view: yes
  icon: mdi:home-map-marker
  entities:
    - group.salon
    - group.cocina
    - group.recibidor
    - group.escalera
    - group.suite
    - group.habitacion_ninos
    - group.calefaccion
    - group.seguridad_interior
    - group.confort

Exterior:
  view: yes
  icon: mdi:tree
  entities:
    - group.luces_exteriores
    - group.meteorologia
    - group.temperatura
    - group.lluvia
    - group.viento
    - group.barrera
    - group.piscina
    - camera.barbacoa
    - camera.caseta
    - camera.entrada_principal
    - group.seguridad_exterior

Varios:
  view: yes
  icon: mdi:grid
  entities:
    - group.jordi
    - group.toyota
#    - group.nissan
    - group.internet
    - group.estado_ha
    - group.crypto_currency
    - group.impresora
#    - group.nas
    - group.sai
    - group.estado_baterias
    - media_player.hokussqueezebox
    - media_player.salon
    - media_player.homeassistant

################################################
# Groups
################################################
Energía:
  entities:
    - binary_sensor.ups_status_bs
#    - sensor.energy_usage
    - sensor.efergy_2577
    - sensor.ups_status

Temperatura:
  entities:
    - sensor.netatmo_exterior_temperature
    - sensor.netatmo_exterior_min_temp
    - sensor.netatmo_exterior_max_temp
    - history_graph.temperatura_exterior
    - sensor.netatmo_exterior_humidity
    - sensor.exterior_termometro_temperatura_tendencia
    - sensor.netatmo_exterior_radio

Meteorología:
  entities:
    - sensor.pws_weather_1d_metric
    - sensor.sunrise
    - sensor.sunset
    - sensor.season

Lluvia:
  entities:
    - sensor.netatmo_pluviometro_rain
    - sensor.netatmo_pluviometro_sum_rain_1
    - sensor.netatmo_pluviometro_sum_rain_24
    - sensor.netatmo_pluviometro_radio

Viento:
  entities:
    - sensor.netatmo_anemometro_strength
    - sensor.netatmo_anemometro_angle
    - sensor.netatmo_anemometro_gust_strength
    - sensor.netatmo_anemometro_gust_angle
    - sensor.netatmo_anemometro_radio

Salón:
  entities:
    - sensor.netatmo_salon_temperature
    - sensor.salon_termometro_temperatura_tendencia
    - sensor.netatmo_salon_min_temp
    - sensor.netatmo_salon_max_temp
    - sensor.netatmo_salon_humidity
    - sensor.netatmo_salon_noise
    - sensor.netatmo_salon_pressure
    - sensor.netatmo_salon_co2
    - sensor.salon_termometro_co2_tendencia
    - sensor.netatmo_salon_wifi
    - binary_sensor.salon_sensor_movimiento
    - binary_sensor.salon_sensor_movimiento_sabotaje
    - input_boolean.salon_sensor_movimiento
    - sensor.salon_sensor_movimiento_luminance
    - sensor.salon_sensor_movimiento_temperature

Escalera:
  entities:
    - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
    - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy
    - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power

Suite:
  entities:
    - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
    - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_energy_2
    - sensor.fibaro_fgs223_double_relay_luz_escalera_y_suite_power_2
    - sensor.netatmo_suite_temperature
    - sensor.suite_termometro_temperatura_tendencia
    - sensor.netatmo_suite_min_temp
    - sensor.netatmo_suite_max_temp
    - sensor.netatmo_suite_co2
    - sensor.suite_termometro_co2_tendencia
    - sensor.netatmo_suite_humidity
    - sensor.netatmo_suite_radio

Habitación niños:
  entities:
    - sensor.netatmo_habitacion_temperature
    - sensor.habitacion_termometro_temperatura_tendencia
    - sensor.netatmo_habitacion_min_temp
    - sensor.netatmo_habitacion_max_temp
    - sensor.netatmo_habitacion_co2
    - sensor.habitacion_termometro_co2_tendencia
    - sensor.netatmo_habitacion_humidity
    - sensor.netatmo_habitacion_radio

Recibidor:
  entities:
    - switch.swiid_swiidinter_lampara_recibidor_switch
    - sensor.recibidor_termometro_temperatura
    - sensor.recibidor_termometro_temperatura_tendencia
    - camera.recibidor

Cocina:
  entities:
    - binary_sensor.porche_sensor_puerta
    - input_boolean.cocina_sensor_puerta
    - binary_sensor.porche_sensor_persiana
    - input_boolean.cocina_sensor_persiana
    - binary_sensor.coladuria_sensor_puerta
    - input_boolean.coladuria_sensor_puerta
    - sensor.porche_sensor_puerta_temperature

Luces exteriores:
  entities:
    - light.barrera_derecha
    - light.barrera_izquierda
    - light.puerta_coladuria
    - input_number.entrada_luz_brillo

External Lights Group:
  entities:
    - light.barrera_derecha
    - light.barrera_izquierda
    - light.puerta_coladuria

Luces interiores:
  entities:
    - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch_2
    - switch.fibaro_fgs223_double_relay_luz_escalera_y_suite_switch
    - switch.swiid_swiidinter_lampara_recibidor_switch

Barrera:
  entities:
    - switch.barrera
    - sensor.switch_barrera

Internet:
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.caducidad_certificado_ssl
    - sensor.dominio_principal
    - sensor.dominio_nena

Crypto Currency:
  entities:
    - sensor.exchange_rate_1_btc
    - sensor.bitcoin_balance
    - sensor.bitcoin_walet_value
    - sensor.exchange_rate_1_eth
    - sensor.ethereum_balance
    - sensor.ethereum_walet_value

Calefacción:
  entities:
    - switch.termostato
    - switch.termostato_modo_ausente
    - climate.termostato

Confort:
  entities:
    - binary_sensor.confort_state
    - sensor.temperature_ground_floor
    - sensor.planta_baja_temperatura_tendencia
    - sensor.temperature_first_floor
    - sensor.primera_planta_temperatura_tendencia
    - group.unidad_familiar
    - switch.termostato
    - switch.termostato_modo_ausente
    - climate.termostato

Estado HA:
  entities:
    - script.system_restart_ha
    - script.system_reboot_pi
    - sensor.cpu_use
    - sensor.ram_free
    - sensor.disk_free_
    - sensor.last_boot
    - sensor.since_last_boot
    - sensor.ha_runtime_in_minutes
    - sensor.connected_clients
#    - sensor.current_release
#    - sensor.latest_release

Impresora:
  entities:
    - sensor.hp_photosmart_5520
    - sensor.ink_level_magenta
    - sensor.ink_level_cyan
    - sensor.ink_level_yellow
    - sensor.ink_level_black

SAI:
  entities:
#    - sensor.nut_ups_manufacturer
#    - sensor.nut_ups_model
    - sensor.ups_status
    - sensor.nut_ups_battery_charge
    - sensor.nut_ups_battery_runtime
    - switch.ups_beeper

Estado baterías:
  entities:
    - sensor.netatmo_exterior_battery
    - sensor.netatmo_pluviometro_battery
    - sensor.netatmo_anemometro_battery
    - sensor.netatmo_suite_battery
    - sensor.netatmo_habitacion_battery
    - sensor.cocina_sensor_puerta_bateria
    - sensor.cocina_sensor_persiana_bateria
    - sensor.coladuria_sensor_puerta_bateria
    - sensor.salon_sensor_movimiento_bateria
    - sensor.piscina_sensor_piscina_bateria
    - sensor.recibidor_boton_bateria
#Escalera:
#  entities:
#    - device_tracker.router_movistar
#    - device_tracker.efergy
#    - device_tracker.qnap
#
#Despacho:
#  entities:
#    - device_tracker.hokus_laptop
#    - device_tracker.hokus_laptop_wifi
#    - device_tracker.hp_photosmart_5520
#
#Recibidor:
#  entities:
#    - device_tracker.cam_recibidor
#    - device_tracker.wemo_maker_barrera
#
#Dispositivos Salón:
#  entities:
#    - device_tracker.netatmo
#    - device_tracker.chromecast
#    - device_tracker.decodificador_movistar
#    - device_tracker.bluesens_wifi
#    - device_tracker.bluesens
#    - device_tracker.router_speedtouch
#    - device_tracker.dvd_player
#Suite:
#  entities:
#    - device_tracker.squeezebox
#    - device_tracker.withings_smart_scale
#    - device_tracker.router_orange
#Caseta:
#  entities:
#    - device_tracker.wemo_insight_piscina
#    - device_tracker.router_vodafone
#    - device_tracker.cam_piscina
#    - device_tracker.cam_caseta
#Cocina:
#  entities:
#    - device_tracker.wemo_link
#    - device_tracker.netatmo_thermostat
#Portátil:
#  entities:
#    - device_tracker.geni_laptop
#    - device_tracker.hokus_laptop
#    - device_tracker.hokus_laptop_wifi
#    - device_tracker.nexus_10
#    - device_tracker.ipad
#Dispositivos Varios:
#  entities:
#    - device_tracker.c67bb0af2169
