################################################
# Views
################################################
default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.alarma
    - group.barrera
    - group.familia
    - group.energia
    - group.calefaccion
#    - group.seguridad
    - group.luces_exteriores
    - group.luces_interiores
    - sensor.a_la_oficina
    - sensor.al_colegio
    - updater.updater

Vista Seguridad:
  view: yes
  icon: mdi:shield-home
  entities:
    - group.alarma
    - group.familia
    - group.seguridad
    - group.camara_recibidor
    - group.camara_salon
    - group.sensor_despacho
    - group.camara_entrada_principal
    - group.camara_piscina
    - group.camara_barbacoa
    - group.camara_caseta
    - group.acciones_presencia
    - group.puerta_porche_cocina
    - group.persiana_porche_cocina
    - group.puerta_coladuria_cocina
    - group.sensor_salon

Interior:
  view: yes
  icon: mdi:home-map-marker
  entities:
    - group.salon
    - group.cocina
    - group.recibidor
    - group.despacho
    - group.escalera
    - group.suite
    - group.habitacion_ninos
    - group.calefaccion
    - group.seguridad_interior
    - group.confort

Exterior:
  view: yes
  icon: mdi:tree
  entities:
    - group.luces_exteriores
    - group.climatologia
    - group.temperatura
    - group.lluvia
    - group.viento
    - group.barrera
    - group.piscina
    - camera.barbacoa
    - camera.caseta
    - camera.entrada_principal
    - group.seguridad_exterior

Coche:
  view: yes
  icon: mdi:car
  entities:
    - group.cargador
    - group.consumo_electricidad
    - group.estado
    - group.localizacion
#    - group.nissan

Dashboard Coche:
  view: yes
  icon: mdi:car-electric
  entities:
    - group.cargador

Varios:
  view: yes
  icon: mdi:grid
  entities:
    - group.jordi

    - group.internet
    - group.estado_ha
    - group.crypto_currency
    - group.impresora
#    - group.nas
    - group.sai
    - group.estado_baterias
    - media_player.hokussqueezebox
    - media_player.salon
    - media_player.recibidor
    - media_player.cocina

################################################
# Groups
################################################

Salón:
  entities:
    - camera.salon
    - sensor.netatmo_salon_temperature
    - sensor.netatmo_salon_temperature_trend
    - sensor.netatmo_salon_min_temp
    - sensor.netatmo_salon_max_temp
    - sensor.netatmo_salon_humidity
    - sensor.netatmo_salon_noise
    - sensor.netatmo_salon_pressure
    - sensor.netatmo_salon_co2
    - sensor.netatmo_salon_co2_trend
    - sensor.netatmo_salon_wifi

Despacho:
  entities:
    - sensor.despacho_sensor_movimiento_luminance
    - sensor.despacho_sensor_movimiento_temperature
    - sensor.office_sensor_temperature_trend

Escalera:
  entities:
    - switch.escalera_switch
    - sensor.escalera_switch_energy
    - sensor.escalera_switch_power

Suite:
  entities:
    - switch.suite_switch
    - sensor.suite_switch_energy
    - sensor.suite_switch_power
    - sensor.netatmo_suite_temperature
    - sensor.netatmo_suite_temperature_trend
    - sensor.netatmo_suite_min_temp
    - sensor.netatmo_suite_max_temp
    - sensor.netatmo_suite_co2
    - sensor.netatmo_suite_co2_trend
    - sensor.netatmo_suite_humidity
    - sensor.netatmo_suite_radio

Habitación niños:
  entities:
    - sensor.netatmo_habitacion_temperature
    - sensor.netatmo_habitacion_temperature_trend
    - sensor.netatmo_habitacion_min_temp
    - sensor.netatmo_habitacion_max_temp
    - sensor.netatmo_habitacion_co2
    - sensor.netatmo_habitacion_co2_trend
    - sensor.netatmo_habitacion_humidity
    - sensor.netatmo_habitacion_radio

Recibidor:
  entities:
    - camera.recibidor
    - switch.entrance_hall_lamp_switch
    - sensor.entrance_hall_thermostat_temperature
    - sensor.entrance_hall_thermostat_temperature_trend

Cocina:
  entities:
    - binary_sensor.porche_sensor_puerta
    - input_boolean.porche_sensor_puerta
    - binary_sensor.porche_sensor_persiana
    - input_boolean.porche_sensor_persiana
    - binary_sensor.coladuria_sensor_puerta
    - input_boolean.coladuria_sensor_puerta
    - sensor.porche_sensor_puerta_temperature

Internet:
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.caducidad_certificado_ssl
    - sensor.dominio_principal
    - sensor.dominio_nena
    - sensor.google_wifi_current_version
    - sensor.google_wifi_last_restart
    - sensor.google_wifi_new_version
    - sensor.google_wifi_status
    - sensor.google_wifi_uptime

Crypto Currency:
  entities:
    - sensor.exchange_rate_1_btc
    - sensor.bitcoin_balance
    - sensor.bitcoin_walet_value
    - sensor.exchange_rate_1_eth
    - sensor.ethereum_balance
    - sensor.ethereum_walet_value

Estado HA:
  entities:
    - script.system_restart_ha
    - script.system_reboot_pi
    - sensor.processor_use
    - sensor.memory_free
    - sensor.disk_free
    - sensor.last_boot
    - sensor.ha_runtime_in_minutes
    - sensor.connected_clients
#    - sensor.current_release
#    - sensor.latest_release

Impresora:
  entities:
    - sensor.hp_photosmart_5520
    - sensor.ink_level_magenta
    - sensor.ink_level_cyan
    - sensor.ink_level_yellow
    - sensor.ink_level_black

Estado baterías:
  entities:
    - sensor.netatmo_exterior_battery
    - sensor.netatmo_pluviometro_battery
    - sensor.netatmo_anemometro_battery
    - sensor.netatmo_suite_battery
    - sensor.netatmo_habitacion_battery
    - sensor.porche_sensor_puerta_bateria
    - sensor.porche_sensor_persiana_bateria
    - sensor.coladuria_sensor_puerta_bateria
    - sensor.despacho_sensor_movimiento_bateria
    - sensor.recibidor_boton_bateria