#############################################################
# System scripts
#############################################################
system_restart_ha:
  alias: 'Reiniciar HA'
  sequence:
      - service: homeassistant.restart

system_reboot_pi:
  alias: 'Reiniciar Pi'
  sequence:
      - service: shell_command.reboot_pi

#############################################################
# Speech scripts
#############################################################
google_home_good_morning:
  alias: 'Buenos días'
  sequence:
    # Wait until tts finishes
#    - wait_template: "{{ is_state('media_player.recibidor', 'playing') }}"
#    - wait_template: "{{ not is_state('media_player.recibidor', 'playing') }}"
    - service: script.turn_on
      data:
        entity_id: script.speech_parte_meteorologico_corto
    - wait_template: "{{ is_state('media_player.recibidor', 'playing') }}"
    - wait_template: "{{ not is_state('media_player.recibidor', 'playing') }}"
    - service: script.turn_on
      data:
        entity_id: script.geni_shift

speech_set_tts_volume_level:
  alias: 'Lower the home-assistant tts volume level between 23 and 9'
  sequence:
    - condition: time
      after: '23:00'
      before: '9:00'
    - service: media_player.volume_set
      entity_id: media_player.recibidor
      data:
        volume_level: 0.3
    - delay:
        minutes: 2
    - service: media_player.volume_set
      entity_id: media_player.recibidor
      data:
        volume_level: 0.75

speech_parte_meteorologico:
  alias: 'Parte meteorológico'
  sequence:
    - service: tts.google_say
      entity_id: media_player.recibidor
      data_template:
        message: >
          La temperatura exterior es de {{ states("sensor.netatmo_exterior_temperature") | replace("."," con ") }} grados 
          y una humedad del {{ states("sensor.netatmo_exterior_humidity") }} {{states.sensor["netatmo_exterior_humidity"].attributes.unit_of_measurement }}.
          La temperatura máxima de hoy ha sido de {{ states("sensor.netatmo_exterior_max_temp") | replace("."," con ") }} grados.
          La temperatura mínima de hoy ha sido de {{ states("sensor.netatmo_exterior_min_temp") | replace("."," con ") }} grados.
          La presión atmosférica es de {{ states("sensor.netatmo_salon_pressure") | replace("."," con ") }} {{states.sensor["netatmo_salon_pressure"].attributes.unit_of_measurement }}.
          Las rachas de viento son de {{ states("sensor.netatmo_anemometro_gust_strength") }} {{states.sensor["netatmo_anemometro_gust_strength"].attributes.unit_of_measurement }}'
          {%- if states("sensor.netatmo_pluviometro_rain") == "0" %} No está lloviendo.{% else %} Está lloviendo unos {{ states("sensor.netatmo_pluviometro_rain") | replace("."," con ") }} {{states.sensor["netatmo_pluviometro_rain"].attributes.unit_of_measurement }}.{% endif %}
          {%- if states("sensor.netatmo_pluviometro_sum_rain_1") == "0" %} No ha llovido durante la última hora.{% else %} La precipitación de la última hora ha sido de {{ states("sensor.netatmo_pluviometro_sum_rain_1") | replace("."," con ") }} {{states.sensor["netatmo_pluviometro_sum_rain_1"].attributes.unit_of_measurement }}.{% endif %}
          {%- if states("sensor.netatmo_pluviometro_sum_rain_24") == "0" %} No ha llovido durante las últimas 24 horas.{% else %} La precipitación de las últimas 24 horas ha sido de {{ states("sensor.netatmo_pluviometro_sum_rain_24") | replace("."," con ") }} {{states.sensor["netatmo_pluviometro_sum_rain_24"].attributes.unit_of_measurement }}.{% endif %}
        cache: false

speech_parte_meteorologico_corto:
  alias: 'Parte meteorológico corto'
  sequence:
    - service: tts.google_say
      entity_id: media_player.recibidor
      data_template:
        message: >
          La temperatura exterior es de {{ states("sensor.netatmo_exterior_temperature") | replace("."," con ") }} grados.
          La temperatura máxima de hoy ha sido de {{ states("sensor.netatmo_exterior_max_temp") | replace("."," con ") }} grados.
          La temperatura mínima de hoy ha sido de {{ states("sensor.netatmo_exterior_min_temp") | replace("."," con ") }} grados.
        cache: false

chores:
  alias: 'Basura'
  sequence:
    - service: tts.google_say
      entity_id: media_player.recibidor
      data_template:
        message: >
          {% if now().strftime('%a') != "Sat" %}
            {{['La suerte está echada.',
               'Déjame pensar.',
               'Creo que',
               'He decidido que',
               'Yo diría que',
               'Si la memoria no me falla.',
               'Si no voy mal,',
               'Espera que lo consulto.',
               'Según mis cálculos',
               'Lula me ha dicho que',
               'Si no voy mal',
               'Espera que piense.']|random}} hoy le toca a {% if now().strftime('%j')|int % 2 != 0 %}Carlos{% else %}Jorge{% endif %} sacar {{ {"Sun": "la basura orgánica", "Mon": "los envases y el papel", "Tue": "la basura orgánica", "Wed": "los restos y vídrio", "Thu": "la basura orgánica", "Fri": "los envases", "Sat": "no hay que sacar basura"}[now().strftime('%a')] }}.
          {% else %}
            Hoy estáis de suerte, no hay que sacar la basura
          {% endif %}

geni_shift:
  alias: 'Turno Geni'
  sequence:
    - service: tts.google_say
      entity_id: media_player.recibidor
      data_template:
        message: >
         {%- if is_state("sensor.next_shift_event", "Saliente") -%}
           Jeni está hoy saliente de noche
         {%- else -%}
           {% set diff = as_timestamp(states.calendar.turnos_geni_everything.attributes.start_time) - as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0).replace(microsecond=0)) %}
           {%- if diff < 86400 -%}
             Jeni trabaja hoy por la {{ states("sensor.next_shift_event") }}
           {%- elif diff >= 86400 and diff < 86400*2 -%}
             Jeni trabaja mañana por la {{ states("sensor.next_shift_event") }}
           {%- else -%}
             Jeni trabaja el próximo {{ states("sensor.next_shift_date") }} por la {{ states("sensor.next_shift_event") }}
           {% endif %}
         {% endif %}

#############################################################
# Misc scripts
#############################################################
goto_sleep:
  alias: 'Go to sleep'
  sequence:
    # Only execute script between 21:00 and 6:00
    - condition: time
      after: '21:00'
      before: '6:00'
    # Turn on stairs lights
    - service: switch.turn_on
      data:
        entity_id: switch.escalera_switch
    # Close fence if open
    - service_template: >
        {%- if is_state("sensor.outside_fence", "Abierta") -%}
          homeassistant.turn_on
        {%- else -%}
          homeassistant.update_entity
        {%- endif -%}

      data:
        entity_id: switch.barrera
    # Turn off outside lights
    - service: homeassistant.turn_off
      data:
        entity_id: group.luces_exteriores
    # Turn off hall lamp
    - service: switch.turn_off
      data:
        entity_id: switch.entrance_hall_lamp_switch
    # Alarm arm night
    - service: script.turn_on
      data:
        entity_id: script.alarm_arm_night
      # Notify found incidences and say good night.
    - service: tts.google_say
      entity_id: media_player.recibidor
      data_template:
        message: >
          {%- if is_state("binary_sensor.porche_sensor_puerta", "on") %}Puerta de la cocina abierta. {% endif %}
          {%- if is_state("binary_sensor.porche_sensor_persiana", "on") %}Persiana de la cocina abierta. {% endif %}
          {%- if is_state("binary_sensor.coladuria_sensor_puerta", "on") %}Puerta de la coladuría abierta. {% endif %}
          {%- if is_state("sensor.outside_fence", "Abierta") -%}Cerrando barrera.{% endif -%}
          Alarma armada en modo noche.
    # Wait until tts finishes
#    - delay: '00:00:{{ states.media_player.recibidor.attributes.media_duration | int }}'
    # Wait 2 minutes before turning stair lights off
    - delay:
        minutes: 2
    # Turn stairs lights off
    - service: switch.turn_off
      data:
        entity_id: switch.escalera_switch