- platform: mqtt
  name: 'holiday'
  state_topic: 'home/holiday/status'
  command_topic: 'home/holiday/status'
  payload_on: 'ON'
  payload_off: 'OFF'
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: 'termostato'
  state_topic: 'home/heating/status'
  command_topic: 'home/heating/status'
  payload_on: 'ON'
  payload_off: 'OFF'
  optimistic: false
  qos: 0
  retain: true

- platform: template
  switches:
    termostato_modo_ausente:
      value_template: >-
        {%- if states("climate.termostato") != "unknown" -%}
          {{ states.climate.termostato.attributes.away_mode }}
        {%- else -%}
          off
        {%- endif %}
      turn_on:
        service: climate.set_away_mode
        entity_id: climate.termostato
        data:
          away_mode: true
      turn_off:
        service: climate.set_away_mode
        entity_id: climate.termostato
        data:
          away_mode: false
#    comfort_state:
#      value_template: {{ states('sensor.temperature_first_floor')|float < states.climate.termostato.attributes.temperature|float and is_state('group.unidad_familiar', 'home') and is_state('switch.termostato', 'on') and is_state('switch.termostato_modo_ausente','off') and is_state_attr('climate.termostato', 'operation_mode', 'idle') and is_state('binary_sensor.primera_planta_temperatura_descendiendo','on') }}
#      turn_on:
#        service: climate.set_temperature
#        data_template:
#          entity_id: climate.termostato
#          temperature: 23
#      turn_off:
#        service: script.turn_on
#        entity_id: script.comfort_mode_off

          
- platform: template
  switches:
    ups_beeper:
      value_template: "{{ is_state('sensor.nut_ups_beeper_status', 'enabled') }}"
      turn_on:
        service: shell_command.nut_ups_enable_beeper
      turn_off:
        service: shell_command.nut_ups_disable_beeper