title: Casa
resources:
  - url: /local/alarm_control_panel-card.js?v=1
    type: js
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views:
    # View tab title.
  - title: Principal
    # Optional unique id for direct access /lovelace/${id}
    id: principal
    # Each view can have a different theme applied.
    theme: dark-mode
    # Specify a tab icon if you want the view tab to be an icon.
    icon: mdi:home-assistant
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - id: 66c366c2d7c147f6a5a9828956db483d  # Automatically created id
        type: thermostat
        entity: climate.termostato
      - id: 960f53d2d6c6425998816ce94e4ed5af  # Automatically created id
        type: alarm-panel
        title: Alarma
        entity: alarm_control_panel.casa
        states:
          - arm_away
          - arm_night
      - id: 3635120703ff4cbf8f97489d58375a7d  # Automatically created id
        type: entity-filter
        entities:
          - binary_sensor.porche_sensor_puerta
          - binary_sensor.coladuria_sensor_puerta
          - binary_sensor.porche_sensor_persiana
        state_filter:
          - on
        card:
          type: glance
          title: Puertas abiertas
      - id: 2040161f873d450d8eab0d681f516d3a  # Automatically created id
        type: entity-filter
        entities:
          - device_tracker.geni_combined
          - device_tracker.jordi_combined
          - device_tracker.virtual_device
        state_filter:
          - home
        card:
          type: glance
          title: Ocupación
