- name: Oficina
  latitude: !secret office_latitude
  longitude: !secret office_longitude
  radius: 200
  icon: mdi:briefcase

- name: Colegio
  latitude: !secret school_latitude
  longitude: !secret school_longitude
  radius: 175
  icon: mdi:school

- name: Hospital
  latitude: !secret office2_latitude
  longitude: !secret office2_longitude
  radius: 250
  icon: mdi:hospital-building

#- name: Casa
#  latitude: !secret ha_latitude
#  longitude: !secret ha_longitude
#  radius: 100
#  icon: mdi:home
