alias: '[Alarm] Notify when alarm is armed night'
trigger: 
  - platform: state
    entity_id: alarm_control_panel.home
    from: 'disarmed'
    to: 'armed_night'
action:
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'good'
            pretext: ':bell: *Alarma* :bell:'
            text: 'Alarma armada en modo noche :sleeping:'
            fallback: 'Alarma'