alias: '[Alarm] Turn off security group when alarm is disarmed'
trigger: 
  - platform: state
    entity_id: alarm_control_panel.home
    to: 'disarmed'
action:
  # Turn off alarm related sensors
  - service: homeassistant.turn_off
    data:
      entity_id: group.seguridad
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'good'
            pretext: ':bell: *Alarma* :bell:'
            text: 'Alarma desarmada'
            fallback: 'Alarma'