# Notify camera motion detection including attached video
alias: '[Alarm] Notify camera motion detection including attached video when alarm triggered'
trigger:
  platform: event
  event_type: folder_watcher
  event_data:
    event_type: created
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ "mp4" in trigger.event.data.file }}'
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.recibidor_camara_det_mov
      state: 'on'
    - condition: state
      entity_id: switch.salon_camara_det_mov
      state: 'on'
    - condition: state
      entity_id: switch.barbacoa_camara_det_mov
      state: 'on'
    - condition: state
      entity_id: switch.piscina_camara_det_mov
      state: 'on'
    - condition: state
      entity_id: switch.caseta_camara_det_mov
      state: 'on'
    - condition: state
      entity_id: input_boolean.entrada_camara_det_mov
      state: 'on'
action:
  # Delay before evaluating alarm state. This is needed to avoid skipping notifications
  - delay:
      seconds: 1
  # Only continue execution if alarm has been triggered
  - condition: state
    entity_id: alarm_control_panel.home
    state: 'triggered'
  # Delay to allow the file to be totally written in the FTP before sending it
  - delay:
      seconds: 90
  # Notify the video taken
  - service: script.alarm_notify_camera
    data_template:
      data:
        file: '{{ trigger.event.data.path }}'
        camera_name: >-
          {%- if "C1_00626E615161" in trigger.event.data.folder -%}recibidor
          {%- elif "FI9853EP_00626E563E69" in trigger.event.data.folder -%}piscina
          {%- elif "FI9900P_00626E6D21B2" in trigger.event.data.folder -%}barbacoa
          {%- elif "WVC54CGA" in trigger.event.data.folder -%}caseta
          {%- elif "puerta_principal" in trigger.event.data.folder -%}entrada
          {%- elif "C1_00626E8305E1" in trigger.event.data.folder -%}salon
          {%- else -%}desconocido{%-endif-%}
        turn_off_entity_id: >-
          {%- if "C1_00626E615161" in trigger.event.data.folder -%}switch.recibidor_camara_det_mov
          {%- elif "FI9853EP_00626E563E69" in trigger.event.data.folder -%}switch.piscina_camara_det_mov
          {%- elif "FI9900P_00626E6D21B2" in trigger.event.data.folder -%}switch.barbacoa_camara_det_mov
          {%- elif "WVC54CGA" in trigger.event.data.folder -%}switch.caseta_camara_det_mov
          {%- elif "puerta_principal" in trigger.event.data.folder -%}input_boolean.entrada_camara_det_mov
          {%- elif "C1_00626E8305E1" in trigger.event.data.folder -%}switch.salon_camara_det_mov
          {%- else -%}desconocido{%-endif-%}