# Notify living room motion sensor tampering
alias: '[Alarm] Notify office motion sensor tampering'
trigger: 
  platform: state
  entity_id: binary_sensor.despacho_sensor_movimiento_sabotaje
  to: 'on'
action:
  service: notify.telegram
  data:
    message: 'El sensor de movimento del despacho se ha manipulado'
