#alarm_arm_away:
#  alias: 'Alarm - Alarm arm away'
#  sequence:
#    # Turn on alarm related sensors
#    - service: homeassistant.turn_on
#      data:
#        entity_id: group.seguridad
#    # Arm alarm
#    - service: alarm_control_panel.alarm_arm_away
#      entity_id: alarm_control_panel.home

#alarm_arm_night:
#  alias: 'Alarm - Alarm arm night'
#  sequence:
#    # Turn on alarm related sensors
#    - service: homeassistant.turn_on
#      data:
#        entity_id: group.seguridad
#    # Alarm arm night
#    - service: alarm_control_panel.alarm_arm_night
#      entity_id: alarm_control_panel.home

alarm_disarm_telegram:
  alias: 'Alarm - Alarm disarm telegram'
  sequence:
    # Alarm disarm
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
    # Send message
    - service: telegram_bot.send_message
      data_template:
        message: 'Alarma desarmada manualmente desde Telegram'
        target: 
          - !secret hokusphone_telegram_chat_id
          #- !secret geniphone_telegram_chat_id
        disable_notification: false
        inline_keyboard:
               - 'Armar alarma:/alarm_control_panel.alarm_arm_away#alarm_control_panel.home'

#alarm_disarm_slack:
#  alias: '[Alarm - Control Panel] Alarm disarm from slack'
#  sequence:
#    # Alarm disarm
#    - service: alarm_control_panel.alarm_disarm
#      data:
#        entity_id: alarm_control_panel.home
#    # Send message
#    - service: notify.slack
#      data_template:
#        message: ''
#        data:
#          attachments:
#            - color: 'danger'
#              pretext: ':bell: *Alarma* :bell:'
#              text: 'Alarma desarmada desde slack'
#              fallback: 'Alarma'

alarm_disarm_telegram_temporary:
  alias: 'Alarm - Disarm telegram temporary'
  sequence:
    # Alarm disarm
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
    # Send message
    - service: telegram_bot.send_message
      data_template:
        message: 'Alarma desarmada durante {{data.minutes}} minutos desde Telegram'
        target: 
          - !secret hokusphone_telegram_chat_id
          #- !secret geniphone_telegram_chat_id
        disable_notification: false
        inline_keyboard:
               - 'Armar alarma:/alarm_control_panel.alarm_arm_away#alarm_control_panel.home'
    # Wait specified time before arming the alarm again
    - delay: "{{ data.minutes | multiply(60) | timestamp_custom('%H:%M:%S',False) }}"
    # Only rearm if nobody at home
    - condition: state
      entity_id: group.unidad_familiar
      state: 'not_home'
    # Alarm arm away
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.home