alarm_arm_away:
  alias: '[Alarm - Control Panel] Alarm arm away'
  sequence:
    # Turn on alarm related sensors
    - service: homeassistant.turn_on
      data:
        entity_id: group.seguridad
    # Arm alarm
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home

alarm_arm_night:
  alias: '[Alarm - Control Panel] Alarm arm night'
  sequence:
    # Turn on alarm related sensors
    - service: homeassistant.turn_on
      data:
        entity_id: group.seguridad
    # Alarm arm night
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home

alarm_disarm_telegram:
  alias: '[Alarm - Control Panel] Alarm disarm from telegram'
  sequence:
    # Alarm disarm
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
    # Send message
    - service: telegram_bot.send_message
      data_template:
        message: 'Alarma desarmada manualmente desde Telegram'
        target: 
          - !secret hokusphone_telegram_chat_id
          #- !secret geniphone_telegram_chat_id
        disable_notification: false
        inline_keyboard:
               - 'Armar alarma:/script.turn_on#script.alarm_arm_away'

alarm_disarm_slack:
  alias: '[Alarm - Control Panel] Alarm disarm from slack'
  sequence:
    # Alarm disarm
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
    # Send message
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'danger'
              pretext: ':bell: *Alarma* :bell:'
              text: 'Alarma desarmada desde slack'
              fallback: 'Alarma'

alarm_disarm_telegram_temporary:
  alias: '[Alarm - Control Panel] Disarm alarm temporary from telegram'
  sequence:
    # Alarm disarm
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
    # Send message
    - service: telegram_bot.send_message
      data_template:
        message: 'Alarma desarmada durante {{data.minutes}} minutos desde Telegram'
        target: 
          - !secret hokusphone_telegram_chat_id
          #- !secret geniphone_telegram_chat_id
        disable_notification: false
        inline_keyboard:
               - 'Armar alarma:/script.turn_on#script.alarm_arm_away'
    # Wait specified time before arming the alarm again
    - delay: "{{ data.minutes | multiply(60) | timestamp_custom('%H:%M:%S',False) }}"
    # Alarm arm away
    - service: script.turn_on
      data:
        entity_id: script.alarm_arm_away