alarm_notify_camera:
  alias: 'Alarm - Notify camera'
  sequence:
#    # Send the video to slack
#    - service: notify.slack
#      data_template:
#        message: 'Movimiento detectado en {{data.camera_name}}'
#        data:
#          file:
#            path: '{{data.file}}'
#
#    # Notify to slack
#    - service: notify.slack
#      data_template:
#        message: ''
#        data:
#          attachments:
#            - color: 'danger'
#              pretext: ':bell: *Alarma* :bell:'
#              text: 'Movimiento detectado en {{data.camera_name}}'
#              fallback: 'Alarma'
#            - color: 'danger'
#              title: '¿Qué quieres hacer?'
#              callback_id: 'alarma_{{data.camera_name}}'
#              attachment_type: 'default'
#              actions: 
#                - name: 'desactivar_{{data.camera_name}}'
#                  text: 'Desactivar det. mov. {{data.camera_name}}'
#                  type: 'button'
#                  value: 'homeassistant.turn_off#{{data.turn_off_entity_id}}'
#                - name: 'desarmar_alarma'
#                  text: 'Desarmar alarma'
#                  type: 'button'
#                  value: 'script.turn_on#script.alarm_disarm_slack'

    # Continue to notify in telegram only if jpg or mp4 video
    - condition: template
      value_template: '{{ "jpg" in file_path or "mp4" in file_path }}'

    # Notify to telegram
    - service_template: >-
        {%- if "jpg" in file_path -%}
          telegram_bot.send_photo
        {%- elif "mp4" in file_path -%}
          telegram_bot.send_video
        {%- endif -%}

      data_template:
        file: '{{file_path}}'
        caption: '{{message}}'
        target: 
          - !secret hokusphone_telegram_chat_id
          #- !secret geniphone_telegram_chat_id
        disable_notification: false
        inline_keyboard:
          - 'Desactivar det. mov. {{place}}:/homeassistant.turn_off#{{turn_off_entity_id}}'
          - 'Desarmar 30 mins:/30_mins, Desarmar 1 hora:/60_mins'
          - 'Desarmar 2 horas:/120_mins, Desarmar 3 horas:/180_mins'
          - 'Desarmar alarma:/script.turn_on#script.alarm_disarm_telegram'

alarm_notify_sensor:
  alias: 'Alarm - Notify sensor'
  sequence:
    # Send the notification
    - service: telegram_bot.send_message
      data_template:
        message: '{{message}}'
        target: 
          - !secret hokusphone_telegram_chat_id
          #- !secret geniphone_telegram_chat_id
        disable_notification: false
        inline_keyboard:
          - 'Desactivar sensor:/homeassistant.turn_off#{{turn_off_entity_id}}'
          - 'Desarmar 30 mins:/30_mins, Desarmar 1 hora:/60_mins'
          - 'Desarmar 2 horas:/120_mins, Desarmar 3 horas:/180_mins'
          - 'Desarmar alarma:/script.turn_on#script.alarm_disarm_telegram'

#alarm_notify_state_change_slack:
#  alias: '[Alarm - Notification] Notify alarm state changes to slack'
#  sequence:
#    - service: notify.slack
#      data_template:
#        message: ''
#        data:
#          blocks:
#            - type: section
#              text:
#                type: mrkdwn
#                text: ':bell: *Alarma* :bell:'
#            - type: section
#              text:
#                type: mrkdwn
#                text: '{{message}}'
