- alias: '[Security - Motion detection] Trigger motion detected in camera for 30 seconds'
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  action:
    - service: mqtt.publish
      data_template:
        payload_template: 1
        retain: true
        topic: >- 
            {%- if "C1_00626E615161" in trigger.event.data.folder -%}home/sensor/camera/recibidor/alarm
            {%- elif "FI9853EP_00626E563E69" in trigger.event.data.folder -%}home/sensor/camera/piscina/alarm
            {%- elif "FI9900P_00626E6D21B2" in trigger.event.data.folder -%}home/sensor/camera/barbacoa/alarm
            {%- elif "WVC54CGA" in trigger.event.data.folder -%}home/sensor/camera/caseta/alarm
            {%- elif "puerta_principal" in trigger.event.data.folder -%}home/sensor/camera/entrada/alarm
            {%- elif "C1_00626E8305E1" in trigger.event.data.folder -%}home/sensor/camera/salon/alarm
            {%- else -%}desconocido{%-endif-%}
    - delay:
        seconds: 30
    - service: mqtt.publish
      data_template:
        payload: 0
        retain: true
        topic:  >- 
            {%- if "C1_00626E615161" in trigger.event.data.folder -%}home/sensor/camera/recibidor/alarm
            {%- elif "FI9853EP_00626E563E69" in trigger.event.data.folder -%}home/sensor/camera/piscina/alarm
            {%- elif "FI9900P_00626E6D21B2" in trigger.event.data.folder -%}home/sensor/camera/barbacoa/alarm
            {%- elif "WVC54CGA" in trigger.event.data.folder -%}home/sensor/camera/caseta/alarm
            {%- elif "puerta_principal" in trigger.event.data.folder -%}home/sensor/camera/entrada/alarm
            {%- elif "C1_00626E8305E1" in trigger.event.data.folder -%}home/sensor/camera/salon/alarm
            {%- else -%}desconocido{%-endif-%}
    - service: logbook.log
      data_template:
        name: >-
            {%- if "C1_00626E615161" in trigger.event.data.folder -%}Recibidor
            {%- elif "FI9853EP_00626E563E69" in trigger.event.data.folder -%}Piscina
            {%- elif "FI9900P_00626E6D21B2" in trigger.event.data.folder -%}Barbacoa
            {%- elif "WVC54CGA" in trigger.event.data.folder -%}Caseta
            {%- elif "puerta_principal" in trigger.event.data.folder -%}Entrada principal
            {%- elif "C1_00626E8305E1" in trigger.event.data.folder -%}Salón
            {%- else -%}desconocido{%-endif-%}
        message: 'Movimiento detectado'
        entity_id: >-
            {%- if "C1_00626E615161" in trigger.event.data.folder -%}camera.recibidor
            {%- elif "FI9853EP_00626E563E69" in trigger.event.data.folder -%}camera.piscina
            {%- elif "FI9900P_00626E6D21B2" in trigger.event.data.folder -%}camera.barbacoa
            {%- elif "WVC54CGA" in trigger.event.data.folder -%}camera.caseta
            {%- elif "puerta_principal" in trigger.event.data.folder -%}camera.entrada
            {%- elif "C1_00626E8305E1" in trigger.event.data.folder -%}camera.salon
            {%- else -%}desconocido{%-endif-%}
        domain: camera
