- alias: '[Presence - Holiday] Enters on holiday mode based on google calendar event'
  trigger:
    platform: state
    entity_id: calendar.holiday_mode
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.holiday
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'good'
              pretext: ':bust_in_silhouette: *Presencia* :bust_in_silhouette:'
              text: 'Modo vacaciones activado'
              fallback: 'Presencia'

- alias: '[Presence - Holiday] Exits on holiday mode based on google calendar event'
  trigger:
    platform: state
    entity_id: calendar.holiday_mode
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.holiday
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'good'
              pretext: ':bust_in_silhouette: *Presencia* :bust_in_silhouette:'
              text: 'Modo vacaciones desactivado'
              fallback: 'Presencia'

- alias: '[Presence - Holiday] Enters holiday mode based on switch state'
  trigger:
    platform: state
    entity_id: switch.holiday
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{states.climate.netatmo_general != None}}"
      - condition: template
        value_template: "{{not is_state('climate.netatmo_general', 'off')}}"
  action:
    # Turn off thermostat
    - service: script.turn_on
      entity_id: script.climate_power_off
    - service: notify.telegram
      data:
        message: 'Modo vacaciones activado'
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'good'
              pretext: ':bust_in_silhouette: *Presencia* :bust_in_silhouette:'
              text: 'Modo vacaciones activado'
              fallback: 'Presencia'

- alias: '[Presence - Holiday] Exits holiday mode based on switch state'
  trigger:
    platform: state
    entity_id: switch.holiday
    from: 'on'
    to: 'off'
  condition:
    condition: template
    value_template: "{{not is_state('climate.netatmo_general', 'off')}}"
  action:
    # Set thermostat away mode 
    - service: climate.set_preset_mode
      entity_id: climate.netatmo_general
      data_template:
        preset_mode: 'away'
    - service: notify.telegram
      data:
        message: 'Modo vacaciones desactivado'
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'good'
              pretext: ':bust_in_silhouette: *Presencia* :bust_in_silhouette:'
              text: 'Modo vacaciones desactivado'
              fallback: 'Presencia'
