- alias: '[Presence - Jordi] Jordi arriving home in Ioniq'
  trigger:
     - platform: zone
       entity_id: device_tracker.car_ioniq
       zone: zone.home
       event: enter
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.outside_fence_sensor_state
        state: 'on'
      - condition: state
        entity_id: binary_sensor.car_ioniq_state
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.barrera
    - service: mqtt.publish
      data:
        payload_template: >
          He abierto la barrera. {%- if is_state("person.geni", "home") -%}Jeni est치 en casa.{%- else -%}Jeni no est치 en casa.{%- endif -%}
        retain: false
        topic: 'phone/sensor/hokus/cmnd/say'
    - delay:
        seconds: 5
    - service: telegram_bot.send_message
      data_template:
        message: 'Barrera abierta autom치ticamente'
        target: !secret hokusphone_telegram_chat_id
        inline_keyboard: 
          - 'Cerrar:/switch.turn_on#switch.barrera'

- alias: '[Presence - Jordi] Jordi leaving home in Ioniq'
  trigger:
     - platform: zone
       entity_id: device_tracker.car_ioniq
       zone: zone.home
       event: leave
  condition:
    - condition: state
      entity_id: binary_sensor.car_ioniq_state
      state: 'on'
  action:
    - service: mqtt.publish
      data:
        payload_template: >
          {%- if is_state("group.unidad_familiar", "not_home") -%}{%- if is_state("sensor.outside_fence", "Abierta") -%}Te has dejado la barrera abierta, la voy a cerrar. {%- endif -%}{%- if is_state("sensor.cocina_sensor_puerta", "Abierta") %}Puerta de la cocina abierta. {% endif -%}{%- if is_state("sensor.cocina_sensor_persiana", "Abierta") %}Persiana de la cocina abierta. {% endif -%}{%- endif -%}La previsi칩n del tiempo es de {{ states.sensor.dark_sky_summary_0d.state | replace(" C."," grados") }}
        retain: false
        topic: 'cmnd/sensor/phone/hokus/say'
    - service_template: >
        {%- if is_state("group.unidad_familiar", "not_home") -%}
          {%- if is_state("sensor.outside_fence_sensor_state", "off") -%}
            homeassistant.turn_on
          {%- else -%}
            homeassistant.update_entity
          {%- endif -%}
        {%- endif -%}

      data:
        entity_id: switch.barrera
