- alias: '[Presence - Notification] Jordi at home'
  trigger:
    - platform: state
      entity_id: person.jordi
      to: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Jordi est치 en casa'

- alias: '[Presence - Notification] Jordi not at home'
  trigger:
    - platform: state
      entity_id: person.jordi
      from: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Jordi no est치 en casa'

- alias: '[Presence - Notification] Geni at home'
  trigger:
    - platform: state
      entity_id: person.geni
      to: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Geni est치 en casa'

- alias: '[Presence - Notification] Geni not at home'
  trigger:
    - platform: state
      entity_id: person.geni
      from: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Geni no est치 en casa'

- alias: '[Presence - Notification] Guest at home'
  trigger:
    - platform: state
      entity_id: person.guest
      to: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Invitado en casa'

- alias: '[Presence - Notification] Guest not at home'
  trigger:
    - platform: state
      entity_id: person.guest
      from: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Invitado fuera de casa'

- alias: '[Presence - Notification] Someone at home'
  trigger:
    - platform: state
      entity_id: group.unidad_familiar
      to: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'Alguien en casa'

- alias: '[Presence - Notification] No one at home'
  trigger:
    - platform: state
      entity_id: group.unidad_familiar
      from: 'home'
  action:
    - service: script.presence_notify_state_change_slack
      data_template:
        message: 'No hay nadie en casa'

- alias: '[Presence - Notification] Notify for new devices'
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.telegram
      data_template:
        message: >
          Nuevo dispositivo detectado:
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
        title: Nuevo dispositivo
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'warning'
              text: ':iphone: *Nuevo dispositivo* :iphone:'
              fields:
                - title: 'Nombre'
                  value: '{{trigger.event.data.host_name}}'
                  short: true
                - title: 'Entidad'
                  value: '{{trigger.event.data.entity_id}}'
                  short: true
              fallback: 'Nuevo dispositivo'
