alias: '[Presence] Authorized person not home'
trigger:
  - platform: state
    entity_id: device_tracker.virtual_device
    from: 'home'
action:
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'good'
            pretext: ':bust_in_silhouette: *Presencia* :bust_in_silhouette:'
            text: 'Persona autorizada fuera de casa'
            fallback: 'Presencia'