# Empty home automation when no one of the Familia group is at home
alias: '[Presence] Empty home'
trigger:
  platform: state
  entity_id: group.unidad_familiar
  to: 'not_home'
action:
  - service: script.turn_on
    data:
      entity_id: script.presence_empty_home