alias: '[Presence] When Barrera open, cast entrada camera to Suite'
trigger:
  platform: state
  entity_id: cover.outside_fence
  to: 'open'
condition:
  condition: state
  entity_id: alarm_control_panel.home
  state: 'armed_night'
action:
  - delay:
      seconds: 15
  - service: camera.play_stream
    data:
      entity_id: 'camera.entrada'
      media_player: 'media_player.suite'
