alias: '[Presence] Geni not home'
trigger:
  - platform: state
    entity_id: person.geni
    from: 'home'
action:
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'good'
            pretext: ':woman: *Presencia* :woman:'
            text: 'Geni está fuera de casa'
            fallback: 'Presencia'