alias: '[Presence] When Barrera closed, stop cast to Suite'
trigger:
  platform: state
  entity_id: cover.outside_fence
  to: 'closed'
condition:
  condition: state
  entity_id: alarm_control_panel.home
  state: 'armed_night'
action:
  - service: media_player.turn_off
    entity_id: 'media_player.suite'