alias: '[Presence] Geni at home'
trigger:
  - platform: state
    entity_id: person.geni
    to: 'home'
action:
  - service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - color: 'good'
            pretext: ':woman: *Presencia* :woman:'
            text: 'Geni está en casa'
            fallback: 'Presencia'