  # When input_boolean.empty_home_activation_delay turns on,
  # Change virtual_device location to home
  # Wait the specified amount of minutes 
  # Turn off input_boolean.empty_home_activation_delay
alias: '[Presence] empty_home_activation_delay on'
trigger:
  platform: state
  entity_id: input_boolean.empty_home_activation_delay
  to: 'on'
action:
  - service: device_tracker.see
    data:
      dev_id: 'virtual_device'
      location_name: 'home'
  - delay: 00:00:10
  - service: homeassistant.turn_on
    data:
      entity_id: group.seguridad
  - service: notify.telegram
    data_template:
      message: >
        Activada persona autorizada durante {{ (states.input_number.empty_home_activation_delay_minutes.state | int) // 60 }} hora(s) y {{ (states.input_number.empty_home_activation_delay_minutes.state | int) % 60 }} minutos
  - delay: '{{ (states.input_number.empty_home_activation_delay_minutes.state | int) // 60 }}:{{ (states.input_number.empty_home_activation_delay_minutes.state | int) % 60 }}'
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.empty_home_activation_delay