# Turn on hall lamp when someone at home and the sun is set
alias: '[Presence] Turn on hall lamp when someone arrives at home and the sun is set'
trigger:
  platform: state
  entity_id: group.unidad_familiar
  to: 'home'
condition:
  condition: sun
  after: sunset
action:
  - service: switch.turn_on
    data:
      entity_id: switch.entrance_hall_lamp_switch