  # When input_boolean.empty_home_activation_delay turns off,
  # Change virtual_device location to not_home
alias: '[Presence] empty_home_activation_delay off'
trigger:
  platform: state
  entity_id: input_boolean.empty_home_activation_delay
  to: 'off'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.seguridad
  - delay: 00:00:10
  - service: device_tracker.see
    data:
      dev_id: 'virtual_device'
      location_name: 'not_home'