# Someone home automation when someone of the Familia group is at home
alias: '[Presence] Someone home'
trigger:
  platform: state
  entity_id: group.unidad_familiar
  to: 'home'
action:
  - service: script.turn_on
    data:
      entity_id: script.presence_someone_home