comfort_mode_on:
  alias: 'Comfort - Mode on'
  sequence:
    # Set thermostat boost mode 
    - service: climate.set_preset_mode
      entity_id: climate.netatmo_general
      data_template:
        preset_mode: 'boost'
    - delay:
        seconds: 15
    # Update entity
    - service: homeassistant.update_entity
      entity_id: climate.netatmo_general
    - delay:
         minutes: 90
    # Turn off comfort mode (after 90 minutes)
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.home_comfort_mode

comfort_mode_off:
  alias: 'Comfort - Mode off'
  sequence:
    # Set thermostat Schedule mode 
    - service: climate.set_preset_mode
      entity_id: climate.netatmo_general
      data_template:
        preset_mode: 'Schedule'
    - delay:
        seconds: 15
    # Update entity
    - service: homeassistant.update_entity
      entity_id: climate.netatmo_general
