goto_sleep:
  alias: '[Comfort - Misc] Go to sleep'
  sequence:
    # Only execute script between 21:00 and 6:00
    - condition: time
      after: '21:00'
      before: '6:00'
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: script.go_to_sleep_inside_lights
      data_template:
        data:
          logbook_message: 'configuradas para ir a dormir'
    - service: script.go_to_sleep_outside_lights
      data_template:
        data:
          logbook_message: 'configuradas para ir a dormir'
    # Close fence if open
    - service_template: >
        {%- if is_state("sensor.outside_fence", "Abierta") -%}
          homeassistant.turn_on
        {%- else -%}
          homeassistant.update_entity
        {%- endif -%}

      data:
        entity_id: switch.barrera
    # Alarm arm night
    - service: script.turn_on
      data:
        entity_id: script.alarm_arm_night
      # Notify found incidences and say good night.
    - service: tts.google_translate_say
      entity_id: media_player.recibidor
      data_template:
        message: >
          {%- if states("sensor.car_ioniq_state_soc_display")|float < 45 %}Batería del coche al {{states("sensor.car_ioniq_state_soc_display")}} por ciento. {% endif %}
          {%- if is_state("binary_sensor.porche_sensor_puerta", "on") %}Puerta de la cocina abierta. {% endif %}
          {%- if is_state("binary_sensor.porche_sensor_persiana", "on") %}Persiana de la cocina abierta. {% endif %}
          {%- if is_state("binary_sensor.coladuria_sensor_puerta", "on") %}Puerta de la coladuría abierta. {% endif %}
          {%- if is_state("sensor.outside_fence", "Abierta") -%}Cerrando barrera.{% endif -%}
          Alarma armada en modo noche.

jordi_on_bed:
  alias: '[Comfort - Misc] Jordi On bed'
  sequence:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - service: script.turn_off_inside_lights
      data_template:
        data:
          logbook_message: 'apagadas porque Jordi ya está en la cama'
