jordi_in_bed:
  alias: 'Jordi in bed'
  sequence:
    - event: bed_occupancy_changed
      event_data:
        state: 'in_bed'
        bed_id: 'jordi'

jordi_not_in_bed:
  alias: 'Jordi not in bed'
  sequence:
    - event: bed_occupancy_changed
      event_data:
        state: 'not_in_bed'
        bed_id: 'jordi'

#speech_set_tts_volume_level:
#  alias: '[Comfort - Misc] Lower the home-assistant tts volume level between 22 and 8:30'
#  sequence:
#    - condition: time
#      after: '22:00'
#      before: '8:30'
#    - service: media_player.volume_set
#      entity_id: media_player.recibidor
#      data:
#        volume_level: 0.25
#    - delay:
#        minutes: 2
#    - service: media_player.volume_set
#      entity_id: media_player.recibidor
#      data:
#        volume_level: 0.65
