jordi_on_bed:
  alias: '[Comfort - Misc] Jordi On bed'
  sequence:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - service: script.turn_off_inside_lights
      data_template:
        data:
          logbook_message: 'apagadas porque Jordi ya está en la cama'

speech_set_tts_volume_level:
  alias: '[Comfort - Misc] Lower the home-assistant tts volume level between 22 and 8:30'
  sequence:
    - condition: time
      after: '22:00'
      before: '8:30'
    - service: media_player.volume_set
      entity_id: media_player.recibidor
      data:
        volume_level: 0.25
    - delay:
        minutes: 2
    - service: media_player.volume_set
      entity_id: media_player.recibidor
      data:
        volume_level: 0.65
