- alias: '[Swimming Pool - Pump] Turn on swimming pool pump'
  trigger: 
    platform: template
    value_template: '{{states.sensor.date_time.state == states.sensor.piscina_on_time.state}}'
  action:
    - service: switch.turn_on
      entity_id: switch.motor_piscina
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'warning'
              pretext: ':swimmer: *Piscina* :swimmer:'
              text: 'Motor piscina encendido'
              fallback: 'Piscina'


- alias: '[Swimming Pool - Pump] Turn off swimming pool pump'
  trigger: 
    platform: template
    value_template: '{{states.sensor.date_time.state == states.sensor.piscina_off_time.state}}'
  action:
    - service: switch.turn_off
      entity_id: switch.motor_piscina
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: 'good'
              pretext: ':swimmer: *Piscina* :swimmer:'
              text: 'Motor piscina apagado'
              fallback: 'Piscina'
